<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
	  <PackageReference Include="log4net" Version="3.3.1" />
	  <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RACommon\RACommon.csproj" />
    <ProjectReference Include="..\RAContract\RAContract.csproj" />
    <ProjectReference Include="..\RADB\RADB.csproj" />
    <ProjectReference Include="..\RAManualApproval\RAManualApproval.csproj" />
  </ItemGroup>

</Project>
