/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */



using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Net;
using System.IO;
using AvePoint.GCommon;
using AvePoint.GCommon.Contract.Server.Common;
using AvePoint.GCommon.Contract.Tree.Object;
using AvePoint.Wrapper.Common;
using System.Diagnostics.CodeAnalysis;

namespace AvePoint.ObjectModel.Common
{
    public class AveSPServerVersion
    {
        private static AveLogger Logger = AveLogger.GetInstance(typeof(AveSPServerVersion));
        private string mSiteUrl;
        private string mDigestInfo;
        private AveAuthenticationMode mAveAuthMode;
        private AuthenticationResult mCredential;

        [SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Justification = "SharePoint path")]
        internal AveSPServerVersion(string siteUrl, string digestInfo, AuthenticationResult result, AveAuthenticationMode avemode)
        {
            mSiteUrl = siteUrl;
            mDigestInfo = digestInfo;
            mCredential = result;
            mAveAuthMode = avemode;
        }


        /// <summary>
        /// This Request is generated by code:
        ///    //        ClientContext cts = new ClientContext("http://win-cpqm71buqvj:1000/sites/LocalTerm");        
        ///    //cts.Load(cts.Site, ss => ss.Url, ss => ss.Id);
        ///    //cts.ExecuteQuery();
        /// </summary>
        /// <returns></returns>
        public AveServerVersion GetSPServerVersion()
        {
            AveServerVersion serverVersion = new AveServerVersion();
            serverVersion.SiteUrl = mSiteUrl;
            serverVersion.Version = GetSPVersion();
            serverVersion.VersionType = ParseVersion(serverVersion.Version, mAveAuthMode);

            return serverVersion;
        }

        public static AveServerVersion ConvertServerVersoin(string siteUrl,string version, AveAuthenticationMode authMode)
        {
            AveServerVersion serverVersion = new AveServerVersion();
            serverVersion.SiteUrl = siteUrl;
            serverVersion.Version = version;
            serverVersion.VersionType = ParseVersion(serverVersion.Version, authMode);

            return serverVersion;
        }

        private string GetSPVersion()
        {
            try
            {
                try
                {
                    return GetSPVersionV1(this.mSiteUrl, this.mCredential);
                }
                catch (Exception e)
                {
                    Logger.Warn("An error occurred while get sp version, error: {0}", e);
                    return GetSPVersionV2(mSiteUrl, this.mCredential);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        private string GetSPVersionV2(string siteUrl, AuthenticationResult credential)
        {
            Uri uri = new Uri(siteUrl);
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
            request.AllowAutoRedirect = false;
            credential.SetCredential2Request(siteUrl, request as WebRequest);
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            return response.Headers["MicrosoftSharePointTeamServices"].ToString();
        }

        private string GetSPVersionV1(string siteUrl, AuthenticationResult credential)
        {
            Uri targetUri = new Uri(siteUrl.TrimEnd('/') + "/_vti_bin/client.svc/ProcessQuery");
            ReconnectableHttpWebRequest csomService = ReconnectableHttpWebRequest.CreateRequest(targetUri);
            csomService.Timeout = 0x2bf20;
            csomService.Method = "POST";
            csomService.ContentType = "text/xml";
            csomService.Headers["X-RequestDigest"] = mDigestInfo;
            csomService.Headers["X-RequestForceAuthentication"] = "true";
            byte[] content = Encoding.UTF8.GetBytes("<Request AddExpandoFieldTypeSuffix=\"true\" SchemaVersion=\"14.0.0.0\" LibraryVersion=\"14.0.4762.1000\" ApplicationName=\".NET Library\" xmlns=\"http://schemas.microsoft.com/sharepoint/clientquery/2009\"><Actions><ObjectPath Id=\"2\" ObjectPathId=\"1\" /><ObjectPath Id=\"4\" ObjectPathId=\"3\" /><Query Id=\"5\" ObjectPathId=\"3\"><Query SelectAllProperties=\"false\"><Properties><Property Name=\"Url\" ScalarProperty=\"true\" /><Property Name=\"Id\" ScalarProperty=\"true\" /></Properties></Query></Query></Actions><ObjectPaths><StaticProperty Id=\"1\" TypeId=\"{3747adcd-a3c3-41b9-bfab-4a64dd2f1e0a}\" Name=\"Current\" /><Property Id=\"3\" ParentId=\"1\" Name=\"Site\" /></ObjectPaths></Request>");
            csomService.ContentLength = content.Length;
            credential.SetCredential2Request(siteUrl, csomService as WebRequest);
            using (System.IO.Stream requestStream = csomService.GetRequestStream())
            {
                requestStream.Write(content, 0, content.Length);
                requestStream.Flush();
            }
            HttpWebResponse response = csomService.GetResponse() as HttpWebResponse;
            using (System.IO.Stream responseStream = response.GetResponseStream())
            {
                StreamReader responseReader = new StreamReader(responseStream);
                string csomResponse = responseReader.ReadToEnd();

                var propertiesList = AveJsonUtility.GetDictionaryFromJsonString(csomResponse);

                var contextProperties = propertiesList[0];
                return contextProperties["LibraryVersion"].ToString();
            }
        }

        private static AveSPServerVersionType ParseVersion(string serverVersion, AveAuthenticationMode authMode)
        {
            if (serverVersion.StartsWith("12.", StringComparison.OrdinalIgnoreCase))
            {
                return AveSPServerVersionType.SP2007;
            }
            else if (serverVersion.StartsWith("14.", StringComparison.OrdinalIgnoreCase))
            {
                return AveSPServerVersionType.SP2010;
            }
            else if (serverVersion.StartsWith("15.", StringComparison.OrdinalIgnoreCase))
            {
                return AveSPServerVersionType.SP2013;
            }
            else if (serverVersion.StartsWith("16.", StringComparison.OrdinalIgnoreCase))
            {

                return (AveAuthenticationMode.Online & authMode) != 0
                    ? AveSPServerVersionType.Office365
                    : IsSP2016Version(serverVersion) ? AveSPServerVersionType.SP2016 : (IsSP2019Version(serverVersion) ? AveSPServerVersionType.SP2019 : AveSPServerVersionType.SPSE);
            }
            return AveSPServerVersionType.None;
        }
        private static bool IsSP2016Version(string serverVersion)
        {
            var version = new Version(serverVersion);
            return version.Build <= 9999;//4位数是16 5位数是19
        }
        private static bool IsSP2019Version(string serverVersion)
        {
            var version = new Version(serverVersion);
            return version.Build >= 9999 && version.Build < 14326;//4位数是16 5位数是19,SE Version should greater than 14326
        }
    }
}
