/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Wrapper.Resource.Workflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WrapperWorkflowResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WrapperWorkflowResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Wrapper.Resource.Workflow.WrapperWorkflowResource", typeof(WrapperWorkflowResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding list to dictionary .Message:{0}..
        /// </summary>
        public static string AddListToDictionaryError {
            get {
                return ResourceManager.GetString("AddListToDictionaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while created addtional node for workflow, message:{0}..
        /// </summary>
        public static string AddtionalNodeCreateError {
            get {
                return ResourceManager.GetString("AddtionalNodeCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding workflow to page .Message:{0}..
        /// </summary>
        public static string AddWorkFlowToPageError {
            get {
                return ResourceManager.GetString("AddWorkFlowToPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while caching data for workflow. Error massage:{0}..
        /// </summary>
        public static string CacheDataError {
            get {
                return ResourceManager.GetString("CacheDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calling method. message:{0}..
        /// </summary>
        public static string CallMethodError {
            get {
                return ResourceManager.GetString("CallMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing node value.Message:{0}..
        /// </summary>
        public static string ChangeNodeValueError {
            get {
                return ResourceManager.GetString("ChangeNodeValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking out file .Message:{0}..
        /// </summary>
        public static string CheckOutFileError {
            get {
                return ResourceManager.GetString("CheckOutFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while comparing association unit .Message:{0}..
        /// </summary>
        public static string CompareAssociationUnitError {
            get {
                return ResourceManager.GetString("CompareAssociationUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading configuration file for workflow, message:{0}..
        /// </summary>
        public static string ConfigFileLoadError {
            get {
                return ResourceManager.GetString("ConfigFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update workflow configuration error. Message:{0}..
        /// </summary>
        public static string ConfigurationUpdateError {
            get {
                return ResourceManager.GetString("ConfigurationUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting database .Message:{0}..
        /// </summary>
        public static string ConnectDataBaseError {
            get {
                return ResourceManager.GetString("ConnectDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while converting objcet to list.Message:{0}..
        /// </summary>
        public static string ConvertObjectToListError {
            get {
                return ResourceManager.GetString("ConvertObjectToListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating list for workflow.List:{0} .Message:{0}..
        /// </summary>
        public static string CreateWorkflowListError {
            get {
                return ResourceManager.GetString("CreateWorkflowListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting default content approval workflow id, message:{0}..
        /// </summary>
        public static string DefaultContentApprovalIdSetError {
            get {
                return ResourceManager.GetString("DefaultContentApprovalIdSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while excuting deserializing .Message:{0}..
        /// </summary>
        public static string ExcyteDeSerializeError {
            get {
                return ResourceManager.GetString("ExcyteDeSerializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SPField failed, message:{0}..
        /// </summary>
        public static string FieldCreatedFailed {
            get {
                return ResourceManager.GetString("FieldCreatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find enum type as we known. Message:{0}..
        /// </summary>
        public static string FindEnumTypeFaild {
            get {
                return ResourceManager.GetString("FindEnumTypeFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the site owner.Message:{0}..
        /// </summary>
        public static string FindSiteOwnerFaild {
            get {
                return ResourceManager.GetString("FindSiteOwnerFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fixing up reference. message:{0}..
        /// </summary>
        public static string FixUpReferenceError {
            get {
                return ResourceManager.GetString("FixUpReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate spfile unit error, message:{0}..
        /// </summary>
        public static string GenerateSPFileUnitError {
            get {
                return ResourceManager.GetString("GenerateSPFileUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting duration. message:{0}..
        /// </summary>
        public static string GetDurationError {
            get {
                return ResourceManager.GetString("GetDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get fields schema xml,field name:{0},  message:{1}..
        /// </summary>
        public static string GetFieldsSchemaXMLError {
            get {
                return ResourceManager.GetString("GetFieldsSchemaXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting file by name .Message:{0}..
        /// </summary>
        public static string GetFileByNameError {
            get {
                return ResourceManager.GetString("GetFileByNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting folder from parnet .Message:{0}..
        /// </summary>
        public static string GetFolderFromParentError {
            get {
                return ResourceManager.GetString("GetFolderFromParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting  item attribute  .Message:{0}..
        /// </summary>
        public static string GetItemAttributeError {
            get {
                return ResourceManager.GetString("GetItemAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting item by unique id .Message:{0}..
        /// </summary>
        public static string GetItemByUniqueIdError {
            get {
                return ResourceManager.GetString("GetItemByUniqueIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting list by id .Message:{0}..
        /// </summary>
        public static string GetListByIdError {
            get {
                return ResourceManager.GetString("GetListByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting login name by id.Message:{0}..
        /// </summary>
        public static string GetLoginNameByIdError {
            get {
                return ResourceManager.GetString("GetLoginNameByIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting object type. message:{0}..
        /// </summary>
        public static string GetObjectTypeError {
            get {
                return ResourceManager.GetString("GetObjectTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting pricipal from web.Message:{0}..
        /// </summary>
        public static string GetPricipalFromWebError {
            get {
                return ResourceManager.GetString("GetPricipalFromWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting status field schema.Message:{0}..
        /// </summary>
        public static string GetStatusFieldSchemaError {
            get {
                return ResourceManager.GetString("GetStatusFieldSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting workflow association data   .Message:{0}..
        /// </summary>
        public static string GetWorkflowAssociationDataError {
            get {
                return ResourceManager.GetString("GetWorkflowAssociationDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting workflow field type .Message:{0}..
        /// </summary>
        public static string GetWorkflowFieldTypeError {
            get {
                return ResourceManager.GetString("GetWorkflowFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fixing up guid mapping, message:{0}..
        /// </summary>
        public static string GuidMappingFixingUpError {
            get {
                return ResourceManager.GetString("GuidMappingFixingUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while mapping language for workflow. Error massage:{0}..
        /// </summary>
        public static string LanguageMappingError {
            get {
                return ResourceManager.GetString("LanguageMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading assemby  message:{0}..
        /// </summary>
        public static string LoadAssemblyError {
            get {
                return ResourceManager.GetString("LoadAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading xml content, message:{0}..
        /// </summary>
        public static string LoadXmlContentError {
            get {
                return ResourceManager.GetString("LoadXmlContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while mapping language for workflow, message:{0}..
        /// </summary>
        public static string MappingLanguageError {
            get {
                return ResourceManager.GetString("MappingLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while mapping user for workflow. Error massage:{0}..
        /// </summary>
        public static string MappingUserError {
            get {
                return ResourceManager.GetString("MappingUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor error when load assembly for nintex database. Error message:{0}..
        /// </summary>
        public static string NintexDBLoadAssemblyError {
            get {
                return ResourceManager.GetString("NintexDBLoadAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace user error in nintex workflow. Error:{0}.
        /// </summary>
        public static string NintexReplaceUserError {
            get {
                return ResourceManager.GetString("NintexReplaceUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load permission unit error while serializing data. Error massage:{0}..
        /// </summary>
        public static string PermissionUnitLoadError {
            get {
                return ResourceManager.GetString("PermissionUnitLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save permission unit error while serializing data. Error massage:{0}..
        /// </summary>
        public static string PermissionUnitSaveError {
            get {
                return ResourceManager.GetString("PermissionUnitSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while doing post action for workflow. Error massage:{0}..
        /// </summary>
        public static string PostActionError {
            get {
                return ResourceManager.GetString("PostActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while recalculating running instance count .Message:{0}..
        /// </summary>
        public static string RecalculateRunningInstanceCountError {
            get {
                return ResourceManager.GetString("RecalculateRunningInstanceCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reloading parent item.Message:{0}..
        /// </summary>
        public static string ReloadParentItemError {
            get {
                return ResourceManager.GetString("ReloadParentItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing dependency object value.Message:{0}..
        /// </summary>
        public static string ReplaceDependencyObjectValueError {
            get {
                return ResourceManager.GetString("ReplaceDependencyObjectValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing user for feed back.Message:{0}..
        /// </summary>
        public static string ReplaceUserForFeedbackError {
            get {
                return ResourceManager.GetString("ReplaceUserForFeedbackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing user for sharepoint 2010.Message:{0}..
        /// </summary>
        public static string ReplaceUserForSP2010Error {
            get {
                return ResourceManager.GetString("ReplaceUserForSP2010Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing user for tree state.Message:{0}..
        /// </summary>
        public static string ReplaceUserForTreeStateError {
            get {
                return ResourceManager.GetString("ReplaceUserForTreeStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while resetting duration. message:{0}..
        /// </summary>
        public static string ResetDurationError {
            get {
                return ResourceManager.GetString("ResetDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring workflow sub item  .Message:{0}..
        /// </summary>
        public static string ResotreWFSubItemError {
            get {
                return ResourceManager.GetString("ResotreWFSubItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restore associal unit  .Message:{0}..
        /// </summary>
        public static string RestoreAssocialUnitError {
            get {
                return ResourceManager.GetString("RestoreAssocialUnitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring custom data for workflow, message:{0}..
        /// </summary>
        public static string RestoreCustomDataError {
            get {
                return ResourceManager.GetString("RestoreCustomDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restore file .Message:{0}..
        /// </summary>
        public static string RestoreFileError {
            get {
                return ResourceManager.GetString("RestoreFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring workflow instance..
        /// </summary>
        public static string RestoreWFInError {
            get {
                return ResourceManager.GetString("RestoreWFInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring workflow instance..
        /// </summary>
        public static string RestoreWFInUnexpectError {
            get {
                return ResourceManager.GetString("RestoreWFInUnexpectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have the permission of the workflow..
        /// </summary>
        public static string RestoreWFWithoutPermission {
            get {
                return ResourceManager.GetString("RestoreWFWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load mapping for workflow error. Error message:{0}..
        /// </summary>
        public static string RuntimeLoadMappingError {
            get {
                return ResourceManager.GetString("RuntimeLoadMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting  item attribute  .Message:{0}..
        /// </summary>
        public static string SetItemAttributeError {
            get {
                return ResourceManager.GetString("SetItemAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting unique id .Message:{0}..
        /// </summary>
        public static string SetItemUniqueIdError {
            get {
                return ResourceManager.GetString("SetItemUniqueIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting list workflow id .Message:{0}..
        /// </summary>
        public static string SetListWFIdError {
            get {
                return ResourceManager.GetString("SetListWFIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the running workflow Instance..
        /// </summary>
        public static string SkipRunningWFInError {
            get {
                return ResourceManager.GetString("SkipRunningWFInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to sql database, message:{0}..
        /// </summary>
        public static string SqlConnInitError {
            get {
                return ResourceManager.GetString("SqlConnInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting or adding status column, column name:{0},  message:{1}..
        /// </summary>
        public static string StatusColumnGetorAddError {
            get {
                return ResourceManager.GetString("StatusColumnGetorAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking status field name, message:{0}..
        /// </summary>
        public static string StatusFieldNameIsAvailble {
            get {
                return ResourceManager.GetString("StatusFieldNameIsAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status field error.Field internal name:{0}, message:{1}..
        /// </summary>
        public static string StatusFieldSetError {
            get {
                return ResourceManager.GetString("StatusFieldSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting sub list information. Message:{0}..
        /// </summary>
        public static string SubListInfoGetError {
            get {
                return ResourceManager.GetString("SubListInfoGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating association name.Message:{0}..
        /// </summary>
        public static string UpdateAssociationNameError {
            get {
                return ResourceManager.GetString("UpdateAssociationNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating configration .Message:{0}..
        /// </summary>
        public static string UpdateConfigrationTimeError {
            get {
                return ResourceManager.GetString("UpdateConfigrationTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while update created time .Message:{0}..
        /// </summary>
        public static string UpdateCreatedTime {
            get {
                return ResourceManager.GetString("UpdateCreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating list .Message:{0}..
        /// </summary>
        public static string UpdateListError {
            get {
                return ResourceManager.GetString("UpdateListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating modify time error.Message:{0}..
        /// </summary>
        public static string UpdateModifyTimeError {
            get {
                return ResourceManager.GetString("UpdateModifyTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating status field name.Message:{0}..
        /// </summary>
        public static string UpdateStatusFieldNameError {
            get {
                return ResourceManager.GetString("UpdateStatusFieldNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing user for workflow.Message:{0}..
        /// </summary>
        public static string UserReplaceError {
            get {
                return ResourceManager.GetString("UserReplaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Get web url .Message:{0}..
        /// </summary>
        public static string WebUrlGetFailed {
            get {
                return ResourceManager.GetString("WebUrlGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow definition you want to restore conflicts with the existing one in the destination..
        /// </summary>
        public static string WFDeConflictError {
            get {
                return ResourceManager.GetString("WFDeConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition name conflict with destination, and template is different.It will be skipped..
        /// </summary>
        public static string WFDeNameOrTemplateConflictError {
            get {
                return ResourceManager.GetString("WFDeNameOrTemplateConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring workflow definition..
        /// </summary>
        public static string WFDeUnexpectError {
            get {
                return ResourceManager.GetString("WFDeUnexpectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing to file .Message:{0}..
        /// </summary>
        public static string WriteToFileError {
            get {
                return ResourceManager.GetString("WriteToFileError", resourceCulture);
            }
        }
    }
}
