<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <AssemblyName>AgentCommonClientRequestCommon</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\..\bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\..\..\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\..\DocaveReference\DocAveStandard.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\..\DocaveReference\DocAveStandard.snk">
      <Link>DocAveStandard.snk</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\GlobalCommon\GCommonUtility\DocAve.GCommonUtility.csproj" />
    <ProjectReference Include="..\..\..\Microsoft365\Authentication\Microsoft365.Authentication.csproj" />
    <ProjectReference Include="..\..\..\Microsoft365\Common\Microsoft365.Common.csproj" />
    <ProjectReference Include="..\..\..\Microsoft365\Contract\Microsoft365.Contract.csproj" />
    <ProjectReference Include="..\..\..\Microsoft365\SharePoint\Microsoft365.SharePoint.csproj" />
    <ProjectReference Include="..\..\..\Wrapper\Wrapper.Common\Wrapper.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AOS.SDK" Version="1.2.78" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Data.Services.Client" Version="5.8.5" />
    <PackageReference Include="Microsoft.SharePointOnline.CSOM" Version="16.1.26712.12000" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="10.0.2" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Linq.Queryable" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AveHttpWebRequestUtility.cs" />
  </ItemGroup>
</Project>