/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */


using System;
using System.Collections;
using AvePoint.GCommon;
using AvePoint.Wrapper.Common;
using Microsoft.SharePoint.Deployment;

namespace AvePoint.ObjectModel.Server19
{
    class AveExportSettings : AveDeploymentSettings, IAveExportSettings
    {
        private SPExportSettings mExportSettings { get { return base.DeploymentSettings as SPExportSettings; } }
        private AveExportObjectCollection mExportObjects;
        private static AveLogger mLog = AveLogger.GetInstance(typeof(AveExportSettings));

        public AveExportSettings()
        { }

        public AveExportSettings(Uri sourceSiteUrl, string dataFileLocation, string baseDataFileName)
            : base(new SPExportSettings(sourceSiteUrl, dataFileLocation, baseDataFileName))
        {
            this.IncludeVersions = AveIncludeVersions.LastMajor;
            mLog.Debug("Site: {0},file path: {1},file name: {2}", sourceSiteUrl, dataFileLocation, baseDataFileName);
        }

        internal SPExportSettings ExportSettings
        {
            get
            {
                return this.mExportSettings;
            }
        }

        public void Validate()
        {
            mExportSettings.Validate();
        }

        #region IAveExportSettings Member

        public AveIncludeVersions IncludeVersions
        {
            get
            {
                return (AveIncludeVersions)(mExportSettings.IncludeVersions);
            }
            set
            {
                mExportSettings.IncludeVersions = (SPIncludeVersions)value;
            }
        }

        public AveExportMethodType ExportMethod
        {
            get
            {
                return (AveExportMethodType)(mExportSettings.ExportMethod);
            }
            set
            {
                mExportSettings.ExportMethod = (SPExportMethodType)value;
            }
        }

        public bool ExcludeDependencies
        {
            get
            {
                return mExportSettings.ExcludeDependencies;
            }
            set
            {
                mExportSettings.ExcludeDependencies = value;
            }
        }

        public bool OverwriteExistingDataFile
        {
            get
            {
                return mExportSettings.OverwriteExistingDataFile;
            }
            set
            {
                mExportSettings.OverwriteExistingDataFile = value;
            }
        }

        public int FileMaxSize
        {
            get
            {
                return mExportSettings.FileMaxSize;
            }
            set
            {
                mExportSettings.FileMaxSize = value;
            }
        }

        public IAveExportObjectCollection ExportObjects
        {
            get
            {
                if (mExportObjects == null)
                {
                    mExportObjects = new AveExportObjectCollection(mExportSettings.ExportObjects);
                }
                return mExportObjects;
            }
        }

        public ArrayList DataFiles
        {
            get
            {
                return mExportSettings.DataFiles;
            }
        }

        #endregion

        public bool LogExportObjectsTable
        {
            get;
            set;
        }

        public string ExportChangeToken
        {
            get;
            set;
        }

        public bool ExportPublicSchema
        {
            get;
            set;
        }

        public bool AutoGenerateDataFileName
        {
            get
            {
                return mExportSettings.AutoGenerateDataFileName;
            }
            set
            {
                mExportSettings.AutoGenerateDataFileName = value;
            }
        }
    }
}
