/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
using AvePoint.RA.CommonUtil;
using AvePoint.RA.Contract.RMWeb.Explorer;
using AvePoint.RA.DB.Explorer.Model;
using LiteDB;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using AvePoint.RA.DB.Explorer.Dao.CosmosImp.Builder.Extension;
using System.Collections;

namespace AvePoint.RA.DB.Lite 
{
    public class ExplorerOfflineSearchWrapper : IDisposable
    {
        protected AvePoint.RA.Contract.Services.IRALogger logger = RALogger.GetInstance(typeof(ExplorerOfflineSearchWrapper));
        private readonly string _defaultCollectionName = "rec";
        private string _filename;
        private LiteDatabase _db;
        /// <summary>
        /// Fortify scan issue,RECO-20916
        /// path paramether should be generated by SecurityUtils.SafeCombinePath path method! 
        /// </summary>
        /// <param name="dbFilePath"></param>
        /// <exception cref="ArgumentNullException"></exception>
        public ExplorerOfflineSearchWrapper(string dbFilePath)
        {
            
            if (string.IsNullOrEmpty(dbFilePath))
            {
                throw new ArgumentNullException("filename");
            }
            _filename = dbFilePath;
            CheckExists(_filename);
            _db = new LiteDatabase(_filename);
        }

        public void Insert(List<Record> datas)
        { 
            _db.GetCollection<Record>(_defaultCollectionName).InsertBulk(datas);

            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a=>a.LeafName);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.RecordsId);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.TimeCreated);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.TimeModified);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.CreatedBy);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.ModifiedBy);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.DeclaredBy);
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(a => a.HoldStatus);
        }

        public void EnsureIndex<TKey>(Expression<Func<Record, TKey>> keyselectror)
        {
            _db.GetCollection<Record>(_defaultCollectionName).EnsureIndex(_defaultCollectionName, keyselectror, false);
        }

        public List<Record> QueryAll(int pageIndex, int perPage, string orderColumn, bool isAsc = true)
        {
            Query q = LiteDB.Query.All();
            q.Order = isAsc ? 1 : -1;
            q.OrderBy = orderColumn;
            q.Limit = perPage;
            q.Offset = perPage * pageIndex;
            return _db.GetCollection<Record>(_defaultCollectionName).Find(q).ToList();
        }

        public List<Record> QueryAllByPage(int pageIndex, int perPage, ExplorerQueryOrderColumn orderColumn)
        {
            if (!orderColumn.Column.IsCustomColumn())
            {
                Query q = LiteDB.Query.All();
                q.Order = orderColumn.OrderAsc ? 1 : -1;
                q.OrderBy = orderColumn.Column.Name;
                q.Limit = perPage;
                q.Offset = perPage * pageIndex;
                return _db.GetCollection<Record>(_defaultCollectionName).Find(q).ToList();
            }
            else
            {
                ExplorerQueryColumn column = orderColumn.Column;
                Query q = LiteDB.Query.All();
                //return _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderBy(a => { return a!= null && a.CustomColumnDic != null&& a.CustomColumnDic.ContainsKey(column.Id) && a.CustomColumnDic[column.Id] != null ? a.CustomColumnDic[column.Id].Date : new DateTime(0); }).Skip(perPage * pageIndex).Take(perPage).ToList();

                switch (orderColumn.Column.Type)
                {
                    case Contract.TemplateManagement.ColumnType.DateTime:
                        return orderColumn.OrderAsc ? _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderBy(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) && a.CustomColumnDic[column.Id] != null ? a.CustomColumnDic[column.Id].Date : new DateTime(0); }).Skip(perPage * pageIndex).Take(perPage).ToList()
                             : _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderByDescending(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Date : new DateTime(0); }).Skip(perPage * pageIndex).Take(perPage).ToList();

                    case Contract.TemplateManagement.ColumnType.SingleChoice:
                        return orderColumn.OrderAsc ? _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderBy(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Name : ""; }).Skip(perPage * pageIndex).Take(perPage).ToList()
                             : _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderByDescending(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Name : ""; }).Skip(perPage * pageIndex).Take(perPage).ToList();

                    case Contract.TemplateManagement.ColumnType.Number:
                        return orderColumn.OrderAsc ? _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderBy(a => { return a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Number : 0.0; }).Skip(perPage * pageIndex).Take(perPage).ToList()
                             : _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderByDescending(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Number : 0.0; }).Skip(perPage * pageIndex).Take(perPage).ToList();

                    case Contract.TemplateManagement.ColumnType.SingleText:
                    case Contract.TemplateManagement.ColumnType.MultipleText:
                        return orderColumn.OrderAsc ? _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderBy(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Value : ""; }).Skip(perPage * pageIndex).Take(perPage).ToList()
                             : _db.GetCollection<Record>(_defaultCollectionName).Find(q).OrderByDescending(a => { return a.CustomColumnDic != null && a.CustomColumnDic.ContainsKey(column.Id) ? a.CustomColumnDic[column.Id].Value : ""; }).Skip(perPage * pageIndex).Take(perPage).ToList();
                    default:
                        return _db.GetCollection<Record>(_defaultCollectionName).Find(q).Skip(perPage * pageIndex).Take(perPage).ToList();
                }
            }
        } 
        public int QueryCount()
        {
            return _db.GetCollection<Record>(_defaultCollectionName).Count();
        }
        private void CheckExists(string filename)
        {
            try
            {
                FileInfo fs = new FileInfo(filename);
                if (!fs.Directory.Exists)
                {
                    fs.Directory.Create();
                }
            }
            catch (Exception e)
            {
                logger.Warn(e.Message, e);
            }
        }

        public void Dispose()
        {
            try
            {
                if(_db != null)
                {
                    _db.Dispose();
                }
            }
            catch(Exception e)
            {
                logger.Warn($"Dispose db failed, error : {e}");
            }
        }
    }
}
