/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merged18NResources.MediaService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MediaServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merged18NResources.MediaService.MediaServiceResource", typeof(MediaServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Windows Service is starting....
        /// </summary>
        public static string MediaServiceOnStartBeginMediaService {
            get {
                return ResourceManager.GetString("MediaServiceOnStartBeginMediaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while starting Media Windows Service. Please reference the logs for more details: {0}..
        /// </summary>
        public static string MediaServiceOnStartBeginMediaServiceError {
            get {
                return ResourceManager.GetString("MediaServiceOnStartBeginMediaServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media Windows Service successfully..
        /// </summary>
        public static string MediaServiceOnStartBeginMediaServiceSucceed {
            get {
                return ResourceManager.GetString("MediaServiceOnStartBeginMediaServiceSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Windows Service is stopping....
        /// </summary>
        public static string MediaServiceOnStopEndMediaService {
            get {
                return ResourceManager.GetString("MediaServiceOnStopEndMediaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while shutting down Media Windows Service. Please reference the logs for more details: {0}..
        /// </summary>
        public static string MediaServiceOnStopEndMediaServiceError {
            get {
                return ResourceManager.GetString("MediaServiceOnStopEndMediaServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Media Windows Service successfully..
        /// </summary>
        public static string MediaServiceOnStopEndMediaServiceSucceed {
            get {
                return ResourceManager.GetString("MediaServiceOnStopEndMediaServiceSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start initiating Media Service....
        /// </summary>
        public static string MediaServiceRestartMediaServiceBeginStartMediaService {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceBeginStartMediaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start stopping Media Service....
        /// </summary>
        public static string MediaServiceRestartMediaServiceBeginStopMediaService {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceBeginStopMediaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting the running Media Service to stop. Then refresh the status of Service Control Media..
        /// </summary>
        public static string MediaServiceRestartMediaServiceRefreshMediaServiceStartStatus {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceRefreshMediaServiceStartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Service has stopped. The status of Service Control Manager is refreshing....
        /// </summary>
        public static string MediaServiceRestartMediaServiceRefreshMediaServiceStopStatus {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceRefreshMediaServiceStopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restarting the Media Service. Please reference the logs for more details: {0}..
        /// </summary>
        public static string MediaServiceRestartMediaServiceRestartMediaError {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceRestartMediaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarted Media Service successfully..
        /// </summary>
        public static string MediaServiceRestartMediaServiceRestartMediaSucceed {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceRestartMediaSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Servicer is starting. Please wait a minute to complete..
        /// </summary>
        public static string MediaServiceRestartMediaServiceWaitForMediaServiceStart {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceWaitForMediaServiceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Servicer is stopping. Please wait a minute to complete..
        /// </summary>
        public static string MediaServiceRestartMediaServiceWaitForMediaServiceStop {
            get {
                return ResourceManager.GetString("MediaServiceRestartMediaServiceWaitForMediaServiceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start stopping Media Service....
        /// </summary>
        public static string MediaServiceStopMediaServiceBeginStopMedia {
            get {
                return ResourceManager.GetString("MediaServiceStopMediaServiceBeginStopMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Service has stopped, Please refresh the status of Service Control Manager..
        /// </summary>
        public static string MediaServiceStopMediaServiceRefreshMediaServiceStopStatus {
            get {
                return ResourceManager.GetString("MediaServiceStopMediaServiceRefreshMediaServiceStopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while stopping Media Service. Please reference the logs for more details: {0}..
        /// </summary>
        public static string MediaServiceStopMediaServiceStopError {
            get {
                return ResourceManager.GetString("MediaServiceStopMediaServiceStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped Media Service successfully..
        /// </summary>
        public static string MediaServiceStopMediaServiceStopSucceed {
            get {
                return ResourceManager.GetString("MediaServiceStopMediaServiceStopSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Service is stopping. Please wait a minute to complete..
        /// </summary>
        public static string MediaServiceStopMediaServiceWaitForMediaServiceStop {
            get {
                return ResourceManager.GetString("MediaServiceStopMediaServiceWaitForMediaServiceStop", resourceCulture);
            }
        }
    }
}
