<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Castle\ServiceCastle.config" />
    <None Remove="SDS-SEE.exml" />
    <None Remove="TimerLog4net.config" />
    <None Remove="AgentLog4net.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TestData\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>TestData\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Castle\ServiceCastle.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="TimerLog4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
    <Content Include="AgentLog4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SDS-SEE.exml">
      <LogicalName>SDS-SEE.exml</LogicalName>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BenchMark\BenchmarkProgram.cs" />
    <Compile Remove="BenchMark\bin\**" />
    <Compile Remove="BenchMark\obj\**" />
    <EmbeddedResource Remove="BenchMark\bin\**" />
    <EmbeddedResource Remove="BenchMark\obj\**" />
    <None Remove="BenchMark\bin\**" />
    <None Remove="BenchMark\obj\**" />
    <Content Remove="BenchMark\bin\**" />
    <Content Remove="BenchMark\obj\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.3" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.57.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\MediaStorage\Media.StorageApi\Media.StorageApi.csproj" />
    <ProjectReference Include="..\RACommonUtility\RACommonUtility.csproj" />
    <ProjectReference Include="..\RACommon\RACommon.csproj" />
    <ProjectReference Include="..\RAContract\RAContract.csproj" />
    <ProjectReference Include="..\RADB\RADB.csproj" />
    <ProjectReference Include="..\RAExtractor\RAExtractor.csproj" />
    <ProjectReference Include="..\RAMultiGeo\RAMultiGeo.csproj" />
    <ProjectReference Include="..\RASalesforce\RASalesforce.csproj" />
    <ProjectReference Include="..\RAService\RAService.csproj" />
    <ProjectReference Include="..\RMExternalSynchronize\RMSynchronize.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="storage.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
