export const FilterOptions = {
    None: 0,
    ActionTime: 2,
    Source: 3,
    ApprovalStatus: 4,
    ModifiedBy: 5,
    CreatedBy: 6,
    RuleName: 7,
    RuleDisposalClass: 8,
    ApprovedBy: 11,
    LeafName: 12,
    IsRelatedRecords: 13,
    Workspace: 16,
    MLReviewer: 17,
    PredictTime: 18,
    MLApprovalStatus: 19,
    MLEscalatedFrom: 20,
    MLWorkspace: 21,
    StartTime: 22,
    EndTime: 23,
    DateModified: 26,
    DateCreated: 27,
    Classification: 28,
    ModifiedTime: 29,
    LastSyncTime: 30,
    User: 31,
    Action: 32,
    Time: 33,
};

export const FilterI18Ns = new Map([
    [FilterOptions.ActionTime, RMResx.RM_JS_MA_Grid_ActionTime.replace(":", "")],
    [FilterOptions.Source, RMResx.RM_JS_BCM_Explorer_Datagrid_Source],
    [FilterOptions.ApprovalStatus, RMResx.RM_JS_MA_Grid_ApprovalStatus],
    [FilterOptions.ModifiedBy, RMResx.RM_JS_MA_Grid_ModifiedBy],
    [FilterOptions.CreatedBy, RMResx.RM_JS_MA_Grid_CreatedBy],
    [FilterOptions.RuleName, RMResx.RM_JS_MA_Grid_Rule],
    [FilterOptions.RuleDisposalClass, RMResx.RM_JS_Rule_DisposalClass_Title],
    [FilterOptions.ApprovedBy, RMResx.RM_JS_MA_Grid_ApprovedBy],
    [FilterOptions.MLReviewer, RMResx.RM_JS_MA_Grid_RecordOwner],
    [FilterOptions.PredictTime, RMResx.RM_JS_MA_Grid_CreatedTime.replace(":", "")],
    [FilterOptions.MLEscalatedFrom, RMResx.RM_MA_Grid_EscalateOrReassignFrom],
    [FilterOptions.MLWorkspace, RMResx.RM_JS_MA_Location_Filter],
    [FilterOptions.StartTime, RMResx.RM_Common_StartDate],
    [FilterOptions.EndTime, RMResx.RM_JS_JM_EndTime],
    [FilterOptions.DateModified, RMResx.RM_JS_MA_Grid_DateModified],
    [FilterOptions.DateCreated, RMResx.RM_JS_MA_Grid_DateCreated],
    [FilterOptions.Classification, RMResx.RM_ML_TS_Column_Classification],
    [FilterOptions.ModifiedTime, RMResx.RM_FS_Register_LastModifiedTime],
    [FilterOptions.LastSyncTime, RMResx.RM_FS_Register_LastSyncTime],
    [FilterOptions.Time, RMResx.RM_JS_RC_Audit_ViewBy_Option_Time],
]);