/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Media.Storage.Resources.CleversafeI18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CleversafeI18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleversafeI18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Media.Storage.Resources.CleversafeI18N.CleversafeI18N", typeof(CleversafeI18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access key ID.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Access_Key_ID {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Access_Key_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Access_Key_ID_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Access_Key_ID_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate two Accesser IPs with a semicolon..
        /// </summary>
        internal static string MediaStorage_Cleversafe_AccesserIPs_Must_be_separated_with_semicolon {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_AccesserIPs_Must_be_separated_with_semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can contain letters, numbers, periods (.), underscores (_), and dashes (-)..
        /// </summary>
        internal static string MediaStorage_Cleversafe_Can_contain_letters_numbers_periods_underscores_and_dashes {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Can_contain_letters_numbers_periods_underscores_and_dashe" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleversafe.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Cleversafe {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Cleversafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a storage type for the physical device you are about to create..
        /// </summary>
        internal static string MediaStorage_Cleversafe_Configure_your_bucket_name_Access_Key_ID_and_Secret_Access_Key {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Configure_your_bucket_name_Access_Key_ID_and_Secret_Acces" +
                        "s_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 3 and 255 characters long..
        /// </summary>
        internal static string MediaStorage_Cleversafe_Must_be_between_3_and_255_characters_long {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Must_be_between_3_and_255_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be formatted as an IP address (e.g., 192.168.5.4).
        /// </summary>
        internal static string MediaStorage_Cleversafe_Must_not_be_formatted_as_an_IP_address {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Must_not_be_formatted_as_an_IP_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault names must start with a letter or number..
        /// </summary>
        internal static string MediaStorage_Cleversafe_Must_start_with_a_number_or_letter {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Must_start_with_a_number_or_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret access key.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Secret_Access_Key {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Secret_Access_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accesser IPs.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Storage_Accesser_IPs {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Storage_Accesser_IPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault name.
        /// </summary>
        internal static string MediaStorage_Cleversafe_Vault_Name {
            get {
                return ResourceManager.GetString("MediaStorage_Cleversafe_Vault_Name", resourceCulture);
            }
        }
    }
}
