<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AvePoint.GCommon.Extension</RootNamespace>
    <AssemblyName>CommonExtension</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\..\bin\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\..\bin\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\..\..\DocaveReference\DocAveStandard.snk</AssemblyOriginatorKeyFile>
    <BaseOutputPath>bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GCommonContract\DocAve.GCommonContract.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\DocaveReference\DocAveStandard.snk">
      <Link>DocAveStandard.snk</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.CodeDom" Version="10.0.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>
</Project>