export default {
    RecordName: 1,
    RecordsId: 2,
    Type: 3,
    FileExtension: 4,
    ApprovalStatus: 5,
    Rule: 6,
    DisposalClass: 7,
    ReassignedFrom: 8,
    RecordReviewer: 9,
    ApprovedBy: 10,
    QuickReason: 11,
    ApprovalCommnent : 12,
    ExtendTime: 13,
    Comment: 14,
    ModifiedBy: 15,
    CreatedBy: 16,
    CollectionTime: 17,
    RelatedRecords: 18,
    DisposalAction: 19,
    ActionTime: 20,
    FullPath : 21,
    ReassignComment: 22,
    FolderPath: 23,
    LastReasonForRejection: 24,
    LastApproveRejectComment: 25,
    LastReviewedBy: 26,
    LastReviewTime: 27,
    ModifiedTime : 28,
    TermName : 29,
    DisposalDueDate : 30,
};