import {getActionDueDateI18n} from "../../../../Utilities/CommonUtil";

export default {
    RecordName: RMResx.RM_JS_MA_Grid_Title,
    RecordsId: RMResx.RM_PRM_PRE_Column_ID,
    Type: RMResx.RM_JS_BCM_Explorer_Datagrid_FileType,
    FileExtension: "File Extension",
    ApprovalStatus: RMResx.RM_JS_MA_Grid_ApprovalStatus,
    Rule: RMResx.RM_JS_MA_Grid_Rule,
    DisposalClass: RMResx.RM_JS_Rule_DisposalClass_Title,
    ReassignedFrom: RMResx.RM_MA_Grid_EscalateOrReassignFrom,
    RecordReviewer: RMResx.RM_JS_MA_Grid_RecordOwner,
    ApprovedBy: RMResx.RM_JS_MA_Grid_ApprovedBy,
    ApprovalComment : RMResx.RM_MA_ApprovalComment,
    QuickReason : RMResx.RM_MA_ApprovalCommentTerm,
    ExtendTime: RMResx.RM_JS_MA_Grid_ExtendTime,
    Comment: RMResx.RM_JS_MA_Grid_Comment,
    ModifiedBy: RMResx.RM_JS_MA_Grid_ModifiedBy,
    CreatedBy: RMResx.RM_JS_MA_Grid_CreatedBy,
    CollectionTime: RMResx.RM_JS_MA_Grid_CreatedTime,
    RelatedRecords: RMResx.RM_JS_MA_Grid_RelatedRecords,
    DisposalAction: RMResx.RM_JS_MA_Grid_RelatedRecordsAction,
    ActionTime: RMResx.RM_JS_MA_Grid_ActionTime,
    FullPath : RMResx.RM_JS_MA_Grid_FullPath,
    ReassignComment: RMResx.RM_JS_MA_Grid_Reassigned_Comment,
    FolderPath :RMResx.RM_JS_MA_Grid_FolderPath,
    LastReasonForRejection :RMResx.RM_MA_LastReasonforRejection,
    LastApprovalComment:RMResx.RM_MA_JS_LastCommenttExtendDisposalList,
    LastApproveRejectComment: RMResx.RM_MA_JS_LastApproveRejectComment,
    LastReviewedBy: RMResx.RM_MA_JS_LastReviewedBy,
    LastReviewTime: RMResx.RM_MA_JS_LastReviewTime,
    ModifiedTime : RMResx.RM_JS_MA_Grid_ModifiedTime,
    DisposalDueDate : getActionDueDateI18n(),
    DisposalDueDateDesc: RMResx.RM_JS_MA_Grid_DisposalDueDate_Desc,
    TermName : RMResx.RM_JS_MA_Grid_TermName,
};