<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\GlobalCommon\GCommonUtility\DocAve.GCommonUtility.csproj" />
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
    <ProjectReference Include="..\RACommon\RACommon.csproj" />
    <ProjectReference Include="..\RAGoogle\RAGoogle.csproj" />
    <ProjectReference Include="..\RAI.Core\RAI.Core.csproj" />
  </ItemGroup>

</Project>
