/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Media.Storage.Resources.TSMI18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TSMI18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TSMI18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Media.Storage.Resources.TSMI18N.TSMI18N", typeof(TSMI18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string MediaStorage_TSM_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asnodename:.
        /// </summary>
        public static string MediaStorage_TSM_Asnodename {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Asnodename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        public static string MediaStorage_TSM_Authentication_failed {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the remote server..
        /// </summary>
        public static string MediaStorage_TSM_Cannot_connect_to_the_remote_server {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Cannot_connect_to_the_remote_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the entered management class: {0}..
        /// </summary>
        public static string MediaStorage_TSM_Cannot_find_the_entered_management_class {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Cannot_find_the_entered_management_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client node proxy.
        /// </summary>
        public static string MediaStorage_TSM_Client_Node_Proxy {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Client_Node_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string MediaStorage_TSM_Communication {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened the data failed, path: {0}..
        /// </summary>
        public static string MediaStorage_TSM_DataNotFound {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the data failed, path: {0}..
        /// </summary>
        public static string MediaStorage_TSM_DataReadFailed {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_DataReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote the data failed, path: {0}..
        /// </summary>
        public static string MediaStorage_TSM_DataWriteFailed {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_DataWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to the TSM physical device failed, name: {0}..
        /// </summary>
        public static string MediaStorage_TSM_DeviceCanNotConnect {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_DeviceCanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        public static string MediaStorage_TSM_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        public static string MediaStorage_TSM_IP_V6_Node_Name_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_IP_V6_Node_Name_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management class.
        /// </summary>
        public static string MediaStorage_TSM_Management_Class {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Management_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node name.
        /// </summary>
        public static string MediaStorage_TSM_Node_Name {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Node_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        public static string MediaStorage_TSM_Node_Name_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Node_Name_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node password.
        /// </summary>
        public static string MediaStorage_TSM_Node_Password {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Node_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server address.
        /// </summary>
        public static string MediaStorage_TSM_Server_Address {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Server_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port.
        /// </summary>
        public static string MediaStorage_TSM_Server_Port {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP.
        /// </summary>
        public static string MediaStorage_TSM_TCP_IP {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_TCP_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP V6.
        /// </summary>
        public static string MediaStorage_TSM_TCP_IP_V6 {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_TCP_IP_V6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed, please check the information you entered..
        /// </summary>
        public static string MediaStorage_TSM_Test_failed {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_Test_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered node name is incorrect..
        /// </summary>
        public static string MediaStorage_TSM_The_entered_node_name_is_incorrect {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_The_entered_node_name_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSM.
        /// </summary>
        public static string MediaStorage_TSM_TSM {
            get {
                return ResourceManager.GetString("MediaStorage_TSM_TSM", resourceCulture);
            }
        }
    }
}
