<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
  <ItemGroup>
	<PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
	<PackageReference Include="Box.V2.Core" Version="5.8.0" />
	<PackageReference Include="log4net" Version="3.3.1" />
	  <ProjectReference Include="..\Common\GlobalCommon\GCommonContract\DocAve.GCommonContract.csproj" />
	  <ProjectReference Include="..\Common\VCService30\CommonUtility30\DocAve.CommonUtility30.csproj" />
	  <ProjectReference Include="..\RAArchiverCommon\RAArchiverCommon.csproj" />
	  <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
	  <ProjectReference Include="..\RACommonUtility\RACommonUtility.csproj" />
	  <ProjectReference Include="..\RACommon\RACommon.csproj" />
	  <ProjectReference Include="..\RAContract.Global\RAContract.Global.csproj" />
	  <ProjectReference Include="..\RAContract\RAContract.csproj" />
	  <ProjectReference Include="..\RADataSynchronize\RADataSynchronize.csproj" />
	  <ProjectReference Include="..\RADB\RADB.csproj" />
	  <ProjectReference Include="..\RAI18N\RAI18N.csproj" />
  </ItemGroup>

</Project>
