<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>DocAveStandard.snk</AssemblyOriginatorKeyFile>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <Authors>AvePoint, Inc.</Authors>
    <Company>AvePoint, Inc.</Company>
    <Product>Opus</Product>
    <Copyright>Copyright © 2021 AvePoint® Inc. All Rights Reserved.</Copyright>
    <PackageId>Hybrid.ClientCore</PackageId>
    <Version>10.0.0.0</Version>
    <AssemblyName>CloudAgentApiClientCore</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath></OutputPath>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel" Version="8.0.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="8.15.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.2" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    <PackageReference Include="System.Reflection.Emit.ILGeneration" Version="4.7.0" />
    <PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\HybirdFramework\CommonModel\HybridCommonModel.csproj" />
    <ProjectReference Include="..\..\RAContract.Global\RAContract.Global.csproj" />
  </ItemGroup>
</Project>
