/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */


#define CODE_ANALYSIS
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("CommonUtility.dll")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("AvePoint, Inc.")]
[assembly: AssemblyProduct("DocAve 6")]
[assembly: AssemblyCopyright("Copyright © 2021 AvePoint® Inc. All Rights Reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("2a43a9f8-2bd0-4dcc-92e9-ed1b89637163")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("6.7.0.1139")]
[assembly: AssemblyInformationalVersion("6.7.0.1139")]

[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "type", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper", MessageId = "DatabaseEncryptionHelper")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#SaveDatabaseEncryptionInfoToDB(System.Data.SqlClient.SqlConnection,System.String,System.String)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.SaveDatabaseEncryptionInfoToDB")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#SaveDatabaseEncryptionInfoToDB(System.Data.SqlClient.SqlConnection,System.Byte[])", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.SaveDatabaseEncryptionInfoToDB")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#DecryptDatabaseEncryptionKeyByMasterKey(System.Byte[],System.Byte[],AvePoint.GCommon.Utility.Cryptography.EncryptionAlgorithm)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.DecryptDatabaseEncryptionKeyByMasterKey")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#EncryptDatabaseEncryptionKeyByMasterKey(System.Byte[],System.Byte[],AvePoint.GCommon.Utility.Cryptography.EncryptionAlgorithm)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.EncryptDatabaseEncryptionKeyByMasterKey")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#GetDatabaseEncryptionKeyFromDB(System.Data.SqlClient.SqlConnection)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.GetDatabaseEncryptionKeyFromDB")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#SaveDatabaseEncryptionKeyToDB(System.Data.SqlClient.SqlConnection,System.String)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.SaveDatabaseEncryptionKeyToDB")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#GetDatabaseEncryptionInfoFromDB(System.Data.SqlClient.SqlConnection,System.String)", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.GetDatabaseEncryptionInfoFromDB")]
[module: SuppressMessage("FxCopCustomRules", "C100001:DoNotNameSensitiveWords", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.#GenerateDatabaseEncryptionKey()", MessageId = "AvePoint.GCommon.Utility.Cryptography.DatabaseEncryptionHelper.GenerateDatabaseEncryptionKey")]
[module: SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "AvePoint.GCommon.Utility.FilteringBox.EncryptionFilteringBox")]
[module: SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "AvePoint.GCommon.Utility.FilteringBox.MixedFilteringBox")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#lpDisplayName")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#lpBinaryPathName")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#dwTagId")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#lpDependencies")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#lpServiceStartName")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#dwStartType")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#lpLoadOrderGroup")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#dwServiceType")]
[module: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "AvePoint.GCommon.Utility.QUERY_SERVICE_CONFIG.#dwErrorControl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.AveLogger.#.cctor()", MessageId = "Sdids")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.ProfilerChecker.#AddProfilingEnvironmentVariables(System.Collections.Generic.Dictionary`2<System.String,System.String>)", MessageId = "Cor")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.LicenseFilter.#.cctor()", MessageId = "bla")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "streamingmedia")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pyc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ksh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pkg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "zsh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "bsh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "uil")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpe")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tgz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "Mjuice")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "i-deas")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-cmu-raster")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vrml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rn-realflash")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-jps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-dwg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-ustar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "csh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vosaic")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "clariscad")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sdp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-gtar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-wintalk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mjpg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-elc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rmm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "skm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "prt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "commonground")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-dwf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vrt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jav")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rfc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qtif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "avs-video")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xiff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "crt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vql")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rn-realpix")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "smil")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "shtml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-twinvq")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-sgi-movie")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mme")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "deepv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vos")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aiff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-authorware-bin")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wrl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hqx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pvu")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aos")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rgb")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xpm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "crl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vew")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "frl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vocaltec-media-file")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ppm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pict")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "snd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xbm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-uil")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rmp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-gzip")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pbm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-deepv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-navidoc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fli")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-ima")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pagemaker")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-omcdatamaker")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vcs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "omcr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sla")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ppa")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dxr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-mif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wmlsc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pkix-crl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpa")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pcl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wsc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tcl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-cooltalk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "nsc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pkcs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-navimap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "webviewhtml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-cdlink")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "boz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-csh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-dvi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tex")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-amt-demorun")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qcp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xpix")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "bcpio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xwd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wbmp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-livescreen")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vcd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-portable-pixmap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pgm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mcd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sgm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "drw")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-rgb")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "netmc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-setext")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mjf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "der")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pov")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "quicktime")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-bzip")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-tex")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tsv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-qtc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "idc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cpt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xll")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dwg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-bytecode")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "bz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "voxware")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "spl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vst")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "uu")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vqf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "certstore")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "acgi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xld")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mswrite")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "skp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "shar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wpd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-qpro")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-liveaudio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "lma")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cpio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "asf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "roff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cco")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "groupwise")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jfif-tbnl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-troff-man")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "omc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wmlc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-xbitmap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-vrml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rtx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-internett-signup")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-mplayer")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "texinfo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "htx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pwz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ltx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-isvideo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpga")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "etx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wmls")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cxx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-portable-graymap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mspowerpoint")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ssi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tsi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sbk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tbk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ai")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cmu-raster")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hdf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ppz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wsrc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cdf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dcr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fdf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "phyton")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rn-realmedia")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-vrt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-omc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-visio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "flo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "abc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gss")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xsr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ls-xpix")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "igs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "afl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-authorware-map")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "applicaiton")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pascal")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-portable-anymap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hpg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pfunk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-jg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-esrehber")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-xwd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xara")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-newton-compatible-pkg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ra")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vmf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-netcdf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "spr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tsplayer")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aip")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aifc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "py")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sst")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fmf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rast")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "iefs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-authorware-seg")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "lst")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pov")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "oda")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jutvision")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rexx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rnx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sdml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wordperfect")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlb")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qcelp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "florian")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-audiosoft-intra")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hlb")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rmi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "smi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vocaltec-media-desc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vsd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "scm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "svf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fmi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "kar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "toolbook")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ncm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-troff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "lsx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-gsp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jfif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ima")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "evy")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "seccat")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qtc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pcx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-cpt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mbedlet")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "avs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-bcpio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ms-pki")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "skt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "Lscript")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "omcd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mcad")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vqe")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "acad")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ccad")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vsw")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aab")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mcp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-dv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "imap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dvi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "unis")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gtar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wtk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "flexstor")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-navi-animation")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-seelogo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlk")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "plx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-psid")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jpe")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pn-realaudio-plugin")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-twinvq-plugin")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "niff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "flx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pkix-cert")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xgz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fpx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-mpequrl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "nokia")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "spc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-gsm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-texinfo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vmd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gzip")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hlp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "binhex")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-gss")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vdo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aam")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "cpp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "viv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dxf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "uue")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mrc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-httpd-imap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sgml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "crc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-koan")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "htmls")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-la-asf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "nspaudio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dmf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "elisp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pn-realaudio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xdr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qti")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "i-vrml")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "sdr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "qif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ief")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "nvd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-bsh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "htc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "lsp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "nif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wq")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "tcsh")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "bm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "unv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "fif")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wmlscriptc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xgl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-amt-showrun")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hta")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "texi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hgl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xmz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ustar")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vasa")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pkcs")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-omcregerator")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pict")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rn-realplayer")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-troff-ms")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gsd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "isu")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "eps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-tbook")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "skd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "paleovu")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "futuresplash")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-lotusscreencam")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-hdf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-ms-asf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xla")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ssm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "htt")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dv")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-cpio")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "animaflex")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gsm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-troff-me")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "richtext")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-quicktime")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "jcm")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "naplps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-xpixmap")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wmlscript")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vox")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mpc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "elc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "stl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "rn-realvideo")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "iges")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aas")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "aps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "asx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pcx")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wrz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pascal")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mzz")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "uni")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "moov")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "wri")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "vda")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ani")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-pcl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlw")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "svr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mcf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "mbd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "ivr")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "pko")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "gsp")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "dwf")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "hpgl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "xlc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "x-niff")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.MIMETypeHelper.#InitMimeTypes()", MessageId = "scriplet")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.FipsModeUtil.#GetCryptoModeFromRegistry()", MessageId = "Lsa")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.FipsModeUtil.#GetCryptoModeFromConfig()", MessageId = "Fips")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.ProductInfoUtil.#WriteProductInfo(System.String,System.String,System.String)", MessageId = "Signdata")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.ProductInfoUtil.#WriteProductInfoForUpdate(System.String)", MessageId = "Signdata")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.ProductInfoUtil.#WriteProductInfoForUpdate(System.String)", MessageId = "avepoint")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Cryptography.ProductInfoUtil.#GetProductInfomation(System.Boolean)", MessageId = "Signdata")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.TraceSourceGarbageCollector.#.cctor()", MessageId = "tracesources")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#ToString()", MessageId = "ddd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#ToString()", MessageId = "yyyy")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#ToString()", MessageId = "dd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#CompareTo(System.Object)", MessageId = "Rfc")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#ToSpecificString()", MessageId = "yyyy")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Rfc822DateTime.#ToSpecificString()", MessageId = "dd")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Security.AccessControl.SecurityDescriptor.#SecurityDescriptorFromString(System.String)", MessageId = "dacl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Security.AccessControl.SecurityDescriptor.#SecurityDescriptorFromString(System.String)", MessageId = "sacl")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Configurations.DocAveConfigurationSectionHandler.#get_Instance()", MessageId = "docave")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.VSS.iSCSIUtility.#get_iSCSISession()", MessageId = "Iscsi")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.AveLoggerLog4netImp.#SeparateLogByTenant(System.String,System.String)", MessageId = "Separative")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.GConstants+I18NConstants.#.cctor()", MessageId = "Frontend")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.OSInformation.#EnsureCPUAndNetworkInfo()", MessageId = "Cpu")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.HashCodeHelper.#IsUseFIPS140CompliantCryptographicAlgorithms()", MessageId = "Lsa")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.AveLogger.#.cctor()", MessageId = "Deps")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.AveLogger.#.cctor()", MessageId = "Immed")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.LDAPLookup.#CheckAccount(System.DirectoryServices.DirectorySearcher,System.String)", MessageId = "samaccountname")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.GConstants+I18NConstants.#.cctor()", MessageId = "Gui")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Synchronization.ReaderWriterLockSlim.#ExitReadLock()", MessageId = "Mis")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Synchronization.ReaderWriterLockSlim.#ExitUpgradeableReadLock()", MessageId = "Mis")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.Utility.Synchronization.ReaderWriterLockSlim.#ExitWriteLock()", MessageId = "Mis")]
[module: SuppressMessage("FxCopCustomRules", "C100007:SpellCheckStringValues", Scope = "member", Target = "AvePoint.GCommon.LDAPLookup.#CheckAccount(System.DirectoryServices.DirectorySearcher,System.String)", MessageId = "grouptype")]
[module: SuppressMessage("Microsoft.Naming", "CA1708:IdentifiersShouldDifferByMoreThanCase", Scope = "type", Target = "AvePoint.GCommon.Utility.I18N.I18NUtility")]
[module: SuppressMessage("CheckHardCode", "Z100009:CheckString", Scope = "member", Target = "AvePoint.GCommon.FileArchiverManager.#Test()")]
[module: SuppressMessage("CheckHardCode", "Z100009:CheckString", Scope = "member", Target = "AvePoint.GCommon.Utility.AvePerformanceLoggingTest.#MainTest()")]
