/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merged18NResources.MediaCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MediaCommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaCommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merged18NResources.MediaCommon.MediaCommonResource", typeof(MediaCommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve assembly [{0}] by default..
        /// </summary>
        public static string DefaultIocContainerManagerCurrentDomainAssemblyResolveWarning {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerCurrentDomainAssemblyResolveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting media data service....
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerBeginDataService {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerBeginDataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media data service failed:{0}.
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerError {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin integrating Windsor container to MicroKernel framework....
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerIntegrateMicroKernel {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerIntegrateMicroKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin integrating Windsor container and WCF framework....
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerIntegrateWcf {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerIntegrateWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media service successfully..
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerMediaStartSuccessfully {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerMediaStartSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media MicroKernel service failed:{0}.
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerMicroKernelServiceFailed {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerMicroKernelServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media register service failed:{0}.
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerRegisterServiceFailed {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerRegisterServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Windsor container....
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainerStartWindorContainer {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainerStartWindorContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin starting media register service....
        /// </summary>
        public static string DefaultIocContainerManagerLoadContainertMediaServiceStatusStarting {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerLoadContainertMediaServiceStatusStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Media service failed. Error code: {0}.
        /// </summary>
        public static string DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedEventMessage {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media windows service has a critical error and is forcing to be terminated..
        /// </summary>
        public static string DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedTerminateMedia {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedTerminateMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media windows service is failed to be terminated, reason: [{0}]..
        /// </summary>
        public static string DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedTerminateMediaError {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerMediaServiceStatusTrackerManagerFailedTerminateMediaErr" +
                        "or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Server details:
        ///   Control Server Address: {0}  
        ///   Control Server Port: {1}  
        ///   Media Server Name: {2}  
        ///   Media Server HostOrIp Address: {3}  
        ///   Media Server Control Port: {4}  
        ///   Media Server Data Port: {5}  
        ///   Media Server Platform: {6}  
        ///   Media Server Version: {7}  
        ///   Media Server CLR Version: {8}  
        ///   Media Server Machine Name: {9}  
        ///   Media Server Processor Count: {10} 
        ///   Media Server Current Time: {11} 
        ///   Media Server Current Time Zone: {12}.
        /// </summary>
        public static string DefaultIocContainerManagerMediaServiceStatusTrackerManagerStartedMediaServerDetail {
            get {
                return ResourceManager.GetString("DefaultIocContainerManagerMediaServiceStatusTrackerManagerStartedMediaServerDetai" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while collecting the garbage: {0}..
        /// </summary>
        public static string IocContainerGarbageCollectorCollectPerThreadLifestyleManagerCachedInstancesException {
            get {
                return ResourceManager.GetString("IocContainerGarbageCollectorCollectPerThreadLifestyleManagerCachedInstancesExcept" +
                        "ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP port should be a number between 1024 and 65535..
        /// </summary>
        public static string MediaEnvironmentCheckTcpPortIsAvaliableArgumentOutOfRangeExceptionTcpPort {
            get {
                return ResourceManager.GetString("MediaEnvironmentCheckTcpPortIsAvaliableArgumentOutOfRangeExceptionTcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file list is null or empty..
        /// </summary>
        public static string MediaFileTransferSendFilesArgumentNullExceptionSendingFileList {
            get {
                return ResourceManager.GetString("MediaFileTransferSendFilesArgumentNullExceptionSendingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending files: {0}..
        /// </summary>
        public static string MediaFileTransferSendFilesWarn {
            get {
                return ResourceManager.GetString("MediaFileTransferSendFilesWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media MicroKernel host service whose type is {0} is closed successfully..
        /// </summary>
        public static string MediaMicroKernelHostStartClosed {
            get {
                return ResourceManager.GetString("MediaMicroKernelHostStartClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media MicroKernel host service whose type is {0} is beginning to close..
        /// </summary>
        public static string MediaMicroKernelHostStartClosing {
            get {
                return ResourceManager.GetString("MediaMicroKernelHostStartClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media MicroKernel host service whose type is {0} occurs an error..
        /// </summary>
        public static string MediaMicroKernelHostStartFaulted {
            get {
                return ResourceManager.GetString("MediaMicroKernelHostStartFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media MicroKernel host service whose type is {0} is successfully started at Address: {1}..
        /// </summary>
        public static string MediaMicroKernelHostStartOpened {
            get {
                return ResourceManager.GetString("MediaMicroKernelHostStartOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Media MicroKernel host service whose type is {0} is starting at Address: {1}..
        /// </summary>
        public static string MediaMicroKernelHostStartOpening {
            get {
                return ResourceManager.GetString("MediaMicroKernelHostStartOpening", resourceCulture);
            }
        }
    }
}
