<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <NoWarn>SKEXP0001;SKEXP0011;SKEXP0070</NoWarn>
    <AssemblyName>AvePoint.RAI.Core</AssemblyName>
    <RootNamespace>AvePoint.RAI.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Registration\**" />
    <EmbeddedResource Remove="Registration\**" />
    <None Remove="Registration\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AiOptions.cs" />
    <Compile Remove="AiSettings.cs" />
    <Compile Remove="Services\IAiHttpClientFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Admin.Directory.directory_v1" Version="1.73.0.4030" />
    <PackageReference Include="Google.Apis.Admin.Reports.reports_v1" Version="1.73.0.3988" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Cloud.AIPlatform.V1" Version="3.60.0" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.72.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.72.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.72.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.72.0-alpha" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
    <PackageReference Include="System.Memory.Data" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
  </ItemGroup>

</Project>
