var res = {
  "JPMC_App_Classify": "Classify",
  "JPMC_App_Title": "Name",
  "JPMC_App_Save": "Save",
  "JPMC_App_Cancel": "Cancel",
  "JPMC_App_Close": "Close",
  "JPMC_App_ProgressIndicatorDescription": "Don't close the window. The process is not completed.",
  "JPMC_App_RecordCode": "Record Status",
  "JPMC_App_ClassCode": "Class Code",
  "JPMC_App_CountryCode": "Jurisdiction Driving Retention",
  "JPMC_App_RetentionType": "Retention Type",
  "JPMC_App_StartDate": "Start Date",
  "JPMC_App_CreateDate": "Created Date",
  "JPMC_App_ProcessStatus": "Status",
  "JPMC_App_ProcessStatus_Waiting": "Waiting",
  "JPMC_App_ProcessStatus_Running": "In Progress",
  "JPMC_App_ProcessStatus_Success": "Successful",
  "JPMC_App_ProcessStatus_Failed": "Failed",
  "JPMC_App_ProcessComment": "Comment",
  "JPMC_App_ProgressIndicatorLabel": "Total: {0}; Done: {1}",
  "JPMC_App_Msg_Classify_Error": "An error occurred. Please try again later. If the issue persists, contact support for help.",
  "JPMC_App_Msg_Action_NoPermission": "This operation cannot be performed. You must have at least the Edit Items permission for the document.",
  "JPMC_App_Msg_Action_NoPermission_Declared": "This operation cannot be performed. You don't have the permission to declare document as record.",
  "JPMC_App_Msg_Action_NoPermission_Undeclared": "This operation cannot be performed. You don't have the permission to remove a record declaration.",
  "JPMC_App_Msg_Error_Declared": "An error occurred while declaring document as record. Please try again later. If the issue persists, contact support for help.",
  "JPMC_App_Msg_Error_Undeclared": "An error occurred while removing the record declaration. Please try again later. If the issue persists, contact support for help.",
  "JPMC_App_Msg_Classify_Hold": "Failed to classify the document. The document is currently part of an in-place hold.",
  "JPMC_App_Msg_Classify_UnsupportedObj": "This operation is unsupported for the selected object.",
  "JPMC_App_Msg_Classify_Checkout_Final": "Failed to classify the document. The document is currently checked out and you cannot declare it as a record.",
  "JPMC_App_Msg_UnauthorizedAccessRootWeb": "Failed to retrieve the site type from the root site. You must have at least the Open permission for the root site.",
  "JPMC_App_Msg_Classify_NotCheckoutUser": "Failed to classify the document. The document is currently checked out by others.",
  "JPMC_App_Msg_Classify_ClassFieldNotFound": "Failed to classify the document. The Class Code column does not exist in the library.",
  "JPMC_App_Msg_Classify_ClassCodeNotFound": "Failed to classify the document. The class code cannot be found in the term store.",
  "JPMC_App_Msg_Classify_ChannelFolderWaring": "Classification for Teams channel folders is unsupported. However, files within the folder can be classified.",
  "JPMC_App_Msg_Classify_Successful": "Successful!",
  "JPMC_App_Msg_Classify_InProcess": "Classification may take longer than expected. You can close this panel, but please note that you will not receive a notification when the process is complete if you do so.",
  "JPMC_App_Msg_Classify_Skip": "The process completed with some exceptions. These documents may be subject to an in-place hold or may be checked out by others.",
  "JPMC_App_Msg_Classify_Exception": "The process completed with some failures. Please perform the operation again to re-process any failed items.",
  "JPMC_App_Msg_Classify_NeedUpdateApp": "The app package has some updates. You are required to reinstall the app."
};

define([], function () { return res; });
