/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Media.Storage.Resources.DropboxI18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DropboxI18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DropboxI18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Media.Storage.Resources.DropboxI18N.DropboxI18N", typeof(DropboxI18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Access_Token {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Access_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App key.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_AppKey {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_AppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App secret.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_AppSecret {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the detailed information for the storage location..
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Configure_your_root_folder_App_key_and_token_access {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Configure_your_root_folder_App_key_and_token_acces" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my client information.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Customized_Application {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Customized_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the client information provided by DocAve.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Default_Application {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Default_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Dropbox {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer between 0 and 65535..
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Must_be_a_number_between_0_and_65535 {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Must_be_a_number_between_0_and_65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Proxy {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Proxy_Host {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Proxy_Password {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Proxy_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Proxy_Port {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Proxy_Username {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Proxy_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Token.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Retrieve_Token {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Retrieve_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_Root_folder {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_Root_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder name cannot exceed 200 characters..
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_root_folder_cannot_exceed_200_characters {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_root_folder_cannot_exceed_200_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a folder name. A slash (/) can also be entered to connect the root folder of the account with all its files to the SharePoint library..
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_RootFolderName_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_RootFolderName_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the root folder name is incorrect..
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_RootFolderName_Invalid_Format {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_RootFolderName_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token access.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_TokenAccess {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_TokenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token secret.
        /// </summary>
        public static string MediaStorage_Connector_Dropbox_TokenSecret {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Dropbox_TokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token.
        /// </summary>
        public static string MediaStorage_Dropbox_Access_Token {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Access_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your access token, and try again..
        /// </summary>
        public static string MediaStorage_Dropbox_AccessTokenNotAvailable {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_AccessTokenNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string MediaStorage_Dropbox_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App key.
        /// </summary>
        public static string MediaStorage_Dropbox_AppKey {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_AppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App secret.
        /// </summary>
        public static string MediaStorage_Dropbox_AppSecret {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my client information.
        /// </summary>
        public static string MediaStorage_Dropbox_Customized_Application {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Customized_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the client information provided by DocAve.
        /// </summary>
        public static string MediaStorage_Dropbox_Default_Application {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Default_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        public static string MediaStorage_Dropbox_Dropbox {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        public static string MediaStorage_Dropbox_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your proxy username and password, and enter the correct one..
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy_Authentication_Filed {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy_Authentication_Filed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host.
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy_Host {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy_Password {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy_Port {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MediaStorage_Dropbox_Proxy_Username {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Proxy_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Token.
        /// </summary>
        public static string MediaStorage_Dropbox_Retrieve_Token {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Retrieve_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder.
        /// </summary>
        public static string MediaStorage_Dropbox_Root_folder {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Root_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a folder name. A slash (/) can also be entered to connect the root folder of the account with all its files to the SharePoint library..
        /// </summary>
        public static string MediaStorage_Dropbox_RootFolderName_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_RootFolderName_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the root folder name is incorrect..
        /// </summary>
        public static string MediaStorage_Dropbox_RootFolderName_Invalid_Format {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_RootFolderName_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder does not exist..
        /// </summary>
        public static string MediaStorage_Dropbox_RootFolderNotExist {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_RootFolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the connection information for the storage type you&apos;ve selected. This is required to read and write data saved in this library. Information needed for this form can be found in your storage vendor&apos;s documentation. .
        /// </summary>
        public static string MediaStorage_Dropbox_Specify_the_detailed_information_for_the_storage_location {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Specify_the_detailed_information_for_the_storage_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation test failed. Please verify the entered information and try again..
        /// </summary>
        public static string MediaStorage_Dropbox_Test_failed {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_Test_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token access.
        /// </summary>
        public static string MediaStorage_Dropbox_TokenAccess {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_TokenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token secret.
        /// </summary>
        public static string MediaStorage_Dropbox_TokenSecret {
            get {
                return ResourceManager.GetString("MediaStorage_Dropbox_TokenSecret", resourceCulture);
            }
        }
    }
}
