/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merged18NResources.MediaServiceArchiverBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MediaServiceArchiverBackupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaServiceArchiverBackupResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merged18NResources.MediaServiceArchiverBackup.MediaServiceArchiverBackupResource", typeof(MediaServiceArchiverBackupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while releasing resources: {0}.
        /// </summary>
        public static string ArchiverAdvancedSearchServiceCloseException {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceCloseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter {0} has {1} result(s)..
        /// </summary>
        public static string ArchiverAdvancedSearchServiceGetBranchesByFiltersResult {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceGetBranchesByFiltersResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown index type {0}..
        /// </summary>
        public static string ArchiverAdvancedSearchServiceGetFullPathException {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceGetFullPathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing Archiver advanced search: {0}..
        /// </summary>
        public static string ArchiverAdvancedSearchServiceProcessExceptionArchiverAdvancedSearchException {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceProcessExceptionArchiverAdvancedSearchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting advanced search on node: {0}..
        /// </summary>
        public static string ArchiverAdvancedSearchServiceSearchSiteCollectionBegin {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceSearchSiteCollectionBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching site collection {0}: {1}..
        /// </summary>
        public static string ArchiverAdvancedSearchServiceSearchSiteCollectionError {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceSearchSiteCollectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver advanced search result: {0}, {1}.
        /// </summary>
        public static string ArchiverAdvancedSearchServiceShoeResultArchiverAdvancedSearchResult {
            get {
                return ResourceManager.GetString("ArchiverAdvancedSearchServiceShoeResultArchiverAdvancedSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin browsing tree under the node {0}....
        /// </summary>
        public static string ArchiverBackupBrowserServiceArchiverBrowseResultBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupBrowserServiceArchiverBrowseResultBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing tree node finished..
        /// </summary>
        public static string ArchiverBackupBrowserServiceDisposeEnd {
            get {
                return ResourceManager.GetString("ArchiverBackupBrowserServiceDisposeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the archiver tree, details: {0}..
        /// </summary>
        public static string ArchiverBackupBrowserServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchiverBackupBrowserServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media confirms that the agent has received all the messages: [{0}]..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessConfirmMessage {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending thread for Archive backup: {0}..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessException {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item that is needed to be deleted has been sent to agent, item type: {0}, path: {1}..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessInfo {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive send confirm message thread is sending a keepalive message..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessKeepAlive {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessKeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item which is needed to be deleted has been sent to agent, this item head is {0}..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessSend {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All confirmed messages had been sent to agent..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessSendAll {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessSendAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive send confirm message thread starting....
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderSendProcessStart {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderSendProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin stopping archive send confirm message thread....
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderStopBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderStopBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped archive send confirm message thread successfully..
        /// </summary>
        public static string ArchiverBackupConfirmMessageSenderStopSuccessfully {
            get {
                return ResourceManager.GetString("ArchiverBackupConfirmMessageSenderStopSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin calculating archiver data size in physical device....
        /// </summary>
        public static string ArchiverBackupDataCalculatorCalculateBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupDataCalculatorCalculateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated successfully. ID: {0}, size: {1}.
        /// </summary>
        public static string ArchiverBackupDataCalculatorCalculateSize {
            get {
                return ResourceManager.GetString("ArchiverBackupDataCalculatorCalculateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating archiver data size in physical device completed..
        /// </summary>
        public static string ArchiverBackupDataCalculatorDisposeCalculateFinish {
            get {
                return ResourceManager.GetString("ArchiverBackupDataCalculatorDisposeCalculateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated archiver data size in physical device {0} failed, the detail is {1}..
        /// </summary>
        public static string ArchiverBackupDataCalculatorProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchiverBackupDataCalculatorProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detail is {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterAssembleIndexHeaderArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterAssembleIndexHeaderArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported header type {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterAssembleIndexHeaderError {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterAssembleIndexHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed data writer successfully..
        /// </summary>
        public static string ArchiverBackupDataWriterCloseEnd {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Block Changing: unknown file type: {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterGetDataFileNameUnknownFileTypeException {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterGetDataFileNameUnknownFileTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown store type: {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterGetFileHeaderXMLUnknownFileTypeException {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterGetFileHeaderXMLUnknownFileTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current backup data physical deviceID is: {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterGetFirstOnlinePhysicalDriveId {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterGetFirstOnlinePhysicalDriveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle header: {0}..
        /// </summary>
        public static string ArchiverBackupDataWriterHandleHeaderBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterHandleHeaderBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin handling header whose type is: {0}, path is: {1}....
        /// </summary>
        public static string ArchiverBackupDataWriterHandleHeaderInfo {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterHandleHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle tail: {0}.
        /// </summary>
        public static string ArchiverBackupDataWriterHandleTailHandle {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterHandleTailHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the job info table with encryption information  [{0}] finished..
        /// </summary>
        public static string ArchiverBackupDataWriterInitResourceFinished {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterInitResourceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening archive backup data writer....
        /// </summary>
        public static string ArchiverBackupDataWriterOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupDataWriterOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data mode of this job is {0}..
        /// </summary>
        public static string ArchiverBackupRetentionServiceMoveAndDeleteFileFromDeviceDataMode {
            get {
                return ResourceManager.GetString("ArchiverBackupRetentionServiceMoveAndDeleteFileFromDeviceDataMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention info is: {0}, content file number is: {1}..
        /// </summary>
        public static string ArchiverBackupRetentionServiceMoveAndDeleteFileFromDeviceInfo {
            get {
                return ResourceManager.GetString("ArchiverBackupRetentionServiceMoveAndDeleteFileFromDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin archiving retention job whose jobID is {0}....
        /// </summary>
        public static string ArchiverBackupRetentionServiceOpenStart {
            get {
                return ResourceManager.GetString("ArchiverBackupRetentionServiceOpenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished archiving retention job whose jobID is {0}..
        /// </summary>
        public static string ArchiverBackupRetentionServiceUpdateJobStatusAndControlTableEnd {
            get {
                return ResourceManager.GetString("ArchiverBackupRetentionServiceUpdateJobStatusAndControlTableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin converting request to archive backup job information....
        /// </summary>
        public static string ArchiverBackupServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pretreatment of the backup finished successfully..
        /// </summary>
        public static string ArchiverBackupServiceOpenEnd {
            get {
                return ResourceManager.GetString("ArchiverBackupServiceOpenEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while archiving upgrade browse tree, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowserServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowserServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin browsing the tree under the node....
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceBrowseBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceBrowseBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no directories under the node..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceBrowseDirectoryWarning {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceBrowseDirectoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully browsed the tree under the node..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceBrowseSuccessed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceBrowseSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No index was found in sitemasterindex table..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceGetSiteMasterIndexError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceGetSiteMasterIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening the index logical device....
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening the index processor....
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceOpenIndexProcessor {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceOpenIndexProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened the index processor..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceOpenIndexProcessorSuccessed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceOpenIndexProcessorSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened the index logical device..
        /// </summary>
        public static string ArchiverBackupUpgradeBrowseServiceOpenSuccessed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeBrowseServiceOpenSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merging the index, site collection: {0}, details: {1}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceExecuteInsertError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceExecuteInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while verifying data: file name: {0}, details: {1}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceExecuteVerifyError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceExecuteVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin generating Archiver data upgrade job report....
        /// </summary>
        public static string ArchiverBackupUpgradeServiceGenerateJobReportBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceGenerateJobReportBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating Archiver data job report, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceGenerateJobReportError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceGenerateJobReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished generating archiver data upgrade job report..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceGenerateJobReportFinished {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceGenerateJobReportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting indexes into the control sitemaster table, the URL is: {0}, details: {1}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceInsertControlSiteMasterIndexFailed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceInsertControlSiteMasterIndexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully inserted the indexes into the control sitemaster table, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceInsertControlSiteMasterIndexSuccessed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceInsertControlSiteMasterIndexSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merging the jobinfo table, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceInsertIntoJobInfoTableError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceInsertIntoJobInfoTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merging the sitemaster table, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceInsertIntoSiteMasterIndexError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceInsertIntoSiteMasterIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening index processor....
        /// </summary>
        public static string ArchiverBackupUpgradeServiceOpenIndexProcessorBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceOpenIndexProcessorBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened the index processor..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceOpenIndexProcessorSuccessed {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceOpenIndexProcessorSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while archiving upgrade data, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merging the index, item: {0}, details: {1}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceReInsertError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceReInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to upgrade the sitecollection, detail:{0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceUpgradeContinue {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceUpgradeContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while upgrading data, details: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceUpgradeError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceUpgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the index logical device, details:{0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceUpgradeIndexLogicalDeviceNotFound {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceUpgradeIndexLogicalDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of item {1} was not mapped, detials: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceVerifyDataFileExistError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceVerifyDataFileExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin verifying data mapping status, SiteUrl: {0}...                                    .
        /// </summary>
        public static string ArchiverBackupUpgradeServiceVerifyDataMappedBegin {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceVerifyDataMappedBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgraded Data is not mapped, detials: {0}.                                                     .
        /// </summary>
        public static string ArchiverBackupUpgradeServiceVerifyDataMappedError {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceVerifyDataMappedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifing data mapping status finished, the site URL is: {0}..
        /// </summary>
        public static string ArchiverBackupUpgradeServiceVerifyDataMappedFinished {
            get {
                return ResourceManager.GetString("ArchiverBackupUpgradeServiceVerifyDataMappedFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any indexes which need to upgrade from the device{0}..
        /// </summary>
        public static string ArchiverBackupVerifyImportDataServiceGetUpgradeInfoError {
            get {
                return ResourceManager.GetString("ArchiverBackupVerifyImportDataServiceGetUpgradeInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade data is not mapped all ..
        /// </summary>
        public static string ArchiverBackupVerifyImportDataServiceNotMappedAllMessage {
            get {
                return ResourceManager.GetString("ArchiverBackupVerifyImportDataServiceNotMappedAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown index type: {0}.
        /// </summary>
        public static string ArchiverFiltersHandlerGetRealNameException {
            get {
                return ResourceManager.GetString("ArchiverFiltersHandlerGetRealNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported filter condition: {0}.
        /// </summary>
        public static string ArchiverFiltersHandlerValidateByConditionAndRuleConditionException {
            get {
                return ResourceManager.GetString("ArchiverFiltersHandlerValidateByConditionAndRuleConditionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported filter rule type: {0}.
        /// </summary>
        public static string ArchiverFiltersHandlerValidateByConditionAndRuleRuleException {
            get {
                return ResourceManager.GetString("ArchiverFiltersHandlerValidateByConditionAndRuleRuleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to release resources, details: {0}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceCloseFailed {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceCloseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully released all the resources..
        /// </summary>
        public static string ArchiverFullTextIndexServiceCloseSuccessfully {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceCloseSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media starts preparing data for search.exe..
        /// </summary>
        public static string ArchiverFullTextIndexServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information of archiver fulltext job is {0}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceOpenJobInfo {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceOpenJobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiver fulltext index finished with {0} item(s) failed..
        /// </summary>
        public static string ArchiverFullTextIndexServiceRestoreEnd {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceRestoreEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while indexing fulltext, details: {0}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceRestoreError {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin sending item {0}...  The item type is: {1}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceSendIndexDataBegin {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceSendIndexDataBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while indexing fulltext to {0}, the file type is: {1}, details: {2}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceSendIndexDataError {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceSendIndexDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent  item {0}, the item type is {1}..
        /// </summary>
        public static string ArchiverFullTextIndexServiceSendIndexDataSuccessfully {
            get {
                return ResourceManager.GetString("ArchiverFullTextIndexServiceSendIndexDataSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin getting content data number by job ID....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceGetContentDataNumsByJobIdInformation {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceGetContentDataNumsByJobIdInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the count: parent path is null..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceGetCountFromBodyArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceGetCountFromBodyArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin getting content data number by job ID....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceGetMetaDataNumsByJobIdInformation {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceGetMetaDataNumsByJobIdInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin getting retention items by job ID....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceGetRetensionItemsByJobIdInformation {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceGetRetensionItemsByJobIdInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin getting data file retention information....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceGetRetentionInformation {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceGetRetentionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded failed: the path is null..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadAllArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadAllArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded failed: the path is null..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File GUID is empty..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadByFileGUIDArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadByFileGUIDArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading folders: parent path is null..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadFoldersArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadFoldersArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin loading folders under {0}....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadFoldersStart {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadFoldersStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading items: parent path is null..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadItemsArgumentNullException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadItemsArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin loading items under {0}....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadItemsStart {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadItemsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin loading load item from {0}....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceLoadStart {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceLoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin updating content offset by ID....
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceUpdateContentOffsetsInformation {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceUpdateContentOffsetsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown store type: {0}..
        /// </summary>
        public static string ArchiverHeadAndBodyIndexServiceUpdateHeaderArchivedNotSupportedException {
            get {
                return ResourceManager.GetString("ArchiverHeadAndBodyIndexServiceUpdateHeaderArchivedNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed index service successfully..
        /// </summary>
        public static string ArchiverIndexServiceCloseEnd {
            get {
                return ResourceManager.GetString("ArchiverIndexServiceCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening index service....
        /// </summary>
        public static string ArchiverIndexServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverIndexServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened index service successfully..
        /// </summary>
        public static string ArchiverIndexServiceOpenEnd {
            get {
                return ResourceManager.GetString("ArchiverIndexServiceOpenEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the index in this logical device..
        /// </summary>
        public static string ArchiverIndexServiceOpenIndexCanNotFoundException {
            get {
                return ResourceManager.GetString("ArchiverIndexServiceOpenIndexCanNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merging indexes together, details: {0}..
        /// </summary>
        public static string ArchiverMergeIndexServiceMergingIndexError {
            get {
                return ResourceManager.GetString("ArchiverMergeIndexServiceMergingIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error is {0}..
        /// </summary>
        public static string ArchiverMergeIndexServiceRealMergeIndexError {
            get {
                return ResourceManager.GetString("ArchiverMergeIndexServiceRealMergeIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating job progress: {0}..
        /// </summary>
        public static string ArchiverMergeIndexServiceUpdateJobProgressError {
            get {
                return ResourceManager.GetString("ArchiverMergeIndexServiceUpdateJobProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current merging index progress is {0}..
        /// </summary>
        public static string ArchiverMergeIndexServiceUpdateJobProgressInfo {
            get {
                return ResourceManager.GetString("ArchiverMergeIndexServiceUpdateJobProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while rebuilding index, details: {0}..
        /// </summary>
        public static string ArchiverRebuildIndexCommandExecuteCommandError {
            get {
                return ResourceManager.GetString("ArchiverRebuildIndexCommandExecuteCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown level: {0}..
        /// </summary>
        public static string ArchiverRestoreBrowserBrowseArchiverBackupDataLevelException {
            get {
                return ResourceManager.GetString("ArchiverRestoreBrowserBrowseArchiverBackupDataLevelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown load tree mode: {0}..
        /// </summary>
        public static string ArchiverRestoreBrowserOpenModeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreBrowserOpenModeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed archive restore data reader successfully..
        /// </summary>
        public static string ArchiverRestoreDataReaderCloseEnd {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening stream {0}... The file size is {1}..
        /// </summary>
        public static string ArchiverRestoreDataReaderDataBlockOpeningBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderDataBlockOpeningBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version data does not support content..
        /// </summary>
        public static string ArchiverRestoreDataReaderGetFileNameByAveVersionContentException {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderGetFileNameByAveVersionContentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data type {0}..
        /// </summary>
        public static string ArchiverRestoreDataReaderGetFileNameByAveVersionTypeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderGetFileNameByAveVersionTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening archive restore data reader....
        /// </summary>
        public static string ArchiverRestoreDataReaderOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin invoking opendatablock method....
        /// </summary>
        public static string ArchiverRestoreDataReaderOpenDataBlockBeginDebug {
            get {
                return ResourceManager.GetString("ArchiverRestoreDataReaderOpenDataBlockBeginDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start calculating restore data....
        /// </summary>
        public static string ArchiverRestoreServiceCalculateTotalItemNumBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceCalculateTotalItemNumBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The restored data count of the restore job is {0}..
        /// </summary>
        public static string ArchiverRestoreServiceCalculateTotalItemNumEnd {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceCalculateTotalItemNumEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post restore is successful and archive restore complete..
        /// </summary>
        public static string ArchiverRestoreServiceCloseEnd {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data version: {0}.
        /// </summary>
        public static string ArchiverRestoreServiceGetStreamOpenTypeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceGetStreamOpenTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After cut tree{0} {1}.
        /// </summary>
        public static string ArchiverRestoreServiceOpenAfterCut {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceOpenAfterCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cutting tree...{0} {1}.
        /// </summary>
        public static string ArchiverRestoreServiceOpenBeforeCut {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceOpenBeforeCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare the pretreatment of the archiver restore service..
        /// </summary>
        public static string ArchiverRestoreServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown loading tree mode: {0}..
        /// </summary>
        public static string ArchiverRestoreServicePreRestoreModeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreServicePreRestoreModeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing to the data, details: {0}..
        /// </summary>
        public static string ArchiverRestoreServiceSendItemDataError {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceSendItemDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the data, details: {0}..
        /// </summary>
        public static string ArchiverRestoreServiceSendItemDataException {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceSendItemDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin sending the data of [{0}]. And the version flag of current item is: {1}..
        /// </summary>
        public static string ArchiverRestoreServiceSendItemDataSendData {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceSendItemDataSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating job progress, details: {0}..
        /// </summary>
        public static string ArchiverRestoreServiceUpdateJobProgressError {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceUpdateJobProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin updating job progress {0}....
        /// </summary>
        public static string ArchiverRestoreServiceUpdateJobProgressUpdateProgress {
            get {
                return ResourceManager.GetString("ArchiverRestoreServiceUpdateJobProgressUpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown index type: {0}..
        /// </summary>
        public static string ArchiverRestoreStatisticsCalculatorCalculateStatisticsForeachIndexUnknownType {
            get {
                return ResourceManager.GetString("ArchiverRestoreStatisticsCalculatorCalculateStatisticsForeachIndexUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the result statistics is : {0}SiteCollection:   Count: {1}  {0}                  Size:  {2}  {0}Site:             Count: {3}  {0}                  Size:  {4}  {0}List:             Count: {5}  {0}                  Size:  {6}  {0}Folder:           Count: {7}  {0}                  Size:  {8}  {0}Document:         Count: {9}  {0}                  Size:  {10} {0}DocumentVersion:  Count: {11} {0}                  Size:  {12} {0}Item:             Count: {13} {0}                  Size:  {14} {0}ItemVersion:      Co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArchiverRestoreStatisticsCalculatorGetRestoreStatisticsResult {
            get {
                return ResourceManager.GetString("ArchiverRestoreStatisticsCalculatorGetRestoreStatisticsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start calculating archive restore statistics....
        /// </summary>
        public static string ArchiverRestoreStatisticsCalculatorOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreStatisticsCalculatorOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calculating restore statistics, details: {0}..
        /// </summary>
        public static string ArchiverRestoreStatisticsCalculatorProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchiverRestoreStatisticsCalculatorProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of items is {0}..
        /// </summary>
        public static string ArchiverRestoreToFSServiceCalculateTotalItemNumResult {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCalculateTotalItemNumResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start calculating item that is needed to restore....
        /// </summary>
        public static string ArchiverRestoreToFSServiceCalculateTotalItemNumStart {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCalculateTotalItemNumStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring data to FS: {0}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceCloseError {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating job summary, details: {0}..
        /// </summary>
        public static string ArchiverRestoreToFSServiceCloseSendJobSummaryError {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCloseSendJobSummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore data in Archiver to FS completed..
        /// </summary>
        public static string ArchiverRestoreToFSServiceCloseSucceed {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCloseSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type [{1}] of this file does not need to write to FS [{0}]..
        /// </summary>
        public static string ArchiverRestoreToFSServiceCreateFolderOrFileNotWrite {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCreateFolderOrFileNotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening or creating directory {0}....
        /// </summary>
        public static string ArchiverRestoreToFSServiceCreateFolderOrFileOpen {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceCreateFolderOrFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run the restore job..
        /// </summary>
        public static string ArchiverRestoreToFSServiceErrorMessage {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data version: {0}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceGetStreamOpenTypeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceGetStreamOpenTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After cut tree{0} {1}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceOpenAfterCut {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceOpenAfterCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cutting tree{0} {1}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceOpenBeforeCut {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceOpenBeforeCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare to archive restore to FS..
        /// </summary>
        public static string ArchiverRestoreToFSServiceOpenBegin {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending data, details: {0}..
        /// </summary>
        public static string ArchiverRestoreToFSServiceSendItemDataDtoException {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceSendItemDataDtoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin restoring: {0}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceSendItemDataDtoRestore {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceSendItemDataDtoRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating job progress: {0}.
        /// </summary>
        public static string ArchiverRestoreToFSServiceUpdateJobProgressError {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceUpdateJobProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating job report, details: {0}..
        /// </summary>
        public static string ArchiverRestoreToFSServiceUpdateJobReportException {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceUpdateJobReportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file {0} to {1}....
        /// </summary>
        public static string ArchiverRestoreToFSServiceWriteDataToFileWrite {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSServiceWriteDataToFileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored the data to Storage..
        /// </summary>
        public static string ArchiverRestoreToFSSuccessfulMessage {
            get {
                return ResourceManager.GetString("ArchiverRestoreToFSSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The restore tree after cutting: {0} {1}..
        /// </summary>
        public static string ArchiverRestoreTreeHandlerConvertRequestToRestoreJobCuttedTree {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerConvertRequestToRestoreJobCuttedTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init tree: {0} {1}..
        /// </summary>
        public static string ArchiverRestoreTreeHandlerConvertRequestToRestoreJobInitTree {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerConvertRequestToRestoreJobInitTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf node is unchecked..
        /// </summary>
        public static string ArchiverRestoreTreeHandlerProcessNodeDtoInternalNodeException {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerProcessNodeDtoInternalNodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin sending all children under {0}....
        /// </summary>
        public static string ArchiverRestoreTreeHandlerSendAllChildrenDtoSendChildren {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerSendAllChildrenDtoSendChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin sending selected items data....
        /// </summary>
        public static string ArchiverRestoreTreeHandlerSendSelectedItemsDtoSendItems {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerSendSelectedItemsDtoSendItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin sending sub items data from {0}....
        /// </summary>
        public static string ArchiverRestoreTreeHandlerSendSubItemsDtoSendSubItems {
            get {
                return ResourceManager.GetString("ArchiverRestoreTreeHandlerSendSubItemsDtoSendSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching retention time span, details: {0}..
        /// </summary>
        public static string ArchiverSiteMasterIndexServiceGetRetentionTimeSpanByJobIdWarn {
            get {
                return ResourceManager.GetString("ArchiverSiteMasterIndexServiceGetRetentionTimeSpanByJobIdWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring data to file system, details: {0}..
        /// </summary>
        public static string ArchvierRestoreToFSServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("ArchvierRestoreToFSServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parent node with URL: {0}..
        /// </summary>
        public static string EndUserArchiverBrowserServiceAddParentNodeUrl {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceAddParentNodeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current node has {0} children..
        /// </summary>
        public static string EndUserArchiverBrowserServiceBrowseChildrenCount {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceBrowseChildrenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start viewing sub node in [{0}]....
        /// </summary>
        public static string EndUserArchiverBrowserServiceBrowseInfo {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceBrowseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened the device and begin viewing the node whose MD5 is [{0}]..
        /// </summary>
        public static string EndUserArchiverBrowserServiceBrowseStartView {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceBrowseStartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing sub nodes for end user archiver finished..
        /// </summary>
        public static string EndUserArchiverBrowserServiceDisposeFinish {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceDisposeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening index device for end user archiver view....
        /// </summary>
        public static string EndUserArchiverBrowserServiceOpenInfo {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceOpenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while viewing the node in end user archiver, details: {0}..
        /// </summary>
        public static string EndUserArchiverBrowserServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("EndUserArchiverBrowserServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MD5 of current file path is [{0}]..
        /// </summary>
        public static string EndUserArchiverDownloadServiceDownloadPathMD5 {
            get {
                return ResourceManager.GetString("EndUserArchiverDownloadServiceDownloadPathMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current node archive time is {0}, final disposition time is {1} with tick {2}..
        /// </summary>
        public static string EndUserBrowserIndexServiceGetChildIndexListInfo {
            get {
                return ResourceManager.GetString("EndUserBrowserIndexServiceGetChildIndexListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time span is {0} seconds..
        /// </summary>
        public static string EndUserBrowserIndexServiceGetRetentionTimeSpanInfo {
            get {
                return ResourceManager.GetString("EndUserBrowserIndexServiceGetRetentionTimeSpanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the url finished and the result is {0}..
        /// </summary>
        public static string EndUserErrorPageCheckServiceCheckFinished {
            get {
                return ResourceManager.GetString("EndUserErrorPageCheckServiceCheckFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the device finished and start checking the URL [{0}]..
        /// </summary>
        public static string EndUserErrorPageCheckServiceCheckStartCheckingUrl {
            get {
                return ResourceManager.GetString("EndUserErrorPageCheckServiceCheckStartCheckingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking error page finished..
        /// </summary>
        public static string EndUserErrorPageCheckServiceDisposeFinished {
            get {
                return ResourceManager.GetString("EndUserErrorPageCheckServiceDisposeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking error page, details: {0}..
        /// </summary>
        public static string EndUserErrorPageCheckServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("EndUserErrorPageCheckServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting item {0}, details: {1}..
        /// </summary>
        public static string ExportToConcordanceServiceDoRestoreError {
            get {
                return ResourceManager.GetString("ExportToConcordanceServiceDoRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting item [{0}] finished..
        /// </summary>
        public static string ExportToConcordanceServiceDoRestoreFinished {
            get {
                return ResourceManager.GetString("ExportToConcordanceServiceDoRestoreFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MD5 of current file path is [{0}]..
        /// </summary>
        public static string ExportToConcordanceServiceDoRestorePathMD5 {
            get {
                return ResourceManager.GetString("ExportToConcordanceServiceDoRestorePathMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting data, details: {0}..
        /// </summary>
        public static string ExportToConcordanceServiceDoRestoreProcessExceptionError {
            get {
                return ResourceManager.GetString("ExportToConcordanceServiceDoRestoreProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while merge index, details :  {0} ..
        /// </summary>
        public static string MergeIndexServiceFailed {
            get {
                return ResourceManager.GetString("MergeIndexServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated job report failed, detail is {0}..
        /// </summary>
        public static string MergeIndexServiceGenerateJobReportError {
            get {
                return ResourceManager.GetString("MergeIndexServiceGenerateJobReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated job report successfully, job: {0}.
        /// </summary>
        public static string MergeIndexServiceGenerateJobReportFinished {
            get {
                return ResourceManager.GetString("MergeIndexServiceGenerateJobReportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin inserting data into {0} table....
        /// </summary>
        public static string MergeIndexServiceInsertIntoMainIndexBodyBegin {
            get {
                return ResourceManager.GetString("MergeIndexServiceInsertIntoMainIndexBodyBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert data into {0} table completed..
        /// </summary>
        public static string MergeIndexServiceInsertIntoMainIndexBodyEnd {
            get {
                return ResourceManager.GetString("MergeIndexServiceInsertIntoMainIndexBodyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin inserting data into {0} table....
        /// </summary>
        public static string MergeIndexServiceInsertIntoMainIndexHeadBegin {
            get {
                return ResourceManager.GetString("MergeIndexServiceInsertIntoMainIndexHeadBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert data into {0} table completed..
        /// </summary>
        public static string MergeIndexServiceInsertIntoMainIndexHeadEnd {
            get {
                return ResourceManager.GetString("MergeIndexServiceInsertIntoMainIndexHeadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pieces of record need to be inserted..
        /// </summary>
        public static string MergeIndexServiceMergeIndexCount {
            get {
                return ResourceManager.GetString("MergeIndexServiceMergeIndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging index is successful..
        /// </summary>
        public static string MergeIndexServiceMergeIndexEnd {
            get {
                return ResourceManager.GetString("MergeIndexServiceMergeIndexEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin merging index....
        /// </summary>
        public static string MergeIndexServiceOpenBegin {
            get {
                return ResourceManager.GetString("MergeIndexServiceOpenBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened indexLogicalDevice successfully..
        /// </summary>
        public static string MergeIndexServiceOpenOpenIndexLogicalDeviceSuccessfully {
            get {
                return ResourceManager.GetString("MergeIndexServiceOpenOpenIndexLogicalDeviceSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged index failed, details: {0}..
        /// </summary>
        public static string MergeIndexServiceProcessExceptionError {
            get {
                return ResourceManager.GetString("MergeIndexServiceProcessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge index successful ..
        /// </summary>
        public static string MergeIndexServiceSuccessful {
            get {
                return ResourceManager.GetString("MergeIndexServiceSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated job status and control table failed, details: {0}..
        /// </summary>
        public static string MergeIndexServiceUpdateJobStatusAndControlTableError {
            get {
                return ResourceManager.GetString("MergeIndexServiceUpdateJobStatusAndControlTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while moving the Archiver index. Please refer to the logs for details..
        /// </summary>
        public static string MoveIndexServiceGenerateJobReportFailed {
            get {
                return ResourceManager.GetString("MoveIndexServiceGenerateJobReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move archiver indexes successful..
        /// </summary>
        public static string MoveIndexServiceGenerateJobReportSuccessful {
            get {
                return ResourceManager.GetString("MoveIndexServiceGenerateJobReportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file {0}, details: {1}..
        /// </summary>
        public static string RetentionServiceDeleteDataFromDeviceError {
            get {
                return ResourceManager.GetString("RetentionServiceDeleteDataFromDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting file {0}, details: {1}..
        /// </summary>
        public static string RetentionServiceDeleteDataFromDeviceWarn {
            get {
                return ResourceManager.GetString("RetentionServiceDeleteDataFromDeviceWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted the data whose storage information is [{0}]..
        /// </summary>
        public static string RetentionServiceDeleteFileByStorageInfoInfo {
            get {
                return ResourceManager.GetString("RetentionServiceDeleteFileByStorageInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting file {0}, details: {1}..
        /// </summary>
        public static string RetentionServiceDeleteFileByStorageInfoWarn {
            get {
                return ResourceManager.GetString("RetentionServiceDeleteFileByStorageInfoWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start generating job report... Job: {0}.
        /// </summary>
        public static string RetentionServiceGenerateJobReportBegin {
            get {
                return ResourceManager.GetString("RetentionServiceGenerateJobReportBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate job report completed. Job: {0}.
        /// </summary>
        public static string RetentionServiceGenerateJobReportComplete {
            get {
                return ResourceManager.GetString("RetentionServiceGenerateJobReportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating job report, details: {1}. Job: {0}.
        /// </summary>
        public static string RetentionServiceGenerateJobReportError {
            get {
                return ResourceManager.GetString("RetentionServiceGenerateJobReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start executing moving data. Job: {0}.
        /// </summary>
        public static string RetentionServiceMoveJobDataBegin {
            get {
                return ResourceManager.GetString("RetentionServiceMoveJobDataBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while moving data, job {0}, details: {1}..
        /// </summary>
        public static string RetentionServiceMoveJobDataError {
            get {
                return ResourceManager.GetString("RetentionServiceMoveJobDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved data successfully. Job: {0}, size: {1} bytes.
        /// </summary>
        public static string RetentionServiceMoveJobDataFinished {
            get {
                return ResourceManager.GetString("RetentionServiceMoveJobDataFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening destinationDataLogicalDevice....
        /// </summary>
        public static string RetentionServiceOpenDestinationDataDevice {
            get {
                return ResourceManager.GetString("RetentionServiceOpenDestinationDataDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened destinationDataLogicalDevice successfully..
        /// </summary>
        public static string RetentionServiceOpenDestinationDataDeviceFinished {
            get {
                return ResourceManager.GetString("RetentionServiceOpenDestinationDataDeviceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin opening IndexLogicalDevice and DataLogicalDevice....
        /// </summary>
        public static string RetentionServiceOpenIndexAndDataDevice {
            get {
                return ResourceManager.GetString("RetentionServiceOpenIndexAndDataDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened indexLogicalDevice and dataLogicalDevice successfully..
        /// </summary>
        public static string RetentionServiceOpenIndexAndDataDeviceFinished {
            get {
                return ResourceManager.GetString("RetentionServiceOpenIndexAndDataDeviceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current storage system is not valid, details: {1}..
        /// </summary>
        public static string RetentionServiceRealMoveInvalidDevice {
            get {
                return ResourceManager.GetString("RetentionServiceRealMoveInvalidDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start deleting data... Job: {0}.
        /// </summary>
        public static string RetentionServiceRetainJobDataBegin {
            get {
                return ResourceManager.GetString("RetentionServiceRetainJobDataBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting data, job: {0} details: {1}..
        /// </summary>
        public static string RetentionServiceRetainJobDataDeleteDataError {
            get {
                return ResourceManager.GetString("RetentionServiceRetainJobDataDeleteDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted data successfully, job: {0}, size: {1} bytes..
        /// </summary>
        public static string RetentionServiceRetainJobDataDeleteDataFinished {
            get {
                return ResourceManager.GetString("RetentionServiceRetainJobDataDeleteDataFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown retention rule type: {0}.
        /// </summary>
        public static string RetentionServiceRetainUnknownFileTypeException {
            get {
                return ResourceManager.GetString("RetentionServiceRetainUnknownFileTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin updating the manager table and job status....
        /// </summary>
        public static string RetentionServiceUpdateJobStatusAndControlTableBegin {
            get {
                return ResourceManager.GetString("RetentionServiceUpdateJobStatusAndControlTableBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the manager table and job status, details: {0}..
        /// </summary>
        public static string RetentionServiceUpdateJobStatusAndControlTableError {
            get {
                return ResourceManager.GetString("RetentionServiceUpdateJobStatusAndControlTableError", resourceCulture);
            }
        }
    }
}
