/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Wrapper.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WrapperRestoreReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WrapperRestoreReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Wrapper.Resource.RestoreReport.WrapperRestoreReportResource", typeof(WrapperRestoreReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding &quot;{0}&quot; to the term group contributors. Details: {1}.
        /// </summary>
        public static string AddMetadataGroupContributorFailed {
            get {
                return ResourceManager.GetString("AddMetadataGroupContributorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding &quot;{1}&quot; to the stakeholders of the term set: {0}. Details: {2}.
        /// </summary>
        public static string AddTermSetStakeholderFailed {
            get {
                return ResourceManager.GetString("AddTermSetStakeholderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the term: {0}. Details: {1}.
        /// </summary>
        public static string CreateTermFailed {
            get {
                return ResourceManager.GetString("CreateTermFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; does not have enough permission to create the term group: {1}. Go to Microsoft 365 admin center to make sure this user has been added to Term Store Administrators, and run the restore job again..
        /// </summary>
        public static string CreateTermGroupFailed {
            get {
                return ResourceManager.GetString("CreateTermGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user does not have enough permission to create the term set: {0}. Go to Microsoft 365 admin center to make sure this user has been added to Term Store Administrators, and run the restore job again..
        /// </summary>
        public static string CreateTermSetFailed {
            get {
                return ResourceManager.GetString("CreateTermSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discovered file size of {0} is different from the file size retrieved from SharePoint REST API..
        /// </summary>
        public static string FileContentLengthDismatch {
            get {
                return ResourceManager.GetString("FileContentLengthDismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting properties for the term group: {0}. Details: {1}.
        /// </summary>
        public static string SetMetadataGroupPropertiesFailed {
            get {
                return ResourceManager.GetString("SetMetadataGroupPropertiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting &quot;{1}&quot; as the owner of the term: {0}. Details: {2}.
        /// </summary>
        public static string SetTermOwnerFailed {
            get {
                return ResourceManager.GetString("SetTermOwnerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting properties for the term: {0}. Details: {1}.
        /// </summary>
        public static string SetTermPropertiesFailed {
            get {
                return ResourceManager.GetString("SetTermPropertiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting the owner &quot;{1}&quot; for the term set: {0}. Details: {2}.
        /// </summary>
        public static string SetTermSetOwnerFailed {
            get {
                return ResourceManager.GetString("SetTermSetOwnerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting properties for the term set: {0}. Details: {1}.
        /// </summary>
        public static string SetTermSetPropertiesFailed {
            get {
                return ResourceManager.GetString("SetTermSetPropertiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. The current user does not have enough permission to perform this action or access the resource..
        /// </summary>
        public static string Wrapper_AccessDenied {
            get {
                return ResourceManager.GetString("Wrapper_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft 365 user {0} has been disabled and cannot connect to the site collection {1}. Please go to the SharePoint admin center to check the status of this user..
        /// </summary>
        public static string Wrapper_AccountDisableError {
            get {
                return ResourceManager.GetString("Wrapper_AccountDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; does not have enough permission to restore the metadata service. Navigate to the Microsoft 365 admin center to make sure this user is a Term Store Administrator and then run the restore job again..
        /// </summary>
        public static string Wrapper_ConfirmTermStoreAdmin {
            get {
                return ResourceManager.GetString("Wrapper_ConfirmTermStoreAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. The Microsoft 365 user {0} is not the site collection administrator or does not have the Global administrator role..
        /// </summary>
        public static string Wrapper_ConfirmUserPermission {
            get {
                return ResourceManager.GetString("Wrapper_ConfirmUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message: {0} Site URL: {1}.
        /// </summary>
        public static string Wrapper_ConnectSiteError {
            get {
                return ResourceManager.GetString("Wrapper_ConnectSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the storage server..
        /// </summary>
        public static string Wrapper_ConnectStorageError {
            get {
                return ResourceManager.GetString("Wrapper_ConnectStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the content type &quot;{0}&quot; on which the deployed item depends in the destination..
        /// </summary>
        public static string Wrapper_ConnotFindContentTypeSchemaDependency {
            get {
                return ResourceManager.GetString("Wrapper_ConnotFindContentTypeSchemaDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the column &quot;{0}&quot; on which the deployed item depends in the destination..
        /// </summary>
        public static string Wrapper_ConnotFindFieldSchemaDependency {
            get {
                return ResourceManager.GetString("Wrapper_ConnotFindFieldSchemaDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the schema dependency of the {1} &quot;{0}&quot;..
        /// </summary>
        public static string Wrapper_ConnotFindSchemaDependency {
            get {
                return ResourceManager.GetString("Wrapper_ConnotFindSchemaDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema dependency of the {1} &quot;{0}&quot; conflicts with a destination {1} using the same name or ID..
        /// </summary>
        public static string Wrapper_ContentTypeConflict {
            get {
                return ResourceManager.GetString("Wrapper_ContentTypeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file&apos;s {1} &quot;{0}&quot; does not exist in the destination site..
        /// </summary>
        public static string Wrapper_ContentTypeFailed {
            get {
                return ResourceManager.GetString("Wrapper_ContentTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is currently unavailable..
        /// </summary>
        public static string Wrapper_DeviceOpenUnaccessed {
            get {
                return ResourceManager.GetString("Wrapper_DeviceOpenUnaccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to discover the source data during backup..
        /// </summary>
        public static string Wrapper_DiscoverFailed {
            get {
                return ResourceManager.GetString("Wrapper_DiscoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site has exceeded its maximum file storage limit..
        /// </summary>
        public static string Wrapper_ExceedStorageLimit {
            get {
                return ResourceManager.GetString("Wrapper_ExceedStorageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the file that caches this file and its history versions has exceeded 20 GB. Please choose &quot;Split the cache file for versions&quot; in the backup job..
        /// </summary>
        public static string Wrapper_ExceedTempLimit {
            get {
                return ResourceManager.GetString("Wrapper_ExceedTempLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access the destination site collection. The username or password is incorrect. Site Collection URL: {0}..
        /// </summary>
        public static string Wrapper_IncorrectUserNameOrPasswordError {
            get {
                return ResourceManager.GetString("Wrapper_IncorrectUserNameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rights Management Service client is not available. Details: {0}..
        /// </summary>
        public static string Wrapper_IRMMSIPCClientNotAvailable {
            get {
                return ResourceManager.GetString("Wrapper_IRMMSIPCClientNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The super user is not configured. Go to Control Panel to configure a super user for the current tenant. Tenant ID: {0}. App Principal ID: {1}..
        /// </summary>
        public static string Wrapper_IRMSuperUserNotConfigured {
            get {
                return ResourceManager.GetString("Wrapper_IRMSuperUserNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decrypt the file {0}. Make sure the symmetric key is available. Tenant ID: {1}. App Principal ID: {2}. Details: {3}..
        /// </summary>
        public static string Wrapper_IRMUnprotectFileFailed {
            get {
                return ResourceManager.GetString("Wrapper_IRMUnprotectFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replicate this list or library. The destination environment has an existing list or library with the same name but of a different type. .
        /// </summary>
        public static string Wrapper_ListTemplateConflict {
            get {
                return ResourceManager.GetString("Wrapper_ListTemplateConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data cannot be found in SharePoint. The data may have been moved or deleted..
        /// </summary>
        public static string Wrapper_MissingObject {
            get {
                return ResourceManager.GetString("Wrapper_MissingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the job as multiple requests were sent. Please run the job again..
        /// </summary>
        public static string Wrapper_MultipleRequestError {
            get {
                return ResourceManager.GetString("Wrapper_MultipleRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object was scanned through AvePoint Online Services Auto Discovery using the Microsoft 365 app profile authentication method. This object can only be accessed using a service account due to API limitations in Microsoft 365. Please add a service account to your AvePoint Online Services portal to manage this content: {0}..
        /// </summary>
        public static string Wrapper_ObjectNotSupportedWithAppProfile {
            get {
                return ResourceManager.GetString("Wrapper_ObjectNotSupportedWithAppProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AppData was not restored because the app itself has failed to install..
        /// </summary>
        public static string Wrapper_RestoreAppDataFailedForInstallAppFailed {
            get {
                return ResourceManager.GetString("Wrapper_RestoreAppDataFailedForInstallAppFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Online environment is busy now. Please try again later. Error: {0}.
        /// </summary>
        public static string Wrapper_SharePointBusyError {
            get {
                return ResourceManager.GetString("Wrapper_SharePointBusyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped restoring the list. Some items in this list cannot be edited because the list is in a Microsoft 365 Group team site. List Name: {0}..
        /// </summary>
        public static string Wrapper_SkipO365SpecialList {
            get {
                return ResourceManager.GetString("Wrapper_SkipO365SpecialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped restoring this item since it is an Access Request, which is unsupported..
        /// </summary>
        public static string Wrapper_SkippedAccessRequestListItem {
            get {
                return ResourceManager.GetString("Wrapper_SkippedAccessRequestListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app deployment has been skipped. The app already exists in the destination..
        /// </summary>
        public static string Wrapper_SkippedApp {
            get {
                return ResourceManager.GetString("Wrapper_SkippedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped restoring the AppData. The app already exists in the destination..
        /// </summary>
        public static string Wrapper_SkippedAppData {
            get {
                return ResourceManager.GetString("Wrapper_SkippedAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped restoring the item. It is not allowed to be edited in SharePoint..
        /// </summary>
        public static string Wrapper_SkippedByCannotEditItem {
            get {
                return ResourceManager.GetString("Wrapper_SkippedByCannotEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped restoring this item. An item that is the same as the source item already exists in the destination and this destination item is declared as a record..
        /// </summary>
        public static string Wrapper_SkippedByDeclaredDocument {
            get {
                return ResourceManager.GetString("Wrapper_SkippedByDeclaredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view is a personal view and was skipped..
        /// </summary>
        public static string Wrapper_SkippedByIsPersonalView {
            get {
                return ResourceManager.GetString("Wrapper_SkippedByIsPersonalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item was skipped because the &apos;Include list view&apos; checkbox was not selected..
        /// </summary>
        public static string Wrapper_SkippedByNotIncludeListView {
            get {
                return ResourceManager.GetString("Wrapper_SkippedByNotIncludeListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique field for this item conflicts with that in the destination. The restoration was skipped..
        /// </summary>
        public static string Wrapper_SkippedItemByHasUniqueValue {
            get {
                return ResourceManager.GetString("Wrapper_SkippedItemByHasUniqueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped this item rather than appended it to the destination. An item with the same ID that shares the same file name already exists in the destination..
        /// </summary>
        public static string Wrapper_SkippedItemByIsSameItem {
            get {
                return ResourceManager.GetString("Wrapper_SkippedItemByIsSameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was skipped because the Last Modified Time of the item in the destination is later than the item in backup..
        /// </summary>
        public static string Wrapper_SkippedItemByLastModifiedTime {
            get {
                return ResourceManager.GetString("Wrapper_SkippedItemByLastModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was skipped because the option to only restore security was selected..
        /// </summary>
        public static string Wrapper_SkippedItemByRestoreSecurityOnly {
            get {
                return ResourceManager.GetString("Wrapper_SkippedItemByRestoreSecurityOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was skipped because the version of the item in the destination is greater than the item in backup..
        /// </summary>
        public static string Wrapper_SkippedItemByTargetGtSourceVersion {
            get {
                return ResourceManager.GetString("Wrapper_SkippedItemByTargetGtSourceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item was skipped because it was associated with the workflow instance which this product does not support..
        /// </summary>
        public static string Wrapper_SkippedWorkflowTaskItem {
            get {
                return ResourceManager.GetString("Wrapper_SkippedWorkflowTaskItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list was skipped. It uses a SharePoint built-in hidden template..
        /// </summary>
        public static string Wrapper_SkipSpecialList {
            get {
                return ResourceManager.GetString("Wrapper_SkipSpecialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current list: {0} is within the site: {1}. DocAve Online does not have permission to access this list, because the Custom Script settings in the destination SharePoint Online may not be enabled. Please enable the destination Custom Script settings in SharePoint admin center &gt; settings. Then, run the job again..
        /// </summary>
        public static string Wrapper_SkipSpecialListsWhileOffice365CustomScriptDisabled {
            get {
                return ResourceManager.GetString("Wrapper_SkipSpecialListsWhileOffice365CustomScriptDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the term set that connects with a Metadata column. Term Group Name: {0}; Term Set Name: {1}.
        /// </summary>
        public static string Wrapper_TermSetNotFound {
            get {
                return ResourceManager.GetString("Wrapper_TermSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the user in the destination..
        /// </summary>
        public static string Wrapper_UserNotExist {
            get {
                return ResourceManager.GetString("Wrapper_UserNotExist", resourceCulture);
            }
        }
    }
}
