<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

  <ItemGroup>
    <Compile Update="Export\Export.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Export.resx</DependentUpon>
    </Compile>
    <Compile Update="Export\ExportForInternationalization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExportForInternationalization.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Export\Export.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Export.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Export\ExportForInternationalization.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ExportForInternationalization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Archiver\" />
  </ItemGroup>

</Project>
