/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Media.Storage.Resources.AzureI18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AzureI18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureI18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Media.Storage.Resources.AzureI18N.AzureI18N", typeof(AzureI18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point.
        /// </summary>
        public static string MediaStorage_Azure_Access_Point {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Access_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account key.
        /// </summary>
        public static string MediaStorage_Azure_Account_Key {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Account_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string MediaStorage_Azure_Account_Name {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MediaStorage_Azure_Account_Name_Demo {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Account_Name_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string MediaStorage_Azure_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDN enabled.
        /// </summary>
        public static string MediaStorage_Azure_CDN_Enabled {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_CDN_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the detailed information for the storage location..
        /// </summary>
        public static string MediaStorage_Azure_Configure_your_container_name_account_name_and_account_key {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Configure_your_container_name_account_name_and_account_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container name.
        /// </summary>
        public static string MediaStorage_Azure_Container_Name {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Container_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container names must be from 3 through 63 characters long..
        /// </summary>
        public static string MediaStorage_Azure_Container_names_must_be_from_3_through_63_characters_long {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Container_names_must_be_from_3_through_63_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container names must start with a letter or number, and can contain only lowercase letters, numbers, and the dash (-) character..
        /// </summary>
        public static string MediaStorage_Azure_Container_names_must_start_with_a_letter_or_number_and_can_contain_only_letters_numbers_and_the_dash_character {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Container_names_must_start_with_a_letter_or_number_and_can_con" +
                        "tain_only_letters_numbers_and_the_dash_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every dash (-) character must be immediately preceded and followed by a letter or number..
        /// </summary>
        public static string MediaStorage_Azure_Every_dash_character_must_be_immediately_preceded_and_followed_by_a_letter_or_number {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Every_dash_character_must_be_immediately_preceded_and_followed" +
                        "_by_a_letter_or_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        public static string MediaStorage_Azure_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string MediaStorage_Azure_GUID {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure Storage.
        /// </summary>
        public static string MediaStorage_Azure_Microsoft_Azure_Storage {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Microsoft_Azure_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string MediaStorage_Azure_Proxy {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host.
        /// </summary>
        public static string MediaStorage_Azure_Proxy_Host {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MediaStorage_Azure_Proxy_Password {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Proxy_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string MediaStorage_Azure_Proxy_Port {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MediaStorage_Azure_Proxy_Username {
            get {
                return ResourceManager.GetString("MediaStorage_Azure_Proxy_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Access_Point {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Access_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account key.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Account_Key {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Account_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Account_Name {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Advanced {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDN enabled.
        /// </summary>
        public static string MediaStorage_Connector_Azure_CDN_Enabled {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_CDN_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the detailed information for the storage location..
        /// </summary>
        public static string MediaStorage_Connector_Azure_Configure_your_container_name_account_name_and_account_key {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Configure_your_container_name_account_name_and_accou" +
                        "nt_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container name.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Container_Name {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Container_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container names must be from 3 through 63 characters long..
        /// </summary>
        public static string MediaStorage_Connector_Azure_Container_names_must_be_from_3_through_63_characters_long {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Container_names_must_be_from_3_through_63_characters" +
                        "_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container names must start with a letter or number, and can contain only lowercase letters, numbers, and the dash (-) character..
        /// </summary>
        public static string MediaStorage_Connector_Azure_Container_names_must_start_with_a_letter_or_number_and_can_contain_only_letters_numbers_and_the_dash_character {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Container_names_must_start_with_a_letter_or_number_a" +
                        "nd_can_contain_only_letters_numbers_and_the_dash_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every dash (-) character must be immediately preceded and followed by a letter or number..
        /// </summary>
        public static string MediaStorage_Connector_Azure_Every_dash_character_must_be_immediately_preceded_and_followed_by_a_letter_or_number {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Every_dash_character_must_be_immediately_preceded_an" +
                        "d_followed_by_a_letter_or_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended parameters.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Extended_Parameters {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Extended_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string MediaStorage_Connector_Azure_GUID {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure Storage.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Microsoft_Azure_Storage {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Microsoft_Azure_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an integer between 0 and 65535..
        /// </summary>
        public static string MediaStorage_Connector_Azure_Must_be_a_number_between_0_and_65535 {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Must_be_a_number_between_0_and_65535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Proxy {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Proxy_Host {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Proxy_Password {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Proxy_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Proxy_Port {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string MediaStorage_Connector_Azure_Proxy_Username {
            get {
                return ResourceManager.GetString("MediaStorage_Connector_Azure_Proxy_Username", resourceCulture);
            }
        }
    }
}
