<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MediaServiceApplicationModel</AssemblyName>
  </PropertyGroup>
<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
<ItemGroup>
  <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
  <PackageReference Include="log4net" Version="3.3.1" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Media.Common\Media.Common.csproj" />
    <ProjectReference Include="..\Media.Core.Index\Media.Core.Index.csproj" />
    <ProjectReference Include="..\Media.Core.IO\Media.Core.IO.csproj" />
  </ItemGroup>

</Project>
