<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>RAGoogleTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="log4net" Version="3.3.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RACommonUtility\RACommonUtility.csproj" />
        <ProjectReference Include="..\RACommon\RACommon.csproj" />
        <ProjectReference Include="..\RAContract\RAContract.csproj" />
        <ProjectReference Include="..\RADB\RADB.csproj" />
        <ProjectReference Include="..\RAService\RAService.csproj" />
        <ProjectReference Include="..\RMExternalSynchronize\RMSynchronize.csproj" />
	</ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <Content Include="Castle\ServiceCastle.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <SubType>Designer</SubType>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <Content Update="TimerLog4net.config">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
          <SubType>Designer</SubType>
        </Content>
    </ItemGroup>

</Project>
