/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudRecordDownloadManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudRecordDownloadManager.Properties.I18N", typeof(I18N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string key_0505679f_b4a8_41b2_8b69_414a6a91292e {
            get {
                return ResourceManager.GetString("key_0505679f_b4a8_41b2_8b69_414a6a91292e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string key_07462cc5_2685_4595_923a_9c4a71fd5364 {
            get {
                return ResourceManager.GetString("key_07462cc5_2685_4595_923a_9c4a71fd5364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Agent Installation Wizard.
        /// </summary>
        public static string key_090b97af_fb52_4a97_93b4_bfeb26dfaf83 {
            get {
                return ResourceManager.GetString("key_090b97af_fb52_4a97_93b4_bfeb26dfaf83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Agent Installation Package.
        /// </summary>
        public static string key_0c249c11_99eb_4c69_8759_3da320485e0f {
            get {
                return ResourceManager.GetString("key_0c249c11_99eb_4c69_8759_3da320485e0f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Agent.
        /// </summary>
        public static string key_0cf5afca_a5b2_4f91_b0c1_69b0d2ba1737 {
            get {
                return ResourceManager.GetString("key_0cf5afca_a5b2_4f91_b0c1_69b0d2ba1737", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Agent.
        /// </summary>
        public static string key_1df5afca_b6b2_4f91_b1d1_69b0d2ba1748 {
            get {
                return ResourceManager.GetString("key_1df5afca_b6b2_4f91_b1d1_69b0d2ba1748", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Agent Download Manager.
        /// </summary>
        public static string key_257e3086_b755_4a8d_a694_451b6ab02aa7 {
            get {
                return ResourceManager.GetString("key_257e3086_b755_4a8d_a694_451b6ab02aa7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Framework 4.7.2 or above is required..
        /// </summary>
        public static string key_38a3784d_9749_4635_8459_a5f5fb11ed87 {
            get {
                return ResourceManager.GetString("key_38a3784d_9749_4635_8459_a5f5fb11ed87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has not completed. Are you sure you want to exit?.
        /// </summary>
        public static string key_3e6b5d22_4b85_48aa_bb83_473eee71ff61 {
            get {
                return ResourceManager.GetString("key_3e6b5d22_4b85_48aa_bb83_473eee71ff61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Physical Memory.
        /// </summary>
        public static string key_42e3c7e5_ec8d_46f8_a367_292db9c1035d {
            get {
                return ResourceManager.GetString("key_42e3c7e5_ec8d_46f8_a367_292db9c1035d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string key_43da6143_df4e_4b0f_90dc_df418bd896ec {
            get {
                return ResourceManager.GetString("key_43da6143_df4e_4b0f_90dc_df418bd896ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites Check.
        /// </summary>
        public static string key_43f63948_5986_415b_9036_7b74ba2759b9 {
            get {
                return ResourceManager.GetString("key_43f63948_5986_415b_9036_7b74ba2759b9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string key_456a1568_4227_4e55_ad7c_87e0d4085535 {
            get {
                return ResourceManager.GetString("key_456a1568_4227_4e55_ad7c_87e0d4085535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Configuration.
        /// </summary>
        public static string key_51a906d9_7bad_4489_b99a_d4450dd177b4 {
            get {
                return ResourceManager.GetString("key_51a906d9_7bad_4489_b99a_d4450dd177b4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Location.
        /// </summary>
        public static string key_51c5bc50_e7f7_4309_8720_3f5d49a26e94 {
            get {
                return ResourceManager.GetString("key_51c5bc50_e7f7_4309_8720_3f5d49a26e94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        public static string key_55740329_a988_47c6_9c64_bab0aa27c7f8 {
            get {
                return ResourceManager.GetString("key_55740329_a988_47c6_9c64_bab0aa27c7f8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string key_569c0236_6a67_4bd3_a950_ed6b2cb3c668 {
            get {
                return ResourceManager.GetString("key_569c0236_6a67_4bd3_a950_ed6b2cb3c668", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms in the subscription agreement.
        /// </summary>
        public static string key_5c4f8e4d_bab8_48fa_8cc0_4311589f6cb7 {
            get {
                return ResourceManager.GetString("key_5c4f8e4d_bab8_48fa_8cc0_4311589f6cb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string key_5c9f2d7f_aa92_4332_bed1_9e9910dbcb92 {
            get {
                return ResourceManager.GetString("key_5c9f2d7f_aa92_4332_bed1_9e9910dbcb92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string key_6066fb46_a878_4d44_b3df_6c10942e8fda {
            get {
                return ResourceManager.GetString("key_6066fb46_a878_4d44_b3df_6c10942e8fda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while downloading the Agent installation package..
        /// </summary>
        public static string key_69a82598_134d_4ed3_830e_e2bb7baffc5a {
            get {
                return ResourceManager.GetString("key_69a82598_134d_4ed3_830e_e2bb7baffc5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Manager is used to download the AvePoint Opus installation package and pre-configure the required settings..
        /// </summary>
        public static string key_6ce3d6b2_2203_43c0_918b_ac9955e6ef40 {
            get {
                return ResourceManager.GetString("key_6ce3d6b2_2203_43c0_918b_ac9955e6ef40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} GB of disk space is required..
        /// </summary>
        public static string key_6f5a6290_b14d_4104_9061_a0a27b6e0209 {
            get {
                return ResourceManager.GetString("key_6f5a6290_b14d_4104_9061_a0a27b6e0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Disk Space.
        /// </summary>
        public static string key_721008dd_96c3_4819_a95b_aa3ac6041131 {
            get {
                return ResourceManager.GetString("key_721008dd_96c3_4819_a95b_aa3ac6041131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string key_7315adb9_0e80_42ec_9e98_f1b0a14ecf4d {
            get {
                return ResourceManager.GetString("key_7315adb9_0e80_42ec_9e98_f1b0a14ecf4d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Agent.
        /// </summary>
        public static string key_75584acc_6208_43b5_b8d9_8cfaab54f03e {
            get {
                return ResourceManager.GetString("key_75584acc_6208_43b5_b8d9_8cfaab54f03e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string key_75aaabed_5b63_4d43_a5a6_1b4dabab0693 {
            get {
                return ResourceManager.GetString("key_75aaabed_5b63_4d43_a5a6_1b4dabab0693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string key_76ee35c6_8e5d_44f0_b1ba_046cee19e6e7 {
            get {
                return ResourceManager.GetString("key_76ee35c6_8e5d_44f0_b1ba_046cee19e6e7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Agent has already been installed..
        /// </summary>
        public static string key_79c2e46a_a05b_4bc4_bc83_93b15799b650 {
            get {
                return ResourceManager.GetString("key_79c2e46a_a05b_4bc4_bc83_93b15799b650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string key_89b3350b_2410_4533_aa29_2700d5dfd2b2 {
            get {
                return ResourceManager.GetString("key_89b3350b_2410_4533_aa29_2700d5dfd2b2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string key_8b71ed7f_af35_4151_942c_7e1c756eda41 {
            get {
                return ResourceManager.GetString("key_8b71ed7f_af35_4151_942c_7e1c756eda41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network is not available..
        /// </summary>
        public static string key_8e2ebd87_931c_4d40_9571_52cdc408e63a {
            get {
                return ResourceManager.GetString("key_8e2ebd87_931c_4d40_9571_52cdc408e63a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} GB of physical memory is required..
        /// </summary>
        public static string key_8f862b95_5033_4680_9b5d_42a3309d052c {
            get {
                return ResourceManager.GetString("key_8f862b95_5033_4680_9b5d_42a3309d052c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the following subscription agreement carefully. To continue, you must accept the terms in this agreement..
        /// </summary>
        public static string key_a09a3188_857f_4d1e_93db_b96bc3f80d5b {
            get {
                return ResourceManager.GetString("key_a09a3188_857f_4d1e_93db_b96bc3f80d5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location to install the Agent..
        /// </summary>
        public static string key_a5ce2d83_e6a5_4aa6_9893_b4eab31ab9dd {
            get {
                return ResourceManager.GetString("key_a5ce2d83_e6a5_4aa6_9893_b4eab31ab9dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string key_aa23e68a_835e_47bb_8968_bc332fc96efa {
            get {
                return ResourceManager.GetString("key_aa23e68a_835e_47bb_8968_bc332fc96efa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string key_aa75fb0b_a805_4e77_a040_d753e2507b04 {
            get {
                return ResourceManager.GetString("key_aa75fb0b_a805_4e77_a040_d753e2507b04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string key_ac1166cf_e270_43dc_b0ff_a43b79ff1af2 {
            get {
                return ResourceManager.GetString("key_ac1166cf_e270_43dc_b0ff_a43b79ff1af2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation path &apos;{0}&apos; is invalid..
        /// </summary>
        public static string key_ac4d7b37_c3a5_4c16_913b_9e90d3656c7d {
            get {
                return ResourceManager.GetString("key_ac4d7b37_c3a5_4c16_913b_9e90d3656c7d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string key_af5c691d_cf4a_4b79_86cf_48adb076c4f6 {
            get {
                return ResourceManager.GetString("key_af5c691d_cf4a_4b79_86cf_48adb076c4f6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while updating the agent..
        /// </summary>
        public static string key_b53fb0e6_0645_408b_a7af_8318a40a35e2 {
            get {
                return ResourceManager.GetString("key_b53fb0e6_0645_408b_a7af_8318a40a35e2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string key_b864387b_ddff_483b_8c32_7c8c6fd03c22 {
            get {
                return ResourceManager.GetString("key_b864387b_ddff_483b_8c32_7c8c6fd03c22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string key_bc00875b_d1cd_47e1_8e6a_508c871a82ad {
            get {
                return ResourceManager.GetString("key_bc00875b_d1cd_47e1_8e6a_508c871a82ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Agreement.
        /// </summary>
        public static string key_c1963aed_33e6_4d1d_9a37_da1cb6776f17 {
            get {
                return ResourceManager.GetString("key_c1963aed_33e6_4d1d_9a37_da1cb6776f17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while installing the Agent..
        /// </summary>
        public static string key_c2479e85_f4bb_45d8_b64a_38aa761ce9bc {
            get {
                return ResourceManager.GetString("key_c2479e85_f4bb_45d8_b64a_38aa761ce9bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Agent to:.
        /// </summary>
        public static string key_c3402428_52ee_4a95_a4f3_da7693c8624d {
            get {
                return ResourceManager.GetString("key_c3402428_52ee_4a95_a4f3_da7693c8624d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string key_ccd03b9d_93d4_4b38_bb45_4390a76558db {
            get {
                return ResourceManager.GetString("key_ccd03b9d_93d4_4b38_bb45_4390a76558db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string key_d37c506f_791f_4037_ba5c_700f7330d38a {
            get {
                return ResourceManager.GetString("key_d37c506f_791f_4037_ba5c_700f7330d38a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string key_e1996ec7_ef33_4ab8_8998_e3935200db03 {
            get {
                return ResourceManager.GetString("key_e1996ec7_ef33_4ab8_8998_e3935200db03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        public static string key_f2d4f453_4434_4200_8525_4b839c30de2a {
            get {
                return ResourceManager.GetString("key_f2d4f453_4434_4200_8525_4b839c30de2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string key_f33a29d5_e169_46a5_8283_01adad651dc6 {
            get {
                return ResourceManager.GetString("key_f33a29d5_e169_46a5_8283_01adad651dc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string key_f43a31c4_bdcb_4a47_8bfa_12e1db8d3de3 {
            get {
                return ResourceManager.GetString("key_f43a31c4_bdcb_4a47_8bfa_12e1db8d3de3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string key_f71372ab_4a1e_40b1_b8b9_e8fd24ee856f {
            get {
                return ResourceManager.GetString("key_f71372ab_4a1e_40b1_b8b9_e8fd24ee856f", resourceCulture);
            }
        }
    }
}
