/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */

namespace AvePoint.Media.Storage.Egnyte
{
    #region
    using System;
    using System.Collections.Generic;
    using AvePoint.GCommon.Contract.CodeReview;
    #endregion

    #region CodeReview
    [AveCodeReview(
        "2013/10/16",
        "xiao.zhang@avepoint.com",
        "xiao.zhang@avepoint.com",
        new String[] { CodeReviewConstants.CHECK_LIST_ID_EH_2, CodeReviewConstants.CHECK_LIST_ID_BL_1, CodeReviewConstants.CHECK_LIST_ID_CS_2 },
        "ADO-93945",
        true,
        new String[] { CodeReviewConstants.CHECK_LIST_ID_EH_2, CodeReviewConstants.CHECK_LIST_ID_BL_1, CodeReviewConstants.CHECK_LIST_ID_CS_2 }
        )]
    #endregion

    class EgnyteObject
    {
        public Boolean Is_folder { get; set; }

        public String Name { get; set; }

        public String Folder_id { get; set; }

        public String Entry_id { get; set; }

        public String Checknum { get; set; }

        public String Last_modified { get; set; }

        public String Uploaded_by { get; set; }
        
        public Int64 Size { get; set; }

        public List<EgnyteObject> Files { get; set; }

        public List<EgnyteObject> Folders { get; set; }

        public List<EgnyteObject> Versions { get; set; }
    }

    class User
    {
        //An opaque, immutable, unique identifier for the user, generated by Egnyte. This identifier is used to refer to the user in all API calls
        public Int32 Id { get; set; }

        //The Egnyte username for the user.
        public String Name { get; set; }

        //This is an immutable unique identifier provided by the API consumer.
        public String Externalld { get; set; }

        //The email address of the user.
        public String Email { get; set; }

        //The last name of the user.
        public String FamilyName { get; set; }

        //The first name of the user.
        public String GivenName { get; set; }

        //Whether the user is active or inactive.
        public Boolean Active { get; set; }

        //If set to true when creating a user, an invitation email will be sent (if the user is created in active state)
        public Boolean SendInvite { get; set; }

        ///The authentication type for the user.
        //ad = Active Directory
        //sso = SAML SSO
        //egnyte = internal Egnyte
        public String AuthType { get; set; }

        //The Egnyte role of the user.
        //admin = Administrator
        //power = Power User
        //standard = Standard User
        public String UserType { get; set; }

        //(OPTIONAL) This is the way the user is identified within the SAML Response from an SSO Identity Provider, i.e. the SAML Subject. Only required if the user is SSO authenticated and not using default user mapping.
        public String IdpUserId { get; set; }

        //(OPTIONAL) Used to bind child authentication policies to a user when using Active Directory authentication in a multi-domain setup.
        public String UserPrincipalName { get; set; }

    }
    class EgnyteFileInfo : XFileInfo
    {
        EgnyteSystem system;
        EgnyteObject innerObject;
        List<XFileInfo> version = new List<XFileInfo>();
        public EgnyteFileInfo(String highName, String lowName, EgnyteSystem sys, EgnyteObject obj)
        {
            this.HighName = highName;
            this.LowName = lowName;
            this.system = sys;
            this.innerObject = obj;
            if (obj.Versions != null)
            {
                foreach (var egnyteObject in obj.Versions)
                {
                    version.Add(new EgnyteFileInfo(highName, lowName, sys, egnyteObject));
                }
            }
            if (!String.IsNullOrEmpty(obj.Last_modified))
            {
                this.LastWriteTimeUtc = DateTime.Parse(this.innerObject.Last_modified).ToUniversalTime();
            }
        }
        public override Int64 FileSize
        {
            get
            {
                return this.innerObject.Size;
            }
            set
            {
                this.FileSize = value;
            }
        }
        public override String Name
        {
            get
            {
                return this.LowName;
            }
        }
        public override Boolean Exists
        {
            get
            {
                return this.FileSize != -1;
            }
        }
        public override List<XFileInfo> Versions
        {
            get
            {
                return this.version;
            }
            set
            {
                this.Versions = value;
            }
        }
        public override String ObjectId
        {
            get
            {
                return this.innerObject.Entry_id;
            }
        }
    }
    class EgnyteFolderInfo : XDirectoryInfo
    {
        EgnyteObject innerObject;
        EgnyteSystem system;
        public EgnyteFolderInfo(String highName, String lowName, EgnyteSystem sys, EgnyteObject obj)
        {
            this.HighName = highName;
            this.LowName = lowName;
            this.system = sys;
            innerObject = obj;
            if (!String.IsNullOrEmpty(obj.Last_modified))
            {
                this.LastWriteTimeUtc = DateTime.Parse(this.innerObject.Last_modified).ToUniversalTime();
            }
        }
        public override string ClipId
        {
            get
            {
                return this.innerObject.Folder_id;
            }
            set
            {
                base.ClipId = value;
            }
        }
        public override String Name
        {
            get
            {
                return this.LowName.Trim(new Char[] { ' ', '\\', '/' });
            }
        }
        public override Boolean Exists
        {
            get
            {
                return true;
            }
        }

        public override bool IsEmpty
        {
            get { throw new NotSupportedException(); }
        }
    }
}
