/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */


using System;
using System.Collections.Generic;
using System.Text;
using System.Collections;

namespace AvePoint.Wrapper.Common
{
    public interface IAveExportSettings : IAveDeploymentSettings
    {
        AveIncludeVersions IncludeVersions { get; set; }
        //bool ExportPublicSchema { get; set; }
        //bool ExportFrontEndFileStreams { get; set; }
        AveExportMethodType ExportMethod { get; set; }
        bool ExcludeDependencies { get; set; }
        bool OverwriteExistingDataFile { get; set; }
        int FileMaxSize { get; set; }
        IAveExportObjectCollection ExportObjects { get; }
        ArrayList DataFiles { get; }

        void Validate();

        bool LogExportObjectsTable { set; get; }
        string ExportChangeToken { set; get; }
        bool ExportPublicSchema { get; set; }
        bool AutoGenerateDataFileName { set; get; }
    }

    public enum AveIncludeVersions
    {
        All = 4,
        CurrentVersion = 2,
        LastMajor = 1,
        LastMajorAndMinor = 3
    }

    public enum AveExportMethodType
    {
        ExportAll,
        ExportChanges
    }
}
