<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <RootNamespace>AvePoint.RA.I18N</RootNamespace>
    <AssemblyName>RevIMI18N</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\DocaveReference\DocAveStandard.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\RecordAutomation.fr-FR.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\RecordAutomation.ko-KR.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\RecordAutomation.zh-CN.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\RecordAutomation.en-US.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
	<EmbeddedResource Update="Resources\RecordAutomation.fr-CA.resx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		<SubType>Designer</SubType>
	</EmbeddedResource>
    <EmbeddedResource Update="Resources\RecordAutomation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <SubType>Designer</SubType>
      <LastGenOutput>RecordAutomation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\RecordAutomation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RecordAutomation.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>