<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AvePoint.RA.ArchiverMigration</RootNamespace>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RAArchiverMaintenance\RAArchiverMaintenance.csproj" />
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
    <ProjectReference Include="..\RACommonUtility\RACommonUtility.csproj" />
    <ProjectReference Include="..\RADB\RADB.csproj" />
    <ProjectReference Include="..\RAService\RAService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="Cloud.Sdk.Dao" Version="5.2.22" />
    <PackageReference Include="Cloud.sdk.Data.Opus" Version="5.10.26" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ArchiverMigration\JobStage\automapper.lic" />
  </ItemGroup>

</Project>
