/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */



using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using AvePoint.GCommon.Contract.CentralAdmin.Object;
using AvePoint.GCommon.Contract.Common;
using AvePoint.GCommon.Contract.Server.Common;
using AvePoint.GCommon.Contract.Server.Common.Profile.Object;
using AvePoint.GCommon.Contract.Server.ControlPanel.Cryptography;
using AvePoint.GCommon.Contract.Server.ControlPanel.ManagedAccount.Object;
using AvePoint.GCommon.Contract.Server.ControlPanel.AgentProxy;
using AvePoint.GCommon.Contract.Server.ControlPanel.UpdateManager.Object;

namespace AvePoint.GCommon.Contract.Server.ControlPanel.Object
{
    [DataContract(Namespace = ContractConstants.Namespace)]
    public class RegisterResult
    {
        /// <summary>
        /// customer issue id
        /// </summary>
        [DataMember]
        public string CIID { get; set; }

        /// <summary>
        /// service id
        /// </summary>
        [DataMember]
        public string ServiceID { get; set; }

        /// <summary>
        /// 用于加密DTO中的密码
        /// </summary>
        [DataMember]
        public byte[] CommunicationEncryptionKey { get; set; }

        /// <summary>
        /// 用于加密DTO中的密码
        /// </summary>
        [DataMember]
        public DataEncryptionProfile EncryptionProfile { get; set; }

        [DataMember]
        public bool IsSucceed { get; set; }

        [DataMember]
        public FailedReason FailedReason { get; set; }

        [DataMember]
        public List<FarmBaseInfo> FarmInfos { get; set; }

        /// <summary>
        ///  用于初始化CryptographyManagement中的CryptoMode
        ///  0:NoneFIPS ,1:FIPS
        /// </summary>
        [DataMember]
        public int CryptoMode { get; set; }

        /// <summary>
        /// 用于比较AccountProfile的Password是否有过改动
        /// </summary>
        [DataMember]
        public string AllAccountProfilePwdCrc { get; set; }

        public override String ToString()
        {
            return String.Format("Register result: is succeed:{0}, failed reason:{1}. Crypto mode:{2}, service id:{3}",
                this.IsSucceed,
                this.FailedReason,
                this.CryptoMode,
                this.ServiceID);
        }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class FarmBaseInfo
    {
        [DataMember]
        public string AgentName { get; set; }

        [DataMember]
        public string AgentAddress { get; set; }

        [DataMember]
        public string FarmName { get; set; }

        [DataMember]
        public string FarmID { get; set; }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    [Flags]
    public enum FailedReason
    {
        [EnumMember]
        None = 1 << 0,

        [EnumMember]
        FarmInfoIncorrect = 1 << 1,

        [EnumMember]
        OEMProductTypeMismatched = 1 << 2,
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class ServiceDto
    {
        /// <summary>
        /// Generated by GUID.
        /// </summary>
        [DataMember]
        public string Id { get; set; }

        /// <summary>
        /// service host name
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Schema { get; set; }

        /// <summary>
        /// service ip
        /// </summary>
        [DataMember]
        public string Address { get; set; }

        /// <summary>
        /// service control port
        /// </summary>
        [DataMember]
        public int Port { get; set; }

        /// <summary>
        /// service data port
        /// </summary>
        [DataMember]
        public int DataPort { get; set; }

        /// <summary>
        ///
        /// </summary>
        [DataMember]
        public string AgentType { get; set; }

        [DataMember]
        public string Domain { get; set; }

        [DataMember]
        public string UserName { get; set; }

        [DataMember]
        public string Password { get; set; }

        [DataMember]
        public byte[] Passphrase { get; set; }

        /// <summary>
        /// service version,  6.1 Alpha, 6.2 etc.
        /// </summary>
        [DataMember]
        public string Version { get; set; } //docave version 6.*.*.*

        /// <summary>
        /// version for display
        /// DocAve : 6.*.*.*
        /// NetApp : 7.*.*.*
        /// </summary>
        [DataMember]
        public string DisplayVersion { get; set; }

        [DataMember]
        public int SPVersion { get; set; } //0--unknown, 1---2003, 2---2007, 4---2010

        [DataMember]
        public int MossOrWss { get; set; }//0--unknown, 1--wss, 2--moss

        [DataMember]
        public string FarmName { get; set; }

        [DataMember]
        public string FarmId { get; set; }

        /// <summary>
        /// log level.
        /// </summary>
        [DataMember]
        [Obsolete("该属性不再提倡使用，请用LogSetting")]
        public int LogLevel { get; set; }

        [DataMember]
        public LogSetting LogSetting { get; set; }

        [DataMember]
        public string ExtraInfo { get; set; }

        //Notes: DataMembers below are used by Manager only

        /// <summary>
        /// service state
        /// </summary>
        [DataMember]
        [Obsolete("该属性不再提倡使用，请用Mode")]
        public ServiceState State { get; set; }

        /// <summary>
        /// service state
        /// </summary>
        [DataMember]
        public ServiceState Mode { get; set; }

        /// <summary>
        /// UTC time.
        /// </summary>
        [DataMember]
        public long RegisterTime { get; set; }

        [DataMember]
        public long LastStartTime { get; set; }

        [DataMember]
        public long LastStopTime { get; set; }

        [DataMember]
        [Obsolete("该属性不再提倡使用，请用LoadBalanceFactor")]
        public double LoadBanlanceFactor { get; set; }

        [DataMember]
        public string Properties { get; set; }

        [DataMember]
        public ServiceActive Status { get; set; }

        [DataMember]
        [Obsolete("该属性不再提倡使用，请用Status")]
        public ServiceActive Active { get; set; }

        /// <summary>
        /// Media Service
        /// SP Agent Service
        /// Report Service
        /// </summary>
        [DataMember]
        public string ServiceName { get; set; }

        [DataMember]
        public int EmailStatus { get; set; }

        /// <summary>
        ///
        /// </summary>
        [DataMember]
        public string TimeZoneId { get; set; }

        [DataMember]
        public int Mismatched { get; set; }

        [DataMember]
        public string CacheInfo { get; set; }

        [DataMember]
        public CacheSettingDto CacheSetting { get; set; }

        [DataMember]
        public ProxyType ProxyType { get; set; }

        public override string ToString()
        {
            string username;
            if (Domain!=null)
            {
                username = string.Format("{0}\\{1}", Domain, UserName);
            }
            else
            {
                username = UserName;
            }
            return string.Format("Name:{0}, Address:{1}, Port:{2}, AgentType:{3}, SPVersion:{4}, MossOrWss:{5}, FarmName:{6}, FarmId:{7}, EnvironmentInfo:{8}, RoleInFarm:{9}, OEMType:{10}, ProductVersion:{11}, DisplayVersion:{12}, Username:{13}, FarmServerCount: {14}",
                Name, Address, Port, AgentType, SPVersion, MossOrWss, FarmName, FarmId, EnvironmentInfo, RoleInFarm, OEMProductType.ToString(), Version, DisplayVersion, username, FarmServiceDto ?? null);
        }

        [DataMember]
        public ServiceType Type { get; set; }

        [DataMember]
        [Obsolete("该属性不再提倡使用，请用Address")]
        public string Host { get; set; }

        [DataMember]
        public string LocalTempBuffer { get; set; }

        [DataMember]
        public double LoadBalanceFactor { get; set; }

        [DataMember]
        public string Extension { get; set; }

        [DataMember]
        public int CpuNumber { get; set; }

        [DataMember]
        public long CpuHz { get; set; }

        /// <summary>
        /// 限制agent跑job的个数
        /// </summary>
        [DataMember]
        public int JobRestrictCount { get; set; }

        [DataMember]
        public bool IsJobRestrictChecked { get; set; }

        /// <summary>
        /// agent链接office365时需要的信息
        /// </summary>
        [DataMember]
        public BposInfo BposInfo { get; set; }

        /// <summary>
        /// 控制agent选择api类型的参数
        /// </summary>
        [DataMember]
        public ApiObjectModelType ApiObjectModelType { get; set; }

        /// <summary>
        /// 根据agent type计算出的所有模块列表(AgentGroup功能使用)
        /// </summary>
        [DataMember]
        public Dictionary<string, List<string>> ModuleMap { get; set; }

        /// <summary>
        /// 根据agent type计算出的所有模块列表(AgentGroup功能使用)
        /// </summary>
        [DataMember]
        public Dictionary<string, List<string>> BposModuleMap { get; set; }

        /// <summary>
        /// 根据agent type计算此agent拥有的所有模块列表(AgentMonitor功能使用)
        /// </summary>
        [DataMember]
        public List<ModuleTypeDto> ModuleTypeList { get; set; }

        /// <summary>
        /// 根据agent type计算此bpos agent拥有的所有模块列表(AgentMonitor功能使用)
        /// </summary>
        [DataMember]
        public List<ModuleTypeDto> BposModuleTypeList { get; set; }

        /// <summary>
        /// 所有可用模块，用分号分隔
        /// </summary>
        [DataMember]
        public string AvailableModuleStr { get; set; }

        /// <summary>
        /// Service的环境信息
        /// </summary>
        [DataMember]
        public string EnvironmentInfo { get; set; }

        [DataMember]
        public long SharePointTime { get; set; }

        /// <summary>
        /// SO Extender 使用RoleInFarm来判断Agent的属性(如CA、SQL等)
        /// </summary>
        [DataMember]
        public FarmRoles RoleInFarm { get; set; }

        [DataMember]
        public LicenseStatus LicenseStatus { get; set; }
        /// <summary>
        /// 为Update Manager功能提供显示服务信息的属性
        /// </summary>
        [DataMember]
        public string DisplayName { get; set; }

        /// <summary>
        /// 为Update Manager功能提供Install的进度
        /// </summary>
        [DataMember]
        public int InstallProgress { get; set; }

        /// <summary>
        /// 为Update Manager功能提供Install的状态
        /// </summary>
        [DataMember]
        public InstallStatus InstallStatus { get; set; }

        /// <summary>
        /// 为Update Manager功能提供正在安装Patch的名字
        /// </summary>
        [DataMember]
        public string InstallingPatchName { get; set; }

        [DataMember]
        public InstallStatusHistory UpdateStatusForDisplayService { get; set; }

        [DataMember]
        public List<UpdateHistoryDto> InstalledUpdateHistory { get; set; }

        [DataMember]
        public ServiceUpdateStatusDto InstalledMessage { get; set; }

        [DataMember]
        public List<ProfileDto> Profiles { get; set; }

        [DataMember]
        public FarmServiceDto FarmServiceDto { get; set; }

        [DataMember]
        public int OEMProductType { get; set; }

        [DataMember]
        public List<string> DotNetVersions { get; set; }  

        [DataMember]
        public string AccountProfileId { get; set; }

        [DataMember]
        public AccountProfileDto AccountProfile { get; set; }

        [DataMember]
        public string DependGAProductVersion { get; set; }

        [DataMember]
        public string DependGADisplayVersion { get; set; }

        [DataMember]
        public string DependGAConnectionInfo { get; set; }

        public ServiceDto()
        {
            DotNetVersions = new List<string>();
        }

        public void Init()
        {
            long now = DateTime.UtcNow.Ticks;
            Status = ServiceActive.ACTIVE;
            RegisterTime = now;
            LastStartTime = now;
        }

        public bool IsActive()
        {
            return Status == ServiceActive.ACTIVE && Mode == ServiceState.UP;
        }

        public bool Is2013O365Supported()
        {
            bool result = false;
            bool found = false;
            if (DotNetVersions != null)
            {
                foreach (var item in DotNetVersions)
                {
                    if (item.StartsWith("4.0.30319", StringComparison.OrdinalIgnoreCase))
                    {
                        result = true;
                        break;
                    }
                }
                if (!found)
                {
                    if (DotNetVersions.Count > 0)
                    {
                        DotNetVersions.Sort();
                        string newVersion = DotNetVersions[DotNetVersions.Count - 1];
                        if (string.Compare(newVersion, "4.0.30319", StringComparison.OrdinalIgnoreCase) > 0)
                        {
                            result = true;
                        }
                    }
                }
            }
            return result;
        }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum LicenseStatus
    {
        [EnumMember]
        Allow = 0,

        [EnumMember]
        Deny = 1,
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class LogSetting
    {
        /// <summary>
        /// log level;
        /// DEBUG   -- 30000
        /// INFO    -- 40000
        /// WARNING -- 60000
        /// ERROR   -- 70000
        /// </summary>
        [DataMember]
        public int LogLevel { get; set; }

        /// <summary>
        /// log file size;
        /// MB
        /// </summary>
        [DataMember]
        public int LogFileSize { get; set; }

        [DataMember]
        public int LogFileCount { get; set; }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class AgentConfigInfo
    {
        [DataMember]
        public string Username { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Domain { get; set; }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum ServiceType
    {
        [EnumMember]
        SERVICE_TYPE_SP_AGENT = 0, //SharePoint Agent
        [EnumMember]
        SERVICE_TYPE_BPOS_AGENT = 1, //BPOS Agent
        [EnumMember]
        SERVICE_TYPE_MEDIA = 2, //Media
        [EnumMember]
        SERVICE_TYPE_REPORT = 3, //Report
        [EnumMember]
        SERVICE_TYPE_WEB = 4, //Web
        [EnumMember]
        SERVICE_GOVERNANCE_AUTOMATION = 5, //GA+
    }

    /// <summary>
    /// SO Extender 使用FarmRoles来Agent是否为CA或SQL等
    /// </summary>
    [DataContract(Namespace = ContractConstants.Namespace)]
    [Flags]
    public enum FarmRoles
    {
        [EnumMember]
        UNKNOWN = -1,
        [EnumMember]
        NONE = 0,
        [EnumMember]
        FAILED = 1,       //1
        [EnumMember]
        CA = 2,           //10
        [EnumMember]
        WFE = 4,          //100
        [EnumMember]
        FAST = 8,         //1000
        [EnumMember]
        SQL = 16,         //10000
        [EnumMember]
        SPSERVER = 32,    //100000
        [EnumMember]
        NOTES = 64,       //1000000
        [EnumMember]
        EROOM = 128,      //10000000
        [EnumMember]
        SEARCH = 256,     //100000000 ,SharePoint Server Search
        [EnumMember]
        JSHARP = 512,     //1000000000 ,J# 2.0 for Livelink migration
        [EnumMember]
        DFC = 1024,       //10000000000 ,Documentum Foundation Class for Documentum migration
        [EnumMember]
        QuickPlace = 2048,//100000000000 ,QuickPlace Foundation Class for QuickPlace migration
        [EnumMember]
        SPFARM = 4096,    //1000000000000 ,SharePoint Farm is online
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum AgentControlOperations
    {
        [EnumMember]
        RESTRAT = 0,
        [EnumMember]
        DISABLE = 1,
        [EnumMember]
        ENABLE = 2,
        [EnumMember]
        DELETE = 3,
        [EnumMember]
        UNINSTALL = 4
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum ServiceState
    {
        [EnumMember]
        UP = 0,
        [EnumMember]
        DOWN = 1,
        [EnumMember]
        UNINSTALL = 2,
        [EnumMember]
        DISABLE = 3,
        [EnumMember]
        INVALID = 4,
        [EnumMember]
        MISMATCHED = 5,
        [EnumMember]
        STANDBY = 6,
        [EnumMember]
        WAITING = 7,
        [EnumMember]
        UPGRADING = 8,
        [EnumMember]
        ENVMISMATCHED = 9
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum ServiceActive
    {
        [EnumMember]
        ACTIVE = 0,
        [EnumMember]
        DOWN = 1,
        [EnumMember]
        RESTARTING = 2
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class DeletionRiskDto
    {
        [DataMember]
        public DeletionRiskType DeletionRiskType { get; set; }

        [DataMember]
        public ServiceDto Agent { get; set; }

        [DataMember]
        public List<string> GroupNames { get; set; }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum DeletionRiskType
    {
        [EnumMember]
        Normal = 0,

        [EnumMember]
        LastInFarm = 1,

        [EnumMember]
        InUse = 2,

        [EnumMember]
        DefaultGroupMissing = 3
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public class AgentQueryDto
    {
        [DataMember]
        public string AgentId { get { return mAgentId; } set { mAgentId = value; IsAgentIdAssigned = true; } }
        [DataMember]
        public string AgentName { get { return mAgentName; } set { mAgentName = value; IsAgentNameAssigned = true; } }
        [DataMember]
        public string AgentAddress { get { return mAgentAddress; } set { mAgentAddress = value; IsAgentAddressAssigned = true; } }
        [DataMember]
        public string FarmId { get { return mFarmId; } set { mFarmId = value; IsFarmIdAssigned = true; } }
        [DataMember]
        public int Active { get { return mActive; } set { mActive = value; IsActiveAssigned = true; } }
        [DataMember]
        public int State { get { return mState; } set { mState = value; IsStateAssigned = true; } }
        [DataMember]
        public ServiceType Type { get { return mType; } set { mType = value; IsTypeAssigned = true; } }

        private string mAgentId;
        private string mAgentName;
        private string mAgentAddress;
        private string mFarmId;
        private int mActive;
        private int mState;
        private ServiceType mType;

        [DataMember]
        public bool IsAgentIdAssigned { get; set; }
        [DataMember]
        public bool IsAgentNameAssigned { get; set; }
        [DataMember]
        public bool IsAgentAddressAssigned { get; set; }
        [DataMember]
        public bool IsFarmIdAssigned { get; set; }
        [DataMember]
        public bool IsActiveAssigned { get; set; }
        [DataMember]
        public bool IsStateAssigned { get; set; }
        [DataMember]
        public bool IsTypeAssigned { get; set; }
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum ValidateResult
    {
        [EnumMember]
        None = 0,

        [EnumMember]
        Success = 1,

        [EnumMember]
        ConnectionError = 2,

        [EnumMember]
        FarmInfoError = 4,

        [EnumMember]
        Exception = 8,
    }

    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum AgentTypeEnum
    {
        [EnumMember]
        OnPromise = 0,
        [EnumMember]
        Office365 = 1,
    }

    /// <summary>
    /// ASUP 打log用
    /// Agent Register、Start or Stop
    /// </summary>
    [DataContract(Namespace = ContractConstants.Namespace)]
    public enum AgentActionEnum
    {
        [EnumMember]
        AgentRegister = 0,
        [EnumMember]
        AgentStart = 1,
        [EnumMember]
        AgentStop = 2,
    }
}