/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Wrapper.Resource.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AveObjectModel_CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AveObjectModel_CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Wrapper.Resource.Client.AveObjectModel.CommonResource", typeof(AveObjectModel_CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running restoring navigation node Web:{0}.Error Message:{1}.
        /// </summary>
        public static string AveNavigationImportRunError {
            get {
                return ResourceManager.GetString("AveNavigationImportRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while building navigation tree :{0} ,Web:{1} .Error Message:{2}.
        /// </summary>
        public static string BuildNavNodesTreeError {
            get {
                return ResourceManager.GetString("BuildNavNodesTreeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildNavNodesTreeErrorSerializer: An error occurred while building navigation tree: {0},Web:{1} .Error Message:{2}.
        /// </summary>
        public static string BuildNavNodesTreeErrorSerializer {
            get {
                return ResourceManager.GetString("BuildNavNodesTreeErrorSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting navigation nodes,Web:{0}.Error Message:{1}.
        /// </summary>
        public static string ClearAllNavNodesError {
            get {
                return ResourceManager.GetString("ClearAllNavNodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting navigation node:{0},Web:{1}.Error Message:{2}.
        /// </summary>
        public static string DeleteNavNodeError {
            get {
                return ResourceManager.GetString("DeleteNavNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting item{0} from recycle bin,SiteCollection:{1}.Error Message:{2}.
        /// </summary>
        public static string DeleteObjectFromRecycleBinError {
            get {
                return ResourceManager.GetString("DeleteObjectFromRecycleBinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting items from recyclebin,SiteCollection{0}.Error Message:{1}.
        /// </summary>
        public static string DeleteObjectsFromRecycleBinError {
            get {
                return ResourceManager.GetString("DeleteObjectsFromRecycleBinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  An error occurred while GetDisplayFields List:{0}.Web:{1}.Error Message:{2}.
        /// </summary>
        public static string GetDisplayFieldsError {
            get {
                return ResourceManager.GetString("GetDisplayFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseViewFieldsString:An error occurred while GetDisplayFields.List:{0}.Web:{1}.Error Message:{2}.
        /// </summary>
        public static string GetDisplayFieldsErrorWithSchemaString {
            get {
                return ResourceManager.GetString("GetDisplayFieldsErrorWithSchemaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting field info ,List:{0},Web:{1}.Error Message:{2}.
        /// </summary>
        public static string GetFieldInfoObjectError {
            get {
                return ResourceManager.GetString("GetFieldInfoObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting content type tree.ContentType:{0},List:{1},Web{2}. Error Message:{3}.
        /// </summary>
        public static string GetParentContentTypeInfoTreeError {
            get {
                return ResourceManager.GetString("GetParentContentTypeInfoTreeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting field{0},Item{1}. Error Message:{2}.
        /// </summary>
        public static string GetUserDataError {
            get {
                return ResourceManager.GetString("GetUserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting user data junction.Field:{0}, FieldValue:{1},Item:{2}.Error Message:{3}.
        /// </summary>
        public static string GetUserDataJunctionError {
            get {
                return ResourceManager.GetString("GetUserDataJunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing feature:{0},Web{1}.Error Message:{2}.
        /// </summary>
        public static string RemoveFeatureError {
            get {
                return ResourceManager.GetString("RemoveFeatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force:An error occurred while removing feature:{0},Web{1}. Error Message:{2}.
        /// </summary>
        public static string RemoveFeatureErrorForce {
            get {
                return ResourceManager.GetString("RemoveFeatureErrorForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring navigation node{0},Web:{1}.Error Message:{2}.
        /// </summary>
        public static string RestoreNavigationNodeError {
            get {
                return ResourceManager.GetString("RestoreNavigationNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while restoring item :{0} from recycle bin,SiteCollection:{1}.Error Message:{2}.
        /// </summary>
        public static string RestoreObjectFromRecycleBinError {
            get {
                return ResourceManager.GetString("RestoreObjectFromRecycleBinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom:An error occurred while setting web master page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetCustomWebMasterPageInfoError {
            get {
                return ResourceManager.GetString("SetCustomWebMasterPageInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while SetNeedSetNullFields.List:{0},Web:{1} .Error Message:{2}.
        /// </summary>
        public static string SetNeedSetNullFieldsError {
            get {
                return ResourceManager.GetString("SetNeedSetNullFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting web master page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetWebMasterPageInfoError {
            get {
                return ResourceManager.GetString("SetWebMasterPageInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotImplement:An error occurred while setting web master page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetWebMasterPageInfoError_GetPublishWebFailed {
            get {
                return ResourceManager.GetString("SetWebMasterPageInfoError_GetPublishWebFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestExisting: An error occurred while setting web master page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetWebMasterPageInfoErrorDestExisting {
            get {
                return ResourceManager.GetString("SetWebMasterPageInfoErrorDestExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithoutInheriting:An error occurred while setting web master page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetWebMasterPageInfoErrorWithoutInheriting {
            get {
                return ResourceManager.GetString("SetWebMasterPageInfoErrorWithoutInheriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting welcome page:{0}.Error Message:{1}.
        /// </summary>
        public static string SetWelcomPageError {
            get {
                return ResourceManager.GetString("SetWelcomPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trans listId to Title: {0} ,Web:{1} .Error Message:{2}.
        /// </summary>
        public static string TransListIdToTitleError {
            get {
                return ResourceManager.GetString("TransListIdToTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing:An error occurred while updating navigation node{0},Web:{1}.Error Message:{2}.
        /// </summary>
        public static string UpdateNavigationNodeErrorExisting {
            get {
                return ResourceManager.GetString("UpdateNavigationNodeErrorExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewCreate:An error occurred while updating navigation node{0},Web:{1}.Error Message:{2}.
        /// </summary>
        public static string UpdateNavigationNodeErrorNewCreate {
            get {
                return ResourceManager.GetString("UpdateNavigationNodeErrorNewCreate", resourceCulture);
            }
        }
    }
}
