/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Wrapper.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AveSPResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AveSPResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Wrapper.Resource.ResourceFile.AveSPResourceFile", typeof(AveSPResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Columns.
        /// </summary>
        public static string CustomColumnsGroup {
            get {
                return ResourceManager.GetString("CustomColumnsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people contribute permissions to the SharePoint site: {0}.
        /// </summary>
        public static string DefaultMemberGroupDescription {
            get {
                return ResourceManager.GetString("DefaultMemberGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people contribute permissions to the SharePoint site: &lt;a href=&apos;{1}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string DefaultMemberGroupDescriptionRichText {
            get {
                return ResourceManager.GetString("DefaultMemberGroupDescriptionRichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Members.
        /// </summary>
        public static string DefaultMemberGroupName {
            get {
                return ResourceManager.GetString("DefaultMemberGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people full control permissions to the SharePoint site: {0}.
        /// </summary>
        public static string DefaultOwnerGroupDescription {
            get {
                return ResourceManager.GetString("DefaultOwnerGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people full control permissions to the SharePoint site: &lt;a href=&apos;{1}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string DefaultOwnerGroupDescriptionRichText {
            get {
                return ResourceManager.GetString("DefaultOwnerGroupDescriptionRichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Owners.
        /// </summary>
        public static string DefaultOwnerGroupName {
            get {
                return ResourceManager.GetString("DefaultOwnerGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people read permissions to the SharePoint site: {0}.
        /// </summary>
        public static string DefaultVisitorGroupDescription {
            get {
                return ResourceManager.GetString("DefaultVisitorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this group to grant people read permissions to the SharePoint site: &lt;a href=&apos;{1}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string DefaultVisitorGroupDescriptionRichText {
            get {
                return ResourceManager.GetString("DefaultVisitorGroupDescriptionRichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Visitors.
        /// </summary>
        public static string DefaultVisitorGroupName {
            get {
                return ResourceManager.GetString("DefaultVisitorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection.
        /// </summary>
        public static string SiteCollectionGroupPrefix {
            get {
                return ResourceManager.GetString("SiteCollectionGroupPrefix", resourceCulture);
            }
        }
    }
}
