/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
using System.Reflection;
using AvePoint.GCommon;
using AvePoint.GCommon.Contract.CommonFilter;
using RAExportCommon.VEOExportV2;

namespace RAExportCommon
{
    public class RecordVEODataV3
    {
        private static AveLogger mLog = AveLogger.GetInstance(MethodBase.GetCurrentMethod()?.DeclaringType);
        private static VEOContentXML? _contentVEOXML;
        private static VEOHistoryXML? _historyVEOXML;
        private RecordVEOParametersV3 _contentParams;

        public RecordVEODataV3()
        {
        }

        public static RecordVEOClassV3.VEOContent InitVEOContent(VEOContentXML contentVEOXML)
        {
            _contentVEOXML = contentVEOXML;
            return new RecordVEOClassV3.VEOContent
            {
                HashFunctionAlgorithm = VEOV3CommonString.ALGORITHM_SHA512,
                InformationObject = []
            };
        }

        public static RecordVEOClassV3.VEOHistory InitVEOHistory(VEOHistoryXML historyVEOXML)
        {
            _historyVEOXML = historyVEOXML;
            return new RecordVEOClassV3.VEOHistory();
        }

        public void GenerateVEOHistory(ref RecordVEOClassV3.VEOHistory mVEOHistory)
        {
            if (_historyVEOXML != null && _historyVEOXML.M1 != null)
            {
                foreach (var M3 in _historyVEOXML.M1.M3)
                {
                    var mEvent = new RecordVEOClassV3.Event
                    {
                        EventDateTime = M3.M4?.DefaultValue?.Equals("@TimeNow@", StringComparison.OrdinalIgnoreCase) == true ? DateTime.Now.ToString(VEOV3CommonString.FORMAT_DATETIME_V3) : M3.M4?.DefaultValue,
                        EventType = M3.M5?.DefaultValue,
                        Initiator = M3.M6?.DefaultValue,
                        Description = VEOV3CommonMethod.FilteredValidValue(M3.M23?.Where(d => d.DefaultValue.IsNotNullOrEmpty()).Select(d => d.DefaultValue).ToList()),
                        Error = VEOV3CommonMethod.FilteredValidValue(M3.M7?.Where(d => d.DefaultValue.IsNotNullOrEmpty()).Select(d => d.DefaultValue).ToList()),
                    };

                    (mVEOHistory.Event ??= []).Add(VEOV3CommonMethod.FilteredValidValue(mEvent));
                }
            }
        }

        /// <summary>
        /// VEOSignature V3 is generated by VEOHistory or VEOContent file.
        /// </summary>
        /// <returns></returns>
        public void GenerateVEOSignature(ref RecordVEOClassV3.SignatureBlock mSignatureBlock, MemoryStream memoryStream)
        {
            mSignatureBlock.Version = VEOV3CommonString.VEO_VERSION;
            mSignatureBlock.SignatureAlgorithm = VEOV3CommonString.ALGORITHMID_SHA512WITHRSA;
            mSignatureBlock.SignatureDateTime = VEOV3CommonString.FORMAT_DATETIME_V3;
            mSignatureBlock.Signer = VEOCommonString.SIGNER;

            byte[] result = SHA512WithRSASignature.Signature(memoryStream.ToArray());
            mSignatureBlock.Signature = VEOV3CommonMethod.AddValueNewLine(Convert.ToBase64String(result));
            mSignatureBlock.CertificateChain = new string[1];
            mSignatureBlock.CertificateChain[0] = VEOV3CommonMethod.AddValueNewLine(Convert.ToBase64String(AveCertificateOperation.ExportCertificateWithCertFormat()));
        }

        public void AddInformationObjectBlock(ref RecordVEOClassV3.VEOContent vEOContentObj, RecordVEOParametersV3 vParams)
        {
            if (_contentVEOXML == null) return;
            _contentParams = vParams;
            RecordVEO_M1_VEOContent M1 = _contentVEOXML.M1;
            if (M1 == null) return;
            foreach (var M4 in M1.M4)
            {
                var informationObject = new RecordVEOClassV3.InformationObject();
                informationObject.InformationObjectType = vParams.VIOType;
                informationObject.InformationObjectDepth = vParams.VIODepth;

                AddMetadataPackageBlock(ref informationObject, M4);

                if (vParams.HasIP)
                {
                    AddInformationPieceBlock(ref informationObject, M4);
                }

                (vEOContentObj.InformationObject ??= []).Add(informationObject);
            }
        }

        private void AddMetadataPackageBlock(ref RecordVEOClassV3.InformationObject mInformationObject, RecordVEO_M4_InfomationObject M4)
        {
            foreach (var M7 in M4.M7)
            {
                var metadataPackage = new RecordVEOClassV3.MetadataPackage();
                metadataPackage.MetadataSchemaIdentifier = "http://prov.vic.gov.au/vers/schema/ANZS5478";
                metadataPackage.MetadataSyntaxIdentifier = "http://www.w3.org/1999/02/22-rdf-syntax-ns";

                AddRDFBlock(ref metadataPackage, M7);

                (mInformationObject.MetadataPackage ??= []).Add(metadataPackage);
            }
        }

        private void AddRDFBlock(ref RecordVEOClassV3.MetadataPackage mMetadataPackage, RecordVEO_M7_MetadataPackage M7)
        {
            foreach (var M10 in M7.M10)
            {
                var rdf = new RecordVEOClassV3.RDF();
                AddRDFDescriptionBlock(ref rdf, M10);

                (mMetadataPackage.RDF ??= []).Add(rdf);
            }
        }

        private void AddRDFDescriptionBlock(ref RecordVEOClassV3.RDF rdf, RecordVEO_M10_RDF M10)
        {
            foreach (var M90 in M10.M90)
            {
                var description = new RecordVEOClassV3.AnzsDescription
                {
                    about = _contentParams.VUrl
                };

                AddRDFRecordBlock(ref description, M90);
                rdf.Xmlns = VEOV3CommonMethod.AddXMLNS(RDFTemplate.Record);
                (rdf.AnzsDescription ??= []).Add(description);
            }
        }

        public void AddRDFRecordBlock(ref RecordVEOClassV3.AnzsDescription description, RecordVEO_M90_RDFDescription M90)
        {
            var recordVers = new RecordVEOClassV3.Record();
            recordVers.EntityType = typeof(RecordVEOClassV3.Record).Name;
            if (M90.M11.M13 != null)
            {
                recordVers.Category = VEOV3CustomizeProperty.GetPropertyValueByLevel(M90.M11.M13.SharePointMetadataAsSource, M90.M11.M13.DefaultValue, M90.M11.M13.SharePointMetadata, _contentParams);
            }

            if (M90.M11 != null)
            {
                var M11 = M90.M11;

                AddRDFRecordIdentifierBlock(ref recordVers, M11);

                AddRDFRecordNameBlock(ref recordVers, M11);

                AddRDFRecordDateRangeBlock(ref recordVers, M11);

                AddRDFRecordDescriptionBlock(ref recordVers, M11);

                AddRDFRecordJurisdictionBlock(ref recordVers, M11);

                AddRDFRecordSecurityClassificationBlock(ref recordVers, M11);

                AddRDFRecordSecurityCaveatBlock(ref recordVers, M11);

                AddRDFRecordRightsBlock(ref recordVers, M11);

                AddRDFRecordLanguageBlock(ref recordVers, M11);

                AddRDFRecordCoverageBlock(ref recordVers, M11);

                AddRDFRecordKeywordBlock(ref recordVers, M11);

                AddRDFRecordDisposalBlock(ref recordVers, M11);

                AddRDFRecordFormatBlock(ref recordVers, M11);

                AddRDFRecordExtentBlock(ref recordVers, M11);

                if (M11.M61 != null)
                {
                    recordVers.Medium = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M61.SharePointMetadataAsSource, M11.M61.DefaultValue, M11.M61.SharePointMetadata, _contentParams);
                }

                if (_contentParams.HasIP)
                {
                    AddRDFRecordIntegrityCheckBlock(ref recordVers, M11);
                }

                AddRDFRecordLocationBlock(ref recordVers, M11);

                if (M11.M66 != null)
                {
                    recordVers.DocumentForm = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M66.SharePointMetadataAsSource, M11.M66.DefaultValue, M11.M66.SharePointMetadata, _contentParams);
                }

                if (M11.M67 != null)
                {
                    recordVers.Precedence = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M67.SharePointMetadataAsSource, M11.M67.DefaultValue, M11.M67.SharePointMetadata, _contentParams);
                }

                AddRDFRecordRelationshipBlock(ref recordVers, M11);

                description.Template = recordVers;
            }
        }

        private void AddRDFRecordRelationshipBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            if (M11.M73 != null)
            {
                recordVers.Relationship = new RecordVEOClassV3.Relationship();
                recordVers.Relationship.EntityType = typeof(RecordVEOClassV3.Relationship).Name;
                if (M11.M73.M13 != null)
                {
                    recordVers.Relationship.Category = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M73.M13.SharePointMetadataAsSource, M11.M73.M13.DefaultValue, M11.M73.M13.SharePointMetadata, _contentParams);
                }
                AddRDFRecordRelationshipIdentifierElement(ref recordVers, M11.M73);
                AddRDFRecordRelationshipNameElement(ref recordVers, M11.M73);
                AddRDFRecordRelationshipDateRangeElement(ref recordVers, M11.M73);
                AddRDFRecordRelationshipDescriptionElement(ref recordVers, M11.M73);
                AddRDFRecordRelationshipRelatedEntityElement(ref recordVers, M11.M73);
                AddRDFRecordRelationshipChangeHistoryElement(ref recordVers, M11.M73);
            }
        }

        private void AddRDFRecordRelationshipIdentifierElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            foreach (var M14 in M73.M14)
            {
                if (M14 != null)
                {
                    var identifier = new RecordVEOClassV3.RecordIdentifier();
                    if (M14.M15 != null)
                    {
                        identifier.IdentifierString = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M15.SharePointMetadataAsSource, M14.M15.DefaultValue, M14.M15.SharePointMetadata, _contentParams);
                    }
                    if (M14.M16 != null)
                    {
                        identifier.IdentifierScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M16.SharePointMetadataAsSource, M14.M16.DefaultValue, M14.M16.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(identifier))
                    {
                        continue;
                    }

                    (recordVers.Relationship.Identifier ??= []).Add(identifier);
                }
            }
        }

        private void AddRDFRecordRelationshipChangeHistoryElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            if (M73.M86 != null)
            {
                foreach (var M86 in M73.M86)
                {
                    var mChangeHistory = new RecordVEOClassV3.RelationshipChangeHistory();
                    if (M86.M87 != null)
                    {
                        mChangeHistory.PropertyName = VEOV3CustomizeProperty.GetPropertyValueByLevel(M86.M87.SharePointMetadataAsSource, M86.M87.DefaultValue, M86.M87.SharePointMetadata, _contentParams);
                    }
                    if (M86.M88 != null)
                    {
                        mChangeHistory.PriorValue = VEOV3CustomizeProperty.GetPropertyValueByLevel(M86.M88.SharePointMetadataAsSource, M86.M88.DefaultValue, M86.M88.SharePointMetadata, _contentParams);
                    }
                    if (M86.M89 != null)
                    {
                        mChangeHistory.RelationshipID = VEOV3CustomizeProperty.GetPropertyValueByLevel(M86.M89.SharePointMetadataAsSource, M86.M89.DefaultValue, M86.M89.SharePointMetadata, _contentParams);
                    }

                    if (!VEOV3CommonMethod.IsNotContainValue(mChangeHistory)) (recordVers.Relationship.ChangeHistory ??= []).Add(mChangeHistory);
                }
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            if (M73.M74 != null)
            {
                foreach (var M74 in M73.M74)
                {
                    var mRelatedEntity = new RecordVEOClassV3.RelationshipRelatedEntity();
                    if (M74.M75 != null)
                    {
                        mRelatedEntity.AssignedEntityID = VEOV3CustomizeProperty.GetPropertyValueByLevel(M74.M75.SharePointMetadataAsSource, M74.M75.DefaultValue, M74.M75.SharePointMetadata, _contentParams);
                    }
                    if (M74.M76 != null)
                    {
                        mRelatedEntity.AssignedEntityIDScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M74.M76.SharePointMetadataAsSource, M74.M76.DefaultValue, M74.M76.SharePointMetadata, _contentParams);
                    }
                    if (M74.M77 != null)
                    {
                        mRelatedEntity.RelationshipRole = VEOV3CustomizeProperty.GetPropertyValueByLevel(M74.M77.SharePointMetadataAsSource, M74.M77.DefaultValue, M74.M77.SharePointMetadata, _contentParams);
                    }

                    if (M74.M78 != null)
                    {
                        AddRDFRecordRelationshipRelatedEntityAgentBlock(ref mRelatedEntity, M74.M78);
                    }

                    if (!VEOV3CommonMethod.IsNotContainValue(mRelatedEntity)) (recordVers.Relationship.RelatedEntity ??= []).Add(mRelatedEntity);
                }
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentBlock(ref RecordVEOClassV3.RelationshipRelatedEntity mRelatedEntity, RecordVEO_M78_RDFAgent M78)
        {
            var agent = new RecordVEOClassV3.Agent();
            agent.EntityType = typeof(RecordVEOClassV3.Agent).Name;
            if (M78.M13 != null)
            {
                agent.Category = VEOV3CustomizeProperty.GetPropertyValueByLevel(M78.M13.SharePointMetadataAsSource, M78.M13.DefaultValue, M78.M13.SharePointMetadata, _contentParams);
            }
            AddRDFRecordRelationshipRelatedEntityAgentIdentifierBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentNameBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentDateRangeBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentDescriptionBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentJurisdictionBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentPermissionsBlock(ref agent, M78);

            AddRDFRecordRelationshipRelatedEntityAgentContactBlock(ref agent, M78);

            if (M78.M79 != null)
            {
                agent.Position = VEOV3CustomizeProperty.GetPropertyValueByLevel(M78.M79.SharePointMetadataAsSource, M78.M79.DefaultValue, M78.M79.SharePointMetadata, _contentParams);
            }

            AddRDFRecordRelationshipRelatedEntityAgentLanguageBlock(ref agent, M78);

            mRelatedEntity.Template = agent;
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentLanguageBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M33 in M78.M33)
            {
                var language = VEOV3CustomizeProperty.GetPropertyValueByLevel(M33.SharePointMetadataAsSource, M33.DefaultValue, M33.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(language))
                {
                    continue;
                }

                (agent.Language ??= []).Add(language);
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentContactBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M83 in M78.M83)
            {
                if (M83 != null)
                {
                    var contact = new RecordVEOClassV3.AgentContact();
                    if (M83.M84 != null)
                    {
                        contact.ContactDetails = VEOV3CustomizeProperty.GetPropertyValueByLevel(M83.M84.SharePointMetadataAsSource, M83.M84.DefaultValue, M83.M84.SharePointMetadata, _contentParams);
                    }
                    if (M83.M85 != null)
                    {
                        contact.ContactType = VEOV3CustomizeProperty.GetPropertyValueByLevel(M83.M85.SharePointMetadataAsSource, M83.M85.DefaultValue, M83.M85.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(contact))
                    {
                        continue;
                    }

                    (agent.Contact ??= []).Add(contact);
                }
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentPermissionsBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M80 in M78.M80)
            {
                if (M80 != null)
                {
                    var permissions = new RecordVEOClassV3.AgentPermissions();
                    if (M80.M81 != null)
                    {
                        permissions.PermissionText = VEOV3CustomizeProperty.GetPropertyValueByLevel(M80.M81.SharePointMetadataAsSource, M80.M81.DefaultValue, M80.M81.SharePointMetadata, _contentParams);
                    }
                    if (M80.M82 != null)
                    {
                        permissions.PermissionType = VEOV3CustomizeProperty.GetPropertyValueByLevel(M80.M82.SharePointMetadataAsSource, M80.M82.DefaultValue, M80.M82.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(permissions))
                    {
                        continue;
                    }

                    (agent.Permissions ??= []).Add(permissions);
                }
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentJurisdictionBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M24 in M78.M24)
            {
                var jurisdiction = VEOV3CustomizeProperty.GetPropertyValueByLevel(M24.SharePointMetadataAsSource, M24.DefaultValue, M24.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(jurisdiction))
                {
                    continue;
                }

                (agent.Jurisdiction ??= []).Add(jurisdiction);
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentDescriptionBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M23 in M78.M23)
            {
                var description = VEOV3CustomizeProperty.GetPropertyValueByLevel(M23.SharePointMetadataAsSource, M23.DefaultValue, M23.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(description))
                {
                    continue;
                }

                (agent.Description ??= []).Add(description);
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentDateRangeBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            if (M78.M20 != null)
            {
                var mDateRange = new RecordVEOClassV3.RecordDateRange();
                if (M78.M20.M21 != null)
                {
                    mDateRange.StartDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M78.M20.M21.SharePointMetadataAsSource, M78.M20.M21.DefaultValue, M78.M20.M21.SharePointMetadata, _contentParams);
                }
                if (M78.M20.M22 != null)
                {
                    mDateRange.EndDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M78.M20.M22.SharePointMetadataAsSource, M78.M20.M22.DefaultValue, M78.M20.M22.SharePointMetadata, _contentParams);
                }

                mDateRange.StartDate = mDateRange.StartDate.IsNullOrEmpty() ? DateTime.Now.ToString(VEOV3CommonString.FORMAT_DATETIME_V3) : mDateRange.StartDate;

                if (VEOV3CommonMethod.IsNotContainValue(mDateRange))
                {
                    return;
                }

                agent.DateRange = mDateRange;
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentNameBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M17 in M78.M17)
            {
                if (M17 != null)
                {
                    var recordName = new RecordVEOClassV3.RecordName();
                    if (M17.M18 != null)
                    {
                        recordName.NameWords = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M18.SharePointMetadataAsSource, M17.M18.DefaultValue, M17.M18.SharePointMetadata, _contentParams);
                    }
                    if (M17.M19 != null)
                    {
                        recordName.NameScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M19.SharePointMetadataAsSource, M17.M19.DefaultValue, M17.M19.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(recordName))
                    {
                        continue;
                    }

                    (agent.Name ??= []).Add(recordName);
                }
            }
        }

        private void AddRDFRecordRelationshipRelatedEntityAgentIdentifierBlock(ref RecordVEOClassV3.Agent agent, RecordVEO_M78_RDFAgent M78)
        {
            foreach (var M14 in M78.M14)
            {
                if (M14 != null)
                {
                    var identifier = new RecordVEOClassV3.RecordIdentifier();
                    if (M14.M15 != null)
                    {
                        identifier.IdentifierString = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M15.SharePointMetadataAsSource, M14.M15.DefaultValue, M14.M15.SharePointMetadata, _contentParams);
                    }
                    if (M14.M16 != null)
                    {
                        identifier.IdentifierScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M16.SharePointMetadataAsSource, M14.M16.DefaultValue, M14.M16.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(identifier))
                    {
                        continue;
                    }

                    (agent.Identifier ??= []).Add(identifier);
                }
            }
        }

        private void AddRDFRecordRelationshipDescriptionElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            foreach (var M23 in M73.M23)
            {
                var description = VEOV3CustomizeProperty.GetPropertyValueByLevel(M23.SharePointMetadataAsSource, M23.DefaultValue, M23.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(description))
                {
                    continue;
                }

                (recordVers.Relationship.Description ??= []).Add(description);
            }
        }

        private void AddRDFRecordRelationshipDateRangeElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            if (M73.M20 != null)
            {
                var mDateRange = new RecordVEOClassV3.RecordDateRange();
                if (M73.M20.M21 != null)
                {
                    mDateRange.StartDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M73.M20.M21.SharePointMetadataAsSource, M73.M20.M21.DefaultValue, M73.M20.M21.SharePointMetadata, _contentParams);
                }
                if (M73.M20.M22 != null)
                {
                    mDateRange.EndDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M73.M20.M22.SharePointMetadataAsSource, M73.M20.M22.DefaultValue, M73.M20.M22.SharePointMetadata, _contentParams);
                }

                recordVers.Relationship.DateRange = VEOV3CommonMethod.FilteredValidValue(mDateRange);
            }
        }

        private void AddRDFRecordRelationshipNameElement(ref RecordVEOClassV3.Record recordVers, RecordVEO_M73_RDFRecord_Relationship M73)
        {
            foreach (var M17 in M73.M17)
            {
                if (M17 != null)
                {
                    var recordName = new RecordVEOClassV3.RecordName();
                    if (M17.M18 != null)
                    {
                        recordName.NameWords = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M18.SharePointMetadataAsSource, M17.M18.DefaultValue, M17.M18.SharePointMetadata, _contentParams);
                    }
                    if (M17.M19 != null)
                    {
                        recordName.NameScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M19.SharePointMetadataAsSource, M17.M19.DefaultValue, M17.M19.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(recordName))
                    {
                        continue;
                    }

                    (recordVers.Relationship.Name ??= []).Add(recordName);
                }
            }
        }

        private void AddRDFRecordLocationBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M65 in M11.M65)
            {
                var mLocation = VEOV3CustomizeProperty.GetPropertyValueByLevel(M65.SharePointMetadataAsSource, M65.DefaultValue, M65.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(mLocation))
                {
                    continue;
                }

                (recordVers.Location ??= []).Add(mLocation);
            }
        }

        private void AddRDFRecordIntegrityCheckBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            if (M11.M62 != null)
            {
                var mIntegrityCheck = new RecordVEOClassV3.RecordIntegrityCheck();

                if (M11.M62.M63 != null)
                {
                    mIntegrityCheck.HashFunctionName = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M62.M63.SharePointMetadataAsSource, M11.M62.M63.DefaultValue, M11.M62.M63.SharePointMetadata, _contentParams);
                }
                if (!string.IsNullOrEmpty(mIntegrityCheck.HashFunctionName) && !string.IsNullOrEmpty(_contentParams.VContentFullPath))
                {
                    try
                    {
                        using (var stream = File.OpenRead(_contentParams.VContentFullPath))
                        {
                            mIntegrityCheck.MessageDigest = VEOV3CommonMethod.ComputeHashAsBase64(stream, mIntegrityCheck.HashFunctionName);
                        }
                        if (string.Equals(mIntegrityCheck.HashFunctionName, VEOV3CommonString.ALGORITHM_SHA512, StringComparison.OrdinalIgnoreCase))
                        {
                            _contentParams.VContentHashValue = mIntegrityCheck.MessageDigest;
                        }
                    }
                    catch (Exception e)
                    {
                        mLog.Error($"An error occurred while hashing the content of file {_contentParams.VName}, HashFunctionName: {mIntegrityCheck.HashFunctionName} so convert base64 instead. EX: {e}");
                        _contentParams.VContentHashValue = string.Empty;
                        return;
                    }
                }

                recordVers.IntegrityCheck = VEOV3CommonMethod.FilteredValidValue(mIntegrityCheck);
            }
        }

        private void AddRDFRecordExtentBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M56 in M11.M56)
            {
                if (M56 != null && _contentParams.Level == PolicyLevel.Document)
                {
                    var mExtent = new RecordVEOClassV3.RecordExtent();
                    if (M56.M57 != null)
                    {
                        mExtent.PhysicalDimensions = VEOV3CustomizeProperty.GetPropertyValueByLevel(M56.M57.SharePointMetadataAsSource, M56.M57.DefaultValue, M56.M57.SharePointMetadata, _contentParams);
                    }
                    if (M56.M58 != null)
                    {
                        mExtent.LogicalSize = VEOV3CustomizeProperty.GetPropertyValueByLevel(M56.M58.SharePointMetadataAsSource, M56.M58.DefaultValue, M56.M58.SharePointMetadata, _contentParams);
                    }
                    if (M56.M59 != null)
                    {
                        mExtent.Quantity = VEOV3CustomizeProperty.GetPropertyValueByLevel(M56.M59.SharePointMetadataAsSource, M56.M59.DefaultValue, M56.M59.SharePointMetadata, _contentParams);
                    }
                    if (M56.M60 != null)
                    {
                        mExtent.Units = VEOV3CustomizeProperty.GetPropertyValueByLevel(M56.M60.SharePointMetadataAsSource, M56.M60.DefaultValue, M56.M60.SharePointMetadata, _contentParams);
                    }

                    if (int.TryParse(mExtent.LogicalSize, out int result) && !string.IsNullOrEmpty(mExtent.Units))
                    {
                        mExtent.LogicalSize = Math.Round(VEOV3CommonMethod.AutoFitSizeUnit(result, mExtent.Units), 2).ToString();
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(mExtent))
                    {
                        continue;
                    }

                    (recordVers.Extent ??= []).Add(mExtent);
                }
            }
        }

        private void AddRDFRecordFormatBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            if (M11.M49 != null && _contentParams.Level == PolicyLevel.Document)
            {
                var mFormat = new RecordVEOClassV3.RecordFormat();
                if (M11.M49.M50 != null)
                {
                    mFormat.FormatName = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M50.SharePointMetadataAsSource, M11.M49.M50.DefaultValue, M11.M49.M50.SharePointMetadata, _contentParams);
                }
                if (M11.M49.M51 != null)
                {
                    mFormat.FormatVersion = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M51.SharePointMetadataAsSource, M11.M49.M51.DefaultValue, M11.M49.M51.SharePointMetadata, _contentParams);
                }
                if (M11.M49.M52 != null)
                {
                    mFormat.CreatingApplicationName = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M52.SharePointMetadataAsSource, M11.M49.M52.DefaultValue, M11.M49.M52.SharePointMetadata, _contentParams);
                }
                if (M11.M49.M53 != null)
                {
                    mFormat.CreatingApplicationVersion = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M53.SharePointMetadataAsSource, M11.M49.M53.DefaultValue, M11.M49.M53.SharePointMetadata, _contentParams);
                }
                if (M11.M49.M54 != null)
                {
                    mFormat.FormatRegistry = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M54.SharePointMetadataAsSource, M11.M49.M54.DefaultValue, M11.M49.M54.SharePointMetadata, _contentParams);
                }
                if (M11.M49.M55 != null)
                {
                    mFormat.FormatRegistryID = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M49.M55.SharePointMetadataAsSource, M11.M49.M55.DefaultValue, M11.M49.M55.SharePointMetadata, _contentParams);
                }

                recordVers.Format = VEOV3CommonMethod.FilteredValidValue(mFormat);
            }
        }

        private void AddRDFRecordDisposalBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M43 in M11.M43)
            {
                if (M43 != null)
                {
                    var disposal = new RecordVEOClassV3.RecordDisposal();
                    if (M43.M44 != null)
                    {
                        disposal.RetentionAndDisposalAuthority = VEOV3CustomizeProperty.GetPropertyValueByLevel(M43.M44.SharePointMetadataAsSource, M43.M44.DefaultValue, M43.M44.SharePointMetadata, _contentParams);
                    }

                    if (!string.Equals(disposal.RetentionAndDisposalAuthority, VEOV3CommonString.NO_DISPOSAL_COVERAGE, StringComparison.OrdinalIgnoreCase))
                    {
                        if (M43.M45 != null)
                        {
                            disposal.DisposalClassID = VEOV3CustomizeProperty.GetPropertyValueByLevel(M43.M45.SharePointMetadataAsSource, M43.M45.DefaultValue, M43.M45.SharePointMetadata, _contentParams);
                        }
                        if (M43.M46 != null)
                        {
                            disposal.DisposalAction = VEOV3CustomizeProperty.GetPropertyValueByLevel(M43.M46.SharePointMetadataAsSource, M43.M46.DefaultValue, M43.M46.SharePointMetadata, _contentParams);
                        }
                        if (M43.M47 != null)
                        {
                            AddRDFRecordRecordDisposalDisposalTriggerDateBlock(ref disposal, M43);
                        }
                        if (M43.M48 != null)
                        {
                            AddRDFRecordRecordDisposalDisposalActionDueBlock(ref disposal, M43);
                        }
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(disposal))
                    {
                        continue;
                    }

                    (recordVers.Disposal ??= []).Add(disposal);
                }
            }
        }

        private void AddRDFRecordRecordDisposalDisposalTriggerDateBlock(ref RecordVEOClassV3.RecordDisposal recordRight, RecordVEO_M43_RDFRecord_Disposal M43)
        {
            foreach (var M47 in M43.M47)
            {
                var disposalTriggerDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M47.SharePointMetadataAsSource, M47.DefaultValue, M47.SharePointMetadata, _contentParams);
                if (!string.IsNullOrEmpty(disposalTriggerDate)) (recordRight.DisposalTriggerDate ??= []).Add(disposalTriggerDate);
            }
        }

        private void AddRDFRecordRecordDisposalDisposalActionDueBlock(ref RecordVEOClassV3.RecordDisposal recordRight, RecordVEO_M43_RDFRecord_Disposal M43)
        {
            foreach (var M48 in M43.M48)
            {
                var disposalActionDue = VEOV3CustomizeProperty.GetPropertyValueByLevel(M48.SharePointMetadataAsSource, M48.DefaultValue, M48.SharePointMetadata, _contentParams);
                if (!string.IsNullOrEmpty(disposalActionDue)) (recordRight.DisposalActionDue ??= []).Add(disposalActionDue);
            }
        }

        private void AddRDFRecordKeywordBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M38 in M11.M38)
            {
                if (M38 != null)
                {
                    var keyword = new RecordVEOClassV3.RecordKeyword();
                    if (M38.M39 != null)
                    {
                        keyword.KeywordTerm = VEOV3CustomizeProperty.GetPropertyValueByLevel(M38.M39.SharePointMetadataAsSource, M38.M39.DefaultValue, M38.M39.SharePointMetadata, _contentParams);
                    }
                    if (M38.M40 != null)
                    {
                        keyword.KeywordID = VEOV3CustomizeProperty.GetPropertyValueByLevel(M38.M40.SharePointMetadataAsSource, M38.M40.DefaultValue, M38.M40.SharePointMetadata, _contentParams);
                    }
                    if (M38.M41 != null)
                    {
                        keyword.KeywordScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M38.M41.SharePointMetadataAsSource, M38.M41.DefaultValue, M38.M41.SharePointMetadata, _contentParams);
                    }
                    if (M38.M42 != null)
                    {
                        keyword.KeywordSchemeType = VEOV3CustomizeProperty.GetPropertyValueByLevel(M38.M42.SharePointMetadataAsSource, M38.M42.DefaultValue, M38.M42.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(keyword))
                    {
                        continue;
                    }

                    (recordVers.Keyword ??= []).Add(keyword);
                }
            }
        }

        private void AddRDFRecordCoverageBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M34 in M11.M34)
            {
                if (M34 != null)
                {
                    var coverage = new RecordVEOClassV3.RecordCoverage();
                    if (M34.M35 != null)
                    {
                        AddRDFRecordCoverageJurisdictionalCoverageBlock(ref coverage, M34);
                    }
                    if (M34.M36 != null)
                    {
                        AddRDFRecordCoverageTemporalCoverageBlock(ref coverage, M34);
                    }
                    if (M34.M37 != null)
                    {
                        AddRDFRecordCoverageSpatialCoverageBlock(ref coverage, M34);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(coverage))
                    {
                        continue;
                    }

                    (recordVers.Coverage ??= []).Add(coverage);
                }
            }
        }

        private void AddRDFRecordCoverageSpatialCoverageBlock(ref RecordVEOClassV3.RecordCoverage recordCoverage, RecordVEO_M34_RDFRecord_Coverage M34)
        {
            foreach (var M37 in M34.M37)
            {
                var temporalCoverage = VEOV3CustomizeProperty.GetPropertyValueByLevel(M37.SharePointMetadataAsSource, M37.DefaultValue, M37.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(temporalCoverage))
                {
                    continue;
                }

                (recordCoverage.SpatialCoverage ??= []).Add(temporalCoverage);
            }
        }

        private void AddRDFRecordCoverageTemporalCoverageBlock(ref RecordVEOClassV3.RecordCoverage recordCoverage, RecordVEO_M34_RDFRecord_Coverage M34)
        {
            foreach (var M36 in M34.M36)
            {
                var temporalCoverage = VEOV3CustomizeProperty.GetPropertyValueByLevel(M36.SharePointMetadataAsSource, M36.DefaultValue, M36.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(temporalCoverage))
                {
                    continue;
                }

                (recordCoverage.TemporalCoverage ??= []).Add(temporalCoverage);
            }
        }

        private void AddRDFRecordCoverageJurisdictionalCoverageBlock(ref RecordVEOClassV3.RecordCoverage recordCoverage, RecordVEO_M34_RDFRecord_Coverage M34)
        {
            foreach (var M35 in M34.M35)
            {
                var jurisdictionalCoverage = VEOV3CustomizeProperty.GetPropertyValueByLevel(M35.SharePointMetadataAsSource, M35.DefaultValue, M35.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(jurisdictionalCoverage))
                {
                    continue;
                }

                (recordCoverage.JurisdictionalCoverage ??= []).Add(jurisdictionalCoverage);
            }
        }

        private void AddRDFRecordLanguageBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M33 in M11.M33)
            {
                var language = VEOV3CustomizeProperty.GetPropertyValueByLevel(M33.SharePointMetadataAsSource, M33.DefaultValue, M33.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(language))
                {
                    continue;
                }

                (recordVers.Language ??= []).Add(language);
            }
        }

        private void AddRDFRecordRightsBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M29 in M11.M29)
            {
                if (M29 != null)
                {
                    var rights = new RecordVEOClassV3.RecordRights();
                    if (M29.M30 != null)
                    {
                        AddRDFRecordRightsRightsStatementBlock(ref rights, M29);
                    }
                    if (M29.M31 != null)
                    {
                        rights.RightsType = VEOV3CustomizeProperty.GetPropertyValueByLevel(M29.M31.SharePointMetadataAsSource, M29.M31.DefaultValue, M29.M31.SharePointMetadata, _contentParams);
                    }
                    if (M29.M32 != null)
                    {
                        rights.RightsStatus = VEOV3CustomizeProperty.GetPropertyValueByLevel(M29.M32.SharePointMetadataAsSource, M29.M32.DefaultValue, M29.M32.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(rights))
                    {
                        continue;
                    }

                    (recordVers.Rights ??= []).Add(rights);
                }
            }
        }

        private void AddRDFRecordRightsRightsStatementBlock(ref RecordVEOClassV3.RecordRights recordRight, RecordVEO_M29_RDFRecord_Rights M29)
        {
            foreach (var M30 in M29.M30)
            {
                var rightsStatement = VEOV3CustomizeProperty.GetPropertyValueByLevel(M30.SharePointMetadataAsSource, M30.DefaultValue, M30.SharePointMetadata, _contentParams);
                if (!string.IsNullOrEmpty(rightsStatement)) (recordRight.RightsStatement ??= []).Add(rightsStatement);
            }
        }

        private void AddRDFRecordSecurityCaveatBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M26 in M11.M26)
            {
                if (M26 != null)
                {
                    var securityCaveat = new RecordVEOClassV3.RecordSecurityCaveat();
                    if (M26.M27 != null)
                    {
                        securityCaveat.CaveatText = VEOV3CustomizeProperty.GetPropertyValueByLevel(M26.M27.SharePointMetadataAsSource, M26.M27.DefaultValue, M26.M27.SharePointMetadata, _contentParams);
                    }
                    if (M26.M28 != null)
                    {
                        securityCaveat.CaveatCategory = VEOV3CustomizeProperty.GetPropertyValueByLevel(M26.M28.SharePointMetadataAsSource, M26.M28.DefaultValue, M26.M28.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(securityCaveat))
                    {
                        continue;
                    }

                    (recordVers.SecurityCaveat ??= []).Add(securityCaveat);
                }
            }
        }

        private void AddRDFRecordSecurityClassificationBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M25 in M11.M25)
            {
                var securityClassification = VEOV3CustomizeProperty.GetPropertyValueByLevel(M25.SharePointMetadataAsSource, M25.DefaultValue, M25.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(securityClassification))
                {
                    continue;
                }

                (recordVers.SecurityClassification ??= []).Add(securityClassification);
            }
        }

        private void AddRDFRecordJurisdictionBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M24 in M11.M24)
            {
                var jurisdiction = VEOV3CustomizeProperty.GetPropertyValueByLevel(M24.SharePointMetadataAsSource, M24.DefaultValue, M24.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(jurisdiction))
                {
                    continue;
                }

                (recordVers.Jurisdiction ??= []).Add(jurisdiction);
            }
        }

        private void AddRDFRecordDescriptionBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M23 in M11.M23)
            {
                var description = VEOV3CustomizeProperty.GetPropertyValueByLevel(M23.SharePointMetadataAsSource, M23.DefaultValue, M23.SharePointMetadata, _contentParams);

                if (string.IsNullOrEmpty(description))
                {
                    continue;
                }

                (recordVers.Description ??= []).Add(description);
            }
        }

        private void AddRDFRecordDateRangeBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            if (M11.M20 != null)
            {
                var mDateRange = new RecordVEOClassV3.RecordDateRange();
                if (M11.M20.M21 != null)
                {
                    mDateRange.StartDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M20.M21.SharePointMetadataAsSource, M11.M20.M21.DefaultValue, M11.M20.M21.SharePointMetadata, _contentParams);
                }
                if (M11.M20.M22 != null)
                {
                    mDateRange.EndDate = VEOV3CustomizeProperty.GetPropertyValueByLevel(M11.M20.M22.SharePointMetadataAsSource, M11.M20.M22.DefaultValue, M11.M20.M22.SharePointMetadata, _contentParams);
                }

                recordVers.DateRange = VEOV3CommonMethod.FilteredValidValue(mDateRange);
            }
        }

        private void AddRDFRecordNameBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M17 in M11.M17)
            {
                if (M17 != null)
                {
                    var recordName = new RecordVEOClassV3.RecordName();
                    if (M17.M18 != null)
                    {
                        recordName.NameWords = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M18.SharePointMetadataAsSource, M17.M18.DefaultValue, M17.M18.SharePointMetadata, _contentParams);
                    }
                    if (M17.M19 != null)
                    {
                        recordName.NameScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M17.M19.SharePointMetadataAsSource, M17.M19.DefaultValue, M17.M19.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(recordName))
                    {
                        continue;
                    }

                    (recordVers.Name ??= []).Add(recordName);
                }
            }
        }

        public void AddRDFRecordIdentifierBlock(ref RecordVEOClassV3.Record recordVers, RecordVEO_M11RDFRecord M11)
        {
            foreach (var M14 in M11.M14)
            {
                if (M14 != null)
                {
                    var identifier = new RecordVEOClassV3.RecordIdentifier();
                    if (M14.M15 != null)
                    {
                        identifier.IdentifierString = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M15.SharePointMetadataAsSource, M14.M15.DefaultValue, M14.M15.SharePointMetadata, _contentParams);
                    }
                    if (M14.M16 != null)
                    {
                        identifier.IdentifierScheme = VEOV3CustomizeProperty.GetPropertyValueByLevel(M14.M16.SharePointMetadataAsSource, M14.M16.DefaultValue, M14.M16.SharePointMetadata, _contentParams);
                    }

                    if (VEOV3CommonMethod.IsNotContainValue(identifier))
                    {
                        continue;
                    }

                    (recordVers.Identifier ??= []).Add(identifier);
                }
            }
        }

        private void AddInformationPieceBlock(ref RecordVEOClassV3.InformationObject mInformationObject, RecordVEO_M4_InfomationObject M4)
        {
            foreach (var M68 in M4.M68)
            {
                var informationPiece = new RecordVEOClassV3.InformationPiece();

                if (M68.M69 != null)
                {
                    informationPiece.Label = VEOV3CustomizeProperty.GetPropertyValueByLevel(M68.M69.SharePointMetadataAsSource, M68.M69.DefaultValue, M68.M69.SharePointMetadata, _contentParams);
                }

                if (string.IsNullOrEmpty(informationPiece.Label))
                {
                    informationPiece.Label = _contentParams.AveSPDoc?.AveSPItem.SPListItem.Name;
                }

                AddContentFileBlock(ref informationPiece, M68);

                (mInformationObject.InformationPiece ??= []).Add(informationPiece);
            }
        }

        private void AddContentFileBlock(ref RecordVEOClassV3.InformationPiece mInformationPiece, RecordVEO_M68_InformationPiece M68)
        {
            // always generate value by ourself
            var contentFile = new RecordVEOClassV3.ContentFile
            {
                PathName = _contentParams.VContentPathName,
            };
            try
            {
                if (string.IsNullOrEmpty(_contentParams.VContentFullPath)) throw new Exception($"Cannot get the content of this file");
                using (var stream = File.OpenRead(_contentParams.VContentFullPath))
                {
                    contentFile.HashValue = string.IsNullOrEmpty(_contentParams.VContentHashValue)
                        ? VEOV3CommonMethod.ComputeHashAsBase64(stream)
                        : _contentParams.VContentHashValue;
                }
            }
            catch (Exception e)
            {
                mLog.Error($"An error occurred while hashing content of file {_contentParams.VUrl}. Ex: {e}");
                throw;
            }

            (mInformationPiece.ContentFile ??= []).Add(contentFile);
        }

    }
}
