/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvePoint.Wrapper.Resource.Discovery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WrapperDiscoverResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WrapperDiscoverResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvePoint.Wrapper.Resource.Discovery.WrapperDiscoverResource", typeof(WrapperDiscoverResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting alerts.
        /// </summary>
        public static string AWDGetAlertsError {
            get {
                return ResourceManager.GetString("AWDGetAlertsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting attachments.
        /// </summary>
        public static string AWDGetAttachmentsError {
            get {
                return ResourceManager.GetString("AWDGetAttachmentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting attachments for platform backup.
        /// </summary>
        public static string AWDGetAttachmentsForPRError {
            get {
                return ResourceManager.GetString("AWDGetAttachmentsForPRError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting changed sites.
        /// </summary>
        public static string AWDGetChangedSiteError {
            get {
                return ResourceManager.GetString("AWDGetChangedSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting changed users.
        /// </summary>
        public static string AWDGetChangedUsersError {
            get {
                return ResourceManager.GetString("AWDGetChangedUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting changed sub sites.
        /// </summary>
        public static string AWDGetChangedWebError {
            get {
                return ResourceManager.GetString("AWDGetChangedWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting changed size.
        /// </summary>
        public static string AWDGetChangeSizeError {
            get {
                return ResourceManager.GetString("AWDGetChangeSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting content types.
        /// </summary>
        public static string AWDGetCTsError {
            get {
                return ResourceManager.GetString("AWDGetCTsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting filter attachments.Exception:{0}.
        /// </summary>
        public static string AWDGetFilterAttachmentsError {
            get {
                return ResourceManager.GetString("AWDGetFilterAttachmentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting filter items .Exception:{0}.
        /// </summary>
        public static string AWDGetFilterItemsError {
            get {
                return ResourceManager.GetString("AWDGetFilterItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting folder.
        /// </summary>
        public static string AWDGetFolderError {
            get {
                return ResourceManager.GetString("AWDGetFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting folder size.
        /// </summary>
        public static string AWDGetFolderSizeError {
            get {
                return ResourceManager.GetString("AWDGetFolderSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting guid to docid mapping.
        /// </summary>
        public static string AWDGetGuidDocIdMappingError {
            get {
                return ResourceManager.GetString("AWDGetGuidDocIdMappingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting last modify time of item.
        /// </summary>
        public static string AWDGetItemModifyTimeError {
            get {
                return ResourceManager.GetString("AWDGetItemModifyTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting items.
        /// </summary>
        public static string AWDGetItemsError {
            get {
                return ResourceManager.GetString("AWDGetItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting item size.
        /// </summary>
        public static string AWDGetItemSizeError {
            get {
                return ResourceManager.GetString("AWDGetItemSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting item webparts.
        /// </summary>
        public static string AWDGetItemWebpartsError {
            get {
                return ResourceManager.GetString("AWDGetItemWebpartsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting list.
        /// </summary>
        public static string AWDGetListError {
            get {
                return ResourceManager.GetString("AWDGetListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting list root folder.
        /// </summary>
        public static string AWDGetListRoorFolderError {
            get {
                return ResourceManager.GetString("AWDGetListRoorFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting list size.
        /// </summary>
        public static string AWDGetListSizeError {
            get {
                return ResourceManager.GetString("AWDGetListSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting root sites.
        /// </summary>
        public static string AWDGetRootWebError {
            get {
                return ResourceManager.GetString("AWDGetRootWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting changed securities.
        /// </summary>
        public static string AWDGetSecuritiesError {
            get {
                return ResourceManager.GetString("AWDGetSecuritiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting size size.
        /// </summary>
        public static string AWDGetSizeSizeError {
            get {
                return ResourceManager.GetString("AWDGetSizeSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting stub contents.
        /// </summary>
        public static string AWDGetStubContentsError {
            get {
                return ResourceManager.GetString("AWDGetStubContentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting stub items.
        /// </summary>
        public static string AWDGetStubItemsError {
            get {
                return ResourceManager.GetString("AWDGetStubItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting sub folders.
        /// </summary>
        public static string AWDGetSubFoldersError {
            get {
                return ResourceManager.GetString("AWDGetSubFoldersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting sub sites.
        /// </summary>
        public static string AWDGetSubSitesError {
            get {
                return ResourceManager.GetString("AWDGetSubSitesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the user.Maybe the user has been delete. Exception:{0}.
        /// </summary>
        public static string AWDGetUserError {
            get {
                return ResourceManager.GetString("AWDGetUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting user info, Column:{0}. User:{1}.Exception:{2}.
        /// </summary>
        public static string AWDGetUserInfoError {
            get {
                return ResourceManager.GetString("AWDGetUserInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting versions.
        /// </summary>
        public static string AWDGetVersionsError {
            get {
                return ResourceManager.GetString("AWDGetVersionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting views.
        /// </summary>
        public static string AWDGetViewsError {
            get {
                return ResourceManager.GetString("AWDGetViewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting version editor Info.Exception:{0}.
        /// </summary>
        public static string AWDGetVisionEditorError {
            get {
                return ResourceManager.GetString("AWDGetVisionEditorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting sub sites.
        /// </summary>
        public static string AWDGetWebError {
            get {
                return ResourceManager.GetString("AWDGetWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting sub site root folder.
        /// </summary>
        public static string AWDGetWebRootFolderError {
            get {
                return ResourceManager.GetString("AWDGetWebRootFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing list&apos;s property.
        /// </summary>
        public static string AWDInitListPropertyError {
            get {
                return ResourceManager.GetString("AWDInitListPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the Created By value. The list\library-level rule in the filter policy selected for this job is invalid..
        /// </summary>
        public static string AWDOffice365NotSupportListCreatedByRule {
            get {
                return ResourceManager.GetString("AWDOffice365NotSupportListCreatedByRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the Created By value. The site-level rule in the filter policy selected for this job is invalid..
        /// </summary>
        public static string AWDOffice365NotSupportWebCreatedByRule {
            get {
                return ResourceManager.GetString("AWDOffice365NotSupportWebCreatedByRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while validating the diffrences of the names.
        /// </summary>
        public static string AWDValidateNameError {
            get {
                return ResourceManager.GetString("AWDValidateNameError", resourceCulture);
            }
        }
    }
}
