/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merged18NResources.Archive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ARCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ARCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP2010StorageOptimizationResource.Archive.ARCommon", typeof(ARCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting item..
        /// </summary>
        public static string SOARCOMArchiverReportDtoAddDeletionCommonsItem {
            get {
                return ResourceManager.GetString("SOARCOMArchiverReportDtoAddDeletionCommonsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting list..
        /// </summary>
        public static string SOARCOMArchiverReportDtoAddDeletionCommonsList {
            get {
                return ResourceManager.GetString("SOARCOMArchiverReportDtoAddDeletionCommonsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting site..
        /// </summary>
        public static string SOARCOMArchiverReportDtoAddDeletionCommonsSite {
            get {
                return ResourceManager.GetString("SOARCOMArchiverReportDtoAddDeletionCommonsSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting site collection..
        /// </summary>
        public static string SOARCOMArchiverReportDtoAddDeletionCommonsSiteCollection {
            get {
                return ResourceManager.GetString("SOARCOMArchiverReportDtoAddDeletionCommonsSiteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in CheckCriteria.
        /// </summary>
        public static string SOARCOMCheckRuleManagementCriteria {
            get {
                return ResourceManager.GetString("SOARCOMCheckRuleManagementCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching node:.
        /// </summary>
        public static string SOARCOMCustomContainersFetchNext {
            get {
                return ResourceManager.GetString("SOARCOMCustomContainersFetchNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending process..
        /// </summary>
        public static string SOARCOMJobProgressDtoProcessThread {
            get {
                return ResourceManager.GetString("SOARCOMJobProgressDtoProcessThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send JobProcess:{0} successfull.
        /// </summary>
        public static string SOARCOMJobProgressDtoProcessThreadSendJobProcess {
            get {
                return ResourceManager.GetString("SOARCOMJobProgressDtoProcessThreadSendJobProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send status : {0} successfull.
        /// </summary>
        public static string SOARCOMJobProgressDtoProcessThreadSendJobStatus {
            get {
                return ResourceManager.GetString("SOARCOMJobProgressDtoProcessThreadSendJobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;PCContainer&quot;, &quot;The consuming process has been stopped.&quot;.
        /// </summary>
        public static string SOARCOMPCContainerConsumeObjectDisposedException {
            get {
                return ResourceManager.GetString("SOARCOMPCContainerConsumeObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer gets an object from an empty container..
        /// </summary>
        public static string SOARCOMPCContainerConsumeSynchronizationLockException {
            get {
                return ResourceManager.GetString("SOARCOMPCContainerConsumeSynchronizationLockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;PCContainer&quot;, &quot;The producing process has been stopped.&quot;.
        /// </summary>
        public static string SOARCOMPCContainerProduceObjectDisposedException {
            get {
                return ResourceManager.GetString("SOARCOMPCContainerProduceObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer adds an object to the full container..
        /// </summary>
        public static string SOARCOMPCContainerProduceSynchronizationLockException {
            get {
                return ResourceManager.GetString("SOARCOMPCContainerProduceSynchronizationLockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked expression failed. Expression:.
        /// </summary>
        public static string SOARCOMRuleManagementCheckCriteriaException {
            get {
                return ResourceManager.GetString("SOARCOMRuleManagementCheckCriteriaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the resource files of SharePoint..
        /// </summary>
        public static string SOARCOMScheduleLanguageMappingScheduleLanguageMappingFileNotFoundException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleLanguageMappingScheduleLanguageMappingFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Web cannot be null because the API&apos;s invocation is required..
        /// </summary>
        public static string SOARCOMScheduleRulesAttachmentImpInitAPIVariablesValue {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesAttachmentImpInitAPIVariablesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened for doc {0} and web {1}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpDocumentInitAPIVariablesValue {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpDocumentInitAPIVariablesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened for doc {0} and web {1}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpDocumentInitException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpDocumentInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Web cannot be null because the API&apos;s invocation is required..
        /// </summary>
        public static string SOARCOMScheduleRulesImpDocumentOpenListItemExceptionSPWeb {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpDocumentOpenListItemExceptionSPWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Open file with special userToken with Exception occurred. Exception Details: {0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpDocumentOpenSPFile {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpDocumentOpenSPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target table value is invalid{0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpDocumentVersionInitElementaryInfoException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpDocumentVersionInitElementaryInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened for doc {0} and web {1}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpInitItemVersionAPIVariablesValueException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpInitItemVersionAPIVariablesValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened for doc {0} and web {1}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemInitAPIVariablesValueException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemInitAPIVariablesValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened for doc {0} and web {1}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemInitException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemOpenListItemExceptionSPList {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemOpenListItemExceptionSPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Web cannot be null because the API&apos;s invocation is required..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemOpenListItemExceptionSPWeb {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemOpenListItemExceptionSPWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with special userToken with Exception occurred. Exception Details: {0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemOpenSPFile {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemOpenSPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target table value is invalid{0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemVersionInitElementaryInfoException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemVersionInitElementaryInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemVersionOpenListItemExceptionSPList {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemVersionOpenListItemExceptionSPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Web cannot be null because the API&apos;s invocation is required..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemVersionOpenListItemExceptionSPWeb {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemVersionOpenListItemExceptionSPWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with special userToken with Exception occurred. Exception Details: {0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemVersionOpenListItemOpenSPFile {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemVersionOpenListItemOpenSPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file with special userToken with Exception occurred. Exception Details: {0}..
        /// </summary>
        public static string SOARCOMScheduleRulesImpItemVersionOpenSPFile {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpItemVersionOpenSPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got field of item {0} failed. Column name: {1}.
        /// </summary>
        public static string SOARCOMScheduleRulesImpObtainColumnsInfoSPObjectNotFoundException {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpObtainColumnsInfoSPObjectNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint list item cannot be opened..
        /// </summary>
        public static string SOARCOMScheduleRulesImpOpenListItemExceptionSPListItem {
            get {
                return ResourceManager.GetString("SOARCOMScheduleRulesImpOpenListItemExceptionSPListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin to Init ApproveReport.
        /// </summary>
        public static string SOCOMMONApprovalReportDtoApprovalReportDtoBeginInit {
            get {
                return ResourceManager.GetString("SOCOMMONApprovalReportDtoApprovalReportDtoBeginInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin send ApproveReport.
        /// </summary>
        public static string SOCOMMONApprovalReportDtoSendApproveDetailBeginSend {
            get {
                return ResourceManager.GetString("SOCOMMONApprovalReportDtoSendApproveDetailBeginSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send ApproveReport successfull.
        /// </summary>
        public static string SOCOMMONApprovalReportDtoSendApproveDetailSendSuccessull {
            get {
                return ResourceManager.GetString("SOCOMMONApprovalReportDtoSendApproveDetailSendSuccessull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobProgressDto :Error In Dispose.
        /// </summary>
        public static string SOCOMMONJobProgressDtoDispose {
            get {
                return ResourceManager.GetString("SOCOMMONJobProgressDtoDispose", resourceCulture);
            }
        }
    }
}
