/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

/// <summary>
///
/// </summary>
public class FileVEOClass
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class VERSEncapsulatedObject
    {

        private Text vEOFormatDescriptionField;

        private string versionField;

        private SignatureBlock signatureBlockField;

        private LockSignatureBlock lockSignatureBlockField;

        private SignedObject signedObjectField;

        /// <remarks/>
        public Text VEOFormatDescription
        {
            get
            {
                return this.vEOFormatDescriptionField;
            }
            set
            {
                this.vEOFormatDescriptionField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public SignatureBlock SignatureBlock
        {
            get
            {
                return this.signatureBlockField;
            }
            set
            {
                this.signatureBlockField = value;
            }
        }

        /// <remarks/>
        public LockSignatureBlock LockSignatureBlock
        {
            get
            {
                return this.lockSignatureBlockField;
            }
            set
            {
                this.lockSignatureBlockField = value;
            }
        }

        /// <remarks/>
        public SignedObject SignedObject
        {
            get
            {
                return this.signedObjectField;
            }
            set
            {
                this.signedObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute("VEOFormatDescription", Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class Text
    {

        private string text1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public string Text1
        {
            get
            {
                return this.text1Field;
            }
            set
            {
                this.text1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    public partial class SignatureBlock
    {

        private string signatureFormatDescriptionField;

        private SignatureAlgorithm signatureAlgorithmField;

        private string signatureDateField;

        private string signerField;

        private string signatureField;

        private CertificateBlockCertificate[] certificateBlockField;

        private string idField;

        /// <remarks/>
        public string SignatureFormatDescription
        {
            get
            {
                return this.signatureFormatDescriptionField;
            }
            set
            {
                this.signatureFormatDescriptionField = value;
            }
        }

        /// <remarks/>
        public SignatureAlgorithm SignatureAlgorithm
        {
            get
            {
                return this.signatureAlgorithmField;
            }
            set
            {
                this.signatureAlgorithmField = value;
            }
        }

        /// <remarks/>
        public string SignatureDate
        {
            get
            {
                return this.signatureDateField;
            }
            set
            {
                this.signatureDateField = value;
            }
        }

        /// <remarks/>
        public string Signer
        {
            get
            {
                return this.signerField;
            }
            set
            {
                this.signerField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Certificate", IsNullable = false)]
        public CertificateBlockCertificate[] CertificateBlock
        {
            get
            {
                return this.certificateBlockField;
            }
            set
            {
                this.certificateBlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "NCName")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    public partial class CertificateBlockCertificate
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class SignatureAlgorithm
    {

        private string signatureAlgorithmIdentifierField;

        /// <remarks/>
        public string SignatureAlgorithmIdentifier
        {
            get
            {
                return this.signatureAlgorithmIdentifierField;
            }
            set
            {
                this.signatureAlgorithmIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class LockSignatureBlock
    {

        private string signatureFormatDescriptionField;

        private SignatureAlgorithm signatureAlgorithmField;

        private string signatureDateField;

        private string signerField;

        private string signatureField;

        private CertificateBlockCertificate[] certificateBlockField;

        private string signsSignatureBlockField;

        /// <remarks/>
        public string SignatureFormatDescription
        {
            get
            {
                return this.signatureFormatDescriptionField;
            }
            set
            {
                this.signatureFormatDescriptionField = value;
            }
        }

        /// <remarks/>
        public SignatureAlgorithm SignatureAlgorithm
        {
            get
            {
                return this.signatureAlgorithmField;
            }
            set
            {
                this.signatureAlgorithmField = value;
            }
        }

        /// <remarks/>
        public string SignatureDate
        {
            get
            {
                return this.signatureDateField;
            }
            set
            {
                this.signatureDateField = value;
            }
        }

        /// <remarks/>
        public string Signer
        {
            get
            {
                return this.signerField;
            }
            set
            {
                this.signerField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Certificate", IsNullable = false)]
        public CertificateBlockCertificate[] CertificateBlock
        {
            get
            {
                return this.certificateBlockField;
            }
            set
            {
                this.certificateBlockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "NCName")]
        public string signsSignatureBlock
        {
            get
            {
                return this.signsSignatureBlockField;
            }
            set
            {
                this.signsSignatureBlockField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class SignedObject
    {

        private ObjectMetadata objectMetadataField;

        private ObjectContent objectContentField;

        private string vEOVersionField;

        /// <remarks/>
        public ObjectMetadata ObjectMetadata
        {
            get
            {
                return this.objectMetadataField;
            }
            set
            {
                this.objectMetadataField = value;
            }
        }

        /// <remarks/>
        public ObjectContent ObjectContent
        {
            get
            {
                return this.objectContentField;
            }
            set
            {
                this.objectContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string VEOVersion
        {
            get
            {
                return this.vEOVersionField;
            }
            set
            {
                this.vEOVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class ObjectMetadata
    {

        private string objectTypeField;

        private string objectTypeDescriptionField;

        private string objectCreationDateField;

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string ObjectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }

        /// <remarks/>
        public string ObjectTypeDescription
        {
            get
            {
                return this.objectTypeDescriptionField;
            }
            set
            {
                this.objectTypeDescriptionField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "NMTOKEN")]
        public string ObjectCreationDate
        {
            get
            {
                return this.objectCreationDateField;
            }
            set
            {
                this.objectCreationDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class ObjectContent
    {

        private File fileField;

        /// <remarks/>
        public File File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class File
    {

        private FileMetadata fileMetadataField;

        private FileDisposal fileDisposal;

        /// <remarks/>
        public FileMetadata FileMetadata
        {
            get
            {
                return this.fileMetadataField;
            }
            set
            {
                this.fileMetadataField = value;
            }
        }

        public FileDisposal FileDisposal
        {
            get
            {
                return this.fileDisposal;
            }
            set
            {
                this.fileDisposal = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class FileMetadata
    {

        private List<Agent> agentField;

        private RightsManagement rightsManagementField;

        private Title titleField;

        private ContextPath contextPathField;

        private List<Subject> subjectField;

        private List<string> descriptionField;

        private List<string> auxiliaryDescriptionField;

        private List<string> languageField;

        private List<Relation> relation;

        private List<Coverage> coverage;

        private List<Function> function;

        private Date dateField;

        private string typeField;

        private string aggregationLevelField;

        private Format format;

        private string recordIdentifierField;

        private ManagementHistory managementHistoryField;

        private UseHistory useHistory;

        private PreservationHistory preservationHistory;

        private Location location;

        private Disposal disposalField;

        private List<Mandate> mandate;

        private VEOIdentifier vEOIdentifierField;

        /// <summary>
        /// M12 Agent
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<Agent> Agent
        {
            get
            {
                return this.agentField;
            }
            set
            {
                this.agentField = value;
            }
        }

        /// <summary>
        /// M24 Rights Management
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public RightsManagement RightsManagement
        {
            get
            {
                return this.rightsManagementField;
            }
            set
            {
                this.rightsManagementField = value;
            }
        }

        /// <summary>
        /// M32 Title
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public Title Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <summary>
        /// MExtensionContextPath
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public ContextPath ContextPath
        {
            get
            {
                return this.contextPathField;
            }
            set
            {
                this.contextPathField = value;
            }
        }

        /// <summary>
        /// M37 Subject
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public List<Subject> Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <summary>
        /// M40 Description
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Description", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <summary>
        /// M153 Auxiliary Description
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "AuxiliaryDescription", Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public List<string> AuxiliaryDescription
        {
            get
            {
                return this.auxiliaryDescriptionField;
            }
            set
            {
                this.auxiliaryDescriptionField = value;
            }
        }

        /// <summary>
        /// M41 Language
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Language", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<Relation> Relation
        {
            get
            {
                return this.relation;
            }
            set
            {
                this.relation = value;
            }
        }

        /// <summary>
        /// M46 Coverage
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<Coverage> Coverage
        {
            get
            {
                return this.coverage;
            }
            set
            {
                this.coverage = value;
            }
        }

        /// <summary>
        /// M50 Function
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<Function> Function
        {
            get
            {
                return this.function;
            }
            set
            {
                this.function = value;
            }
        }

        /// <summary>
        /// M54 Date
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public Date Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <summary>
        /// M58 Type
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string AggregationLevel
        {
            get
            {
                return this.aggregationLevelField;
            }
            set
            {
                this.aggregationLevelField = value;
            }
        }

        /// <summary>
        /// M60 Format
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public Format Format
        {
            get
            {
                return this.format;
            }
            set
            {
                this.format = value;
            }
        }

        /// <summary>
        /// M65 Record Identifier
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string RecordIdentifier
        {
            get
            {
                return this.recordIdentifierField;
            }
            set
            {
                this.recordIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public ManagementHistory ManagementHistory
        {
            get
            {
                return this.managementHistoryField;
            }
            set
            {
                this.managementHistoryField = value;
            }
        }

        /// <summary>
        /// M71 Use History
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public UseHistory UseHistory
        {
            get
            {
                return this.useHistory;
            }
            set
            {
                this.useHistory = value;
            }
        }

        /// <summary>
        /// M76 Preservation History
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public PreservationHistory PreservationHistory
        {
            get
            {
                return this.preservationHistory;
            }
            set
            {
                this.preservationHistory = value;
            }
        }

        /// <summary>
        /// M83 Location
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public Location Location
        {
            get
            {
                return this.location;
            }
            set
            {
                this.location = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public Disposal Disposal
        {
            get
            {
                return this.disposalField;
            }
            set
            {
                this.disposalField = value;
            }
        }

        /// <summary>
        /// M93 Mandate
        /// </summary>
        [System.Xml.Serialization.XmlElement(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<Mandate> Mandate
        {
            get
            {
                return this.mandate;
            }
            set
            {
                this.mandate = value;
            }
        }

        /// <remarks/>
        public VEOIdentifier VEOIdentifier
        {
            get
            {
                return this.vEOIdentifierField;
            }
            set
            {
                this.vEOIdentifierField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class FileDisposal
    {
        private string disposalSchedule;

        private string disposalDate;

        private string authorizingOfficer;

        public string DisposalSchedule
        {
            get
            {
                return this.disposalSchedule;
            }
            set
            {
                this.disposalSchedule = value;
            }
        }

        public string DisposalDate
        {
            get
            {
                return this.disposalDate;
            }
            set
            {
                this.disposalDate = value;
            }
        }

        public string AuthorizingOfficer
        {
            get
            {
                return this.authorizingOfficer;
            }
            set
            {
                this.authorizingOfficer = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Agent
    {

        private List<string> agentTypeField;

        private List<string> jurisdictionField;

        private List<string> corporateNameField;

        private string corporateId;

        private string personId;

        private List<string> personalName;

        private List<string> sectionName;

        private List<string> positionName;

        private List<string> contactDetails;

        private List<string> email;

        private List<string> digitalSignature;

        /// <summary>
        /// M13 AGENT TYPE
        /// </summary>
        [System.Xml.Serialization.XmlElement("AgentType")]
        public List<string> AgentType
        {
            get
            {
                return this.agentTypeField;
            }
            set
            {
                this.agentTypeField = value;
            }
        }

        /// <summary>
        /// M14 JURISDICTION
        /// </summary>
        [System.Xml.Serialization.XmlElement("Jurisdiction")]
        public List<string> Jurisdiction
        {
            get
            {
                return this.jurisdictionField;
            }
            set
            {
                this.jurisdictionField = value;
            }
        }

        /// <summary>
        /// M15 CORPORATE ID
        /// </summary>
        public string CorporateId
        {
            get
            {
                return this.corporateId;
            }
            set
            {
                this.corporateId = value;
            }
        }

        /// <summary>
        /// M16 CORPORATE NAME
        /// </summary>
        [System.Xml.Serialization.XmlElement("CorporateName")]
        public List<string> CorporateName
        {
            get
            {
                return this.corporateNameField;
            }
            set
            {
                this.corporateNameField = value;
            }
        }

        /// <summary>
        /// M17 PERSON ID
        /// </summary>
        public string PersonId
        {
            get
            {
                return this.personId;
            }
            set
            {
                this.personId = value;
            }
        }

        /// <summary>
        /// M18 PERSONAL NAME
        /// </summary>
        [System.Xml.Serialization.XmlElement("PersonalName")]
        public List<string> PersonalName
        {
            get
            {
                return this.personalName;
            }
            set
            {
                this.personalName = value;
            }
        }
        /// <summary>
        /// M19 SECTION NAME
        /// </summary>
        [System.Xml.Serialization.XmlElement("SectionName")]
        public List<string> SectionName
        {
            get
            {
                return this.sectionName;
            }
            set
            {
                this.sectionName = value;
            }
        }

        /// <summary>
        /// M20 POSITION NAME
        /// </summary>
        [System.Xml.Serialization.XmlElement("PositionName")]
        public List<string> PositionName
        {
            get
            {
                return this.positionName;
            }
            set
            {
                this.positionName = value;
            }
        }

        /// <summary>
        /// M21 CONTACT DETAILS
        /// </summary>
        [System.Xml.Serialization.XmlElement("ContactDetails")]
        public List<string> ContactDetails
        {
            get
            {
                return this.contactDetails;
            }
            set
            {
                this.contactDetails = value;
            }
        }
        /// <summary>
        /// M22 EMAIL
        /// </summary>
        [System.Xml.Serialization.XmlElement("Email")]
        public List<string> Email
        {
            get
            {
                return this.email;
            }
            set
            {
                this.email = value;
            }
        }

        /// <summary>
        /// M23 DIGITAL SIGNATURE (DEPRECATED)
        /// </summary>
        [System.Xml.Serialization.XmlElement("DigitalSignature")]
        public List<string> DigitalSignature
        {
            get
            {
                return this.digitalSignature;
            }
            set
            {
                this.digitalSignature = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class RightsManagement
    {

        private string securityClassificationField;

        private List<string> caveatField;

        private List<string> codeWord;

        private List<string> releasabilityIndicatorField;

        private string accessStatus;

        private List<string> usageConditionField;

        private string encryptionDetails;

        /// <summary>
        /// M25 Security Classification
        /// </summary>
        public string SecurityClassification
        {
            get
            {
                return this.securityClassificationField;
            }
            set
            {
                this.securityClassificationField = value;
            }
        }

        /// <summary>
        /// M26 Caveat
        /// </summary>
        [System.Xml.Serialization.XmlElement("Caveat")]
        public List<string> Caveat
        {
            get
            {
                return this.caveatField;
            }
            set
            {
                this.caveatField = value;
            }
        }

        /// <summary>
        /// M27 Codeword
        /// </summary>
        [System.Xml.Serialization.XmlElement("Codeword")]
        public List<string> Codeword
        {
            get
            {
                return this.codeWord;
            }
            set
            {
                this.codeWord = value;
            }
        }

        /// <summary>
        /// M28 Releasability Indicator
        /// </summary>
        [System.Xml.Serialization.XmlElement("ReleasabilityIndicator")]
        public List<string> ReleasabilityIndicator
        {
            get
            {
                return this.releasabilityIndicatorField;
            }
            set
            {
                this.releasabilityIndicatorField = value;
            }
        }

        /// <summary>
        /// M29 Access Status
        /// </summary>
        public string AccessStatus
        {
            get
            {
                return this.accessStatus;
            }
            set
            {
                this.accessStatus = value;
            }
        }

        /// <summary>
        /// M30 Usage Condition
        /// </summary>
        [System.Xml.Serialization.XmlElement("UsageCondition")]
        public List<string> UsageCondition
        {
            get
            {
                return this.usageConditionField;
            }
            set
            {
                this.usageConditionField = value;
            }
        }

        /// <summary>
        /// M31 Encryption Details
        /// </summary>
        public string EncryptionDetails
        {
            get
            {
                return this.encryptionDetails;
            }
            set
            {
                this.encryptionDetails = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class ContextPath
    {

        private string contextPathDomainField;

        private string contextPathValueField;



        /// <summary>
        /// MExtensionContextPathDomain
        /// </summary>
        public string ContextPathDomain
        {
            get
            {
                return this.contextPathDomainField;
            }
            set
            {
                this.contextPathDomainField = value;
            }
        }

        /// <summary>
        /// MExtensionContextPathValue
        /// </summary>
        public string ContextPathValue
        {
            get
            {
                return this.contextPathValueField;
            }
            set
            {
                this.contextPathValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Title
    {

        private List<string> schemeTypeField;

        private string schemeNameField;

        private string titleWordsField;

        private List<string> alternativeField;

        /// <summary>
        /// M33 Scheme Type
        /// </summary>
        [System.Xml.Serialization.XmlElement("SchemeType")]
        public List<string> SchemeType
        {
            get
            {
                return this.schemeTypeField;
            }
            set
            {
                this.schemeTypeField = value;
            }
        }

        /// <summary>
        /// M34 Scheme Name
        /// </summary>
        public string SchemeName
        {
            get
            {
                return this.schemeNameField;
            }
            set
            {
                this.schemeNameField = value;
            }
        }

        /// <summary>
        /// M35 Title Words
        /// </summary>
        public string TitleWords
        {
            get
            {
                return this.titleWordsField;
            }
            set
            {
                this.titleWordsField = value;
            }
        }

        /// <summary>
        /// M36 Alternative
        /// </summary>
        [System.Xml.Serialization.XmlElement("Alternative")]
        public List<string> Alternative
        {
            get
            {
                return this.alternativeField;
            }
            set
            {
                this.alternativeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class Subject
    {
        private string keywordLevelField;

        private List<string> keywordField;

        /// <summary>
        /// M38 Keyword Level
        /// </summary>
        public string KeywordLevel
        {
            get
            {
                return this.keywordLevelField;
            }
            set
            {
                this.keywordLevelField = value;
            }
        }

        /// <summary>
        /// M39 Keyword
        /// </summary>
        [System.Xml.Serialization.XmlElement("Keyword")]
        public List<string> Keyword
        {
            get
            {
                return this.keywordField;
            }
            set
            {
                this.keywordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class Date
    {

        private string dateTimeCreatedField;

        private string dateTimeTransactedField;

        private string dateTimeRegisteredField;

        private string dateTimeClosedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string DateTimeCreated
        {
            get
            {
                return this.dateTimeCreatedField;
            }
            set
            {
                this.dateTimeCreatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string DateTimeTransacted
        {
            get
            {
                return this.dateTimeTransactedField;
            }
            set
            {
                this.dateTimeTransactedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string DateTimeRegistered
        {
            get
            {
                return this.dateTimeRegisteredField;
            }
            set
            {
                this.dateTimeRegisteredField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public string DateTimeClosed
        {
            get
            {
                return this.dateTimeClosedField;
            }
            set
            {
                this.dateTimeClosedField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Format
    {
        private string mediaFormatField;

        private string dataFormatField;

        private string mediumField;

        private List<string> extentField;

        /// <summary>
        /// M61 Media Format
        /// </summary>
        public string MediaFormat
        {
            get
            {
                return this.mediaFormatField;
            }
            set
            {
                this.mediaFormatField = value;
            }
        }

        /// <summary>
        /// M62 Data Format
        /// </summary>
        public string DataFormat
        {
            get
            {
                return this.dataFormatField;
            }
            set
            {
                this.dataFormatField = value;
            }
        }

        /// <summary>
        /// M63 Medium
        /// </summary>
        public string Medium
        {
            get
            {
                return this.mediumField;
            }
            set
            {
                this.mediumField = value;
            }
        }

        /// <summary>
        /// M64 Extent
        /// </summary>
        [System.Xml.Serialization.XmlElement("Extent")]
        public List<string> Extent
        {
            get
            {
                return this.extentField;
            }
            set
            {
                this.extentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Relation
    {
        private List<string> mRelatedItemID;
        private List<string> mRelationType;
        private List<string> mRelationDescription;

        /// <summary>
        /// M43 Related Item ID
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "RelatedItemId", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> RelatedItemId
        {
            get
            {
                return this.mRelatedItemID;
            }
            set
            {
                this.mRelatedItemID = value;
            }
        }

        /// <summary>
        /// M44 Relation Type
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "RelationType", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> RelationType
        {
            get
            {
                return this.mRelationType;
            }
            set
            {
                this.mRelationType = value;
            }
        }

        /// <summary>
        ///  M45 Relation Description
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "RelationDescription", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> RelationDescription
        {
            get
            {
                return mRelationDescription;
            }
            set
            {
                this.mRelationDescription = value;
            }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Coverage
    {
        private List<string> jurisdictionField;

        private List<string> placeNameField;

        private List<string> periodNameField;

        /// <summary>
        /// M47 Jurisdiction
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Jurisdiction")]
        public List<string> Jurisdiction
        {
            get
            {
                return this.jurisdictionField;
            }
            set
            {
                this.jurisdictionField = value;
            }
        }

        /// <summary>
        /// M48 Place Name
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "PlaceName")]
        public List<string> PlaceName
        {
            get
            {
                return this.placeNameField;
            }
            set
            {
                this.placeNameField = value;
            }
        }

        /// <summary>
        /// M49 Period Name
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "PeriodName")]
        public List<string> PeriodName
        {
            get
            {
                return this.periodNameField;
            }
            set
            {
                this.periodNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Function
    {
        private List<string> functionDescriptorField;

        private List<string> activityDescriptorField;

        private List<string> thirdLevelDescriptorField;

        /// <summary>
        /// ///M51 Function Descriptor
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "FunctionDescriptor")]
        public List<string> FunctionDescriptor
        {
            get
            {
                return this.functionDescriptorField;
            }
            set
            {
                this.functionDescriptorField = value;
            }
        }

        /// <summary>
        /// M52 Activity Descriptor
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "ActivityDescriptor")]
        public List<string> ActivityDescriptor
        {
            get
            {
                return this.activityDescriptorField;
            }
            set
            {
                this.activityDescriptorField = value;
            }
        }

        /// <summary>
        /// M53 Third Level Descriptor
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "ThirdLevelDescriptor")]
        public List<string> ThirdLevelDescriptor
        {
            get
            {
                return this.thirdLevelDescriptorField;
            }
            set
            {
                this.thirdLevelDescriptorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class RelatedItemId
    {
        private VEOIdentifier mVEOIdentifier { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public VEOIdentifier VEOIdentifier
        {
            get
            {
                return this.mVEOIdentifier;
            }
            set
            {
                this.mVEOIdentifier = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class UseHistory
    {
        private List<Use> useField;

        /// <summary>
        /// M72 Use
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Use", Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public List<Use> Use
        {
            get
            {
                return this.useField;
            }
            set
            {
                this.useField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Use
    {
        private string useDateOrTimeField;

        private string useTypeField;

        private string useDescriptionField;

        /// <summary>
        /// M73 Use Date/Time
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string UseDateTime
        {
            get
            {
                return this.useDateOrTimeField;
            }
            set
            {
                this.useDateOrTimeField = value;
            }
        }

        /// <summary>
        /// M74 Use Type
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string UseType
        {
            get
            {
                return this.useTypeField;
            }
            set
            {
                this.useTypeField = value;
            }
        }

        /// <summary>
        /// M75 Use Description
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string UseDescription
        {
            get
            {
                return this.useDescriptionField;
            }
            set
            {
                this.useDescriptionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class PreservationHistory
    {
        private List<Action> actionField;

        private string nextActionField;

        private string nextActionDueField;

        /// <summary>
        /// M77 Action
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Action", Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public List<Action> Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <summary>
        /// M81 Next Action
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string NextAction
        {
            get
            {
                return this.nextActionField;
            }
            set
            {
                this.nextActionField = value;
            }
        }

        /// <summary>
        /// M82 Next Action Due
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string NextActionDue
        {
            get
            {
                return this.nextActionDueField;
            }
            set
            {
                this.nextActionDueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Action
    {
        private string actionDateOrTimeField;

        private string actionTypeField;

        private string actionDescriptionField;

        /// <summary>
        /// M78 Action Date/Time
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string ActionDateTime
        {
            get
            {
                return this.actionDateOrTimeField;
            }
            set
            {
                this.actionDateOrTimeField = value;
            }
        }

        /// <summary>
        /// M79 Action Type
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string ActionType
        {
            get
            {
                return this.actionTypeField;
            }
            set
            {
                this.actionTypeField = value;
            }
        }

        /// <summary>
        /// M80 Action Description
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string ActionDescription
        {
            get
            {
                return this.actionDescriptionField;
            }
            set
            {
                this.actionDescriptionField = value;
            }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Location
    {
        private string currentLocationField;

        private string homeLocationDetailsField;

        private string homeStorageDetailsField;

        private string mRKSID;

        /// <summary>
        /// M84 Current Location
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string CurrentLocation
        {
            get
            {
                return this.currentLocationField;
            }
            set
            {
                this.currentLocationField = value;
            }
        }

        /// <summary>
        /// M85 Home Location Details
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string HomeLocationDetails
        {
            get
            {
                return this.homeLocationDetailsField;
            }
            set
            {
                this.homeLocationDetailsField = value;
            }
        }

        /// <summary>
        /// M86 Home Storage Details
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string HomeStorageDetails
        {
            get
            {
                return this.homeStorageDetailsField;
            }
            set
            {
                this.homeStorageDetailsField = value;
            }
        }

        /// <summary>
        /// M87 RKS ID
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string RKSID
        {
            get
            {
                return this.mRKSID;
            }
            set
            {
                this.mRKSID = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class ManagementHistory
    {

        private List<ManagementEvent> managementEventField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(ElementName = "ManagementEvent", Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
        public List<ManagementEvent> ManagementEvent
        {
            get
            {
                return this.managementEventField;
            }
            set
            {
                this.managementEventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class ManagementEvent
    {

        private string eventDateTimeField;

        private string eventTypeField;

        private string eventDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string EventDateTime
        {
            get
            {
                return this.eventDateTimeField;
            }
            set
            {
                this.eventDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public string EventDescription
        {
            get
            {
                return this.eventDescriptionField;
            }
            set
            {
                this.eventDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Disposal
    {

        private List<string> disposalAuthorisationField;

        private string sentenceField;

        private string disposalActionDueField;

        private string disposalStatus;

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(ElementName = "DisposalAuthorisation", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> DisposalAuthorisation
        {
            get
            {
                return this.disposalAuthorisationField;
            }
            set
            {
                this.disposalAuthorisationField = value;
            }
        }

        /// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
        public string Sentence
        {
            get
            {
                return this.sentenceField;
            }
            set
            {
                this.sentenceField = value;
            }
        }

        /// <summary>
        /// M91 Disposal Action Due
        /// </summary>
        public string DisposalActionDue
        {
            get
            {
                return this.disposalActionDueField;
            }
            set
            {
                this.disposalActionDueField = value;
            }
        }

        public string DisposalStatus
        {
            get
            {
                return this.disposalStatus;
            }
            set
            {
                this.disposalStatus = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html", IsNullable = false)]
    public partial class Mandate
    {
        private List<string> mandateTypeField;

        private List<string> refersToField;

        private List<string> mandateNameField;

        private List<string> mandateReferenceField;

        private List<string> requirementField;

        /// <summary>
        /// M94 Mandate Type
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "MandateType", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> MandateType
        {
            get
            {
                return this.mandateTypeField;
            }
            set
            {
                this.mandateTypeField = value;
            }
        }

        /// <summary>
        /// M95 Refers To
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "RefersTo", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> RefersTo
        {
            get
            {
                return this.refersToField;
            }
            set
            {
                this.refersToField = value;
            }
        }

        /// <summary>
        /// M96 Mandate Name
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "MandateName", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> MandateName
        {
            get
            {
                return this.mandateNameField;
            }
            set
            {
                this.mandateNameField = value;
            }
        }

        /// <summary>
        /// M97 Mandate Reference
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "MandateReference", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> MandateReference
        {
            get
            {
                return this.mandateReferenceField;
            }
            set
            {
                this.mandateReferenceField = value;
            }
        }

        /// <summary>
        /// M98 Requirement
        /// </summary>
        [System.Xml.Serialization.XmlElement(ElementName = "Requirement", Namespace = "http://www.naa.gov.au/recordkeeping/control/rkms/contents.html")]
        public List<string> Requirement
        {
            get
            {
                return this.requirementField;
            }
            set
            {
                this.requirementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class VEOIdentifier
    {

        private Text agencyIdentifierField;

        private Text seriesIdentifierField;

        private Text fileIdentifierField;

        /// <remarks/>
        public Text AgencyIdentifier
        {
            get
            {
                return this.agencyIdentifierField;
            }
            set
            {
                this.agencyIdentifierField = value;
            }
        }

        /// <remarks/>
        public Text SeriesIdentifier
        {
            get
            {
                return this.seriesIdentifierField;
            }
            set
            {
                this.seriesIdentifierField = value;
            }
        }

        /// <remarks/>
        public Text FileIdentifier
        {
            get
            {
                return this.fileIdentifierField;
            }
            set
            {
                this.fileIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.prov.vic.gov.au/gservice/standard/pros99007.htm", IsNullable = false)]
    public partial class CertificateBlock
    {

        private byte[][] certificateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Certificate")]
        public byte[][] Certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
    }
}