/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
using System;
using System.Globalization;
using System.Runtime.Serialization;

namespace Microsoft365.Authentication.ADAL
{
	/// <summary>
	/// The exception type thrown when an error occurs during token acquisition.
	/// </summary>
	[Serializable]
	public class AdalException : Exception
	{
		internal enum ErrorFormat
		{
			Json,
			Other
		}

		/// <summary>
		/// Gets the protocol error code returned by the service or generated by client. This is the code you can rely on for exception handling.
		/// </summary>
		public string ErrorCode
		{
			get;
			private set;
		}

		/// <summary>
		///  Initializes a new instance of the exception class.
		/// </summary>
		public AdalException()
			: base("Unknown error")
		{
			ErrorCode = "unknown_error";
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		public AdalException(string errorCode)
			: base(GetErrorMessage(errorCode))
		{
			ErrorCode = errorCode;
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code and error message.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="message">The error message that explains the reason for the exception.</param>
		public AdalException(string errorCode, string message)
			: base(message)
		{
			ErrorCode = errorCode;
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code and a reference to the inner exception that is the cause of
		///  this exception.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="innerException">The exception that is the cause of the current exception, or a null reference if no inner exception is specified. It may especially contain the actual error message returned by the service.</param>
		public AdalException(string errorCode, Exception innerException)
			: base(GetErrorMessage(errorCode), innerException)
		{
			ErrorCode = errorCode;
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code, error message and a reference to the inner exception that is the cause of
		///  this exception.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="message">The error message that explains the reason for the exception.</param>
		/// <param name="innerException">The exception that is the cause of the current exception, or a null reference if no inner exception is specified. It may especially contain the actual error message returned by the service.</param>
		public AdalException(string errorCode, string message, Exception innerException)
			: base(message, innerException)
		{
			ErrorCode = errorCode;
		}

		/// <summary>
		/// Creates and returns a string representation of the current exception.
		/// </summary>
		/// <returns>A string representation of the current exception.</returns>
		public override string ToString()
		{
			return base.ToString() + string.Format(CultureInfo.InvariantCulture, "\n\tErrorCode: {0}", new object[1]
			{
				ErrorCode
			});
		}

		/// <summary>
		/// Initializes a new instance of the exception class with serialized data.
		/// </summary>
		/// <param name="info">The System.Runtime.Serialization.SerializationInfo that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The System.Runtime.Serialization.StreamingContext that contains contextual information about the source or destination.</param>
		protected AdalException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
			ErrorCode = info.GetString("ErrorCode");
		}

		/// <summary>
		/// Sets the System.Runtime.Serialization.SerializationInfo with information about the exception.
		/// </summary>
		/// <param name="info">The System.Runtime.Serialization.SerializationInfo that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The System.Runtime.Serialization.StreamingContext that contains contextual information about the source or destination.</param>
		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			if (info == null)
			{
				throw new ArgumentNullException("info");
			}
			info.AddValue("ErrorCode", ErrorCode);
			base.GetObjectData(info, context);
		}

		private static string GetErrorMessage(string errorCode)
		{
			string text = null;
			switch (errorCode)
			{
			case "invalid_credential_type":
				text = "Invalid credential type";
				break;
			case "identity_protocol_login_url_null":
				text = "The LoginUrl property in identityProvider cannot be null";
				break;
			case "identity_protocol_mismatch":
				text = "No identity provider matches the requested protocol";
				break;
			case "email_address_suffix_mismatch":
				text = "No identity provider email address suffix matches the provided address";
				break;
			case "identity_provider_request_failed":
				text = "Token request to identity provider failed. Check InnerException for more details";
				break;
			}
			if (text == null)
			{
				switch (errorCode)
				{
				case "sts_token_request_failed":
					text = "Token request to security token service failed.  Check InnerException for more details";
					break;
				case "encoded_token_too_long":
					text = "Encoded token size is beyond the upper limit";
					break;
				case "sts_metadata_request_failed":
					text = "Metadata request to Access Control service failed. Check InnerException for more details";
					break;
				case "authority_not_in_valid_list":
					text = "'authority' is not in the list of valid addresses";
					break;
				case "unknown_user_type":
					text = "Unknown User Type";
					break;
				}
			}
			if (text == null)
			{
				switch (errorCode)
				{
				case "unknown_user":
					text = "Could not identify logged in user";
					break;
				case "user_realm_discovery_failed":
					text = "User realm discovery failed";
					break;
				case "accessing_ws_metadata_exchange_failed":
					text = "Accessing WS metadata exchange failed";
					break;
				case "parsing_ws_metadata_exchange_failed":
					text = "Parsing WS metadata exchange failed";
					break;
				}
			}
			if (text == null)
			{
				switch (errorCode)
				{
				case "wstrust_endpoint_not_found":
					text = "WS-Trust endpoint not found in metadata document";
					break;
				case "parsing_wstrust_response_failed":
					text = "Parsing WS-Trust response failed";
					break;
				case "authentication_canceled":
					text = "User canceled authentication";
					break;
				case "network_not_available":
					text = "The network is down so authentication cannot proceed";
					break;
				}
			}
			if (text == null)
			{
				switch (errorCode)
				{
				case "authentication_ui_failed":
					text = "The browser based authentication dialog failed to complete";
					break;
				case "user_interaction_required":
					text = "One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame";
					break;
				case "missing_federation_metadata_url":
					text = "Federation Metadata Url is missing for federated user. This user type is unsupported.";
					break;
				case "integrated_authentication_failed":
					text = "Integrated authentication failed. You may try an alternative authentication method";
					break;
				}
			}
			if (text == null)
			{
				switch (errorCode)
				{
				case "unauthorized_response_expected":
					text = "Unauthorized http response (status code 401) was expected";
					break;
				case "multiple_matching_tokens_detected":
					text = "The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements (e.g. UserId)";
					break;
				case "password_required_for_managed_user":
					text = "Password is required for managed user";
					break;
				case "get_user_name_failed":
					text = "Failed to get user name";
					break;
				default:
					text = "Unknown error";
					break;
				}
			}
			return string.Format(CultureInfo.InvariantCulture, "{0}: {1}", new object[2]
			{
				errorCode,
				text
			});
		}
	}
}