/********************************************************************
 *
 *  PROPRIETARY and CONFIDENTIAL
 *
 *  This file is licensed from, and is a trade secret of:
 *
 *                   AvePoint, Inc.
 *                   525 Washington Blvd, Suite 1400
 *                   Jersey City, NJ 07310
 *                   United States of America
 *                   Telephone: +1-201-793-1111
 *                   WWW: www.avepoint.com
 *
 *  Refer to your License Agreement for restrictions on use,
 *  duplication, or disclosure.
 *
 *  RESTRICTED RIGHTS LEGEND
 *
 *  Use, duplication, or disclosure by the Government is
 *  subject to restrictions as set forth in subdivision
 *  (c)(1)(ii) of the Rights in Technical Data and Computer
 *  Software clause at DFARS 252.227-7013 (Oct. 1988) and
 *  FAR 52.227-19 (C) (June 1987).
 *
 *  Copyright © 2017-2026 AvePoint® Inc. All Rights Reserved. 
 *
 *  Unpublished - All rights reserved under the copyright laws of the United States.
 */
using System;
using System.Globalization;
using System.Net;
using System.Runtime.Serialization;

namespace Microsoft365.Authentication.ADAL
{
	/// <summary>
	/// The exception type thrown when user returned by service does not match user in the request.
	/// </summary>
	[Serializable]
	public class AdalServiceException : AdalException
	{
		/// <summary>
		/// Gets the status code returned from http layer. This status code is either the HttpStatusCode in the inner WebException response or
		/// NavigateError Event Status Code in browser based flow (See http://msdn.microsoft.com/en-us/library/bb268233(v=vs.85).aspx).
		/// You can use this code for purposes such as implementing retry logic or error investigation.
		/// </summary>
		public int StatusCode
		{
			get;
			set;
		}

		/// <summary>
		/// Gets the specific error codes that may be returned by the service.
		/// </summary>
		public string[] ServiceErrorCodes
		{
			get;
			set;
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code and error message.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="message">The error message that explains the reason for the exception.</param>
		public AdalServiceException(string errorCode, string message)
			: base(errorCode, message)
		{
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code and a reference to the inner exception that is the cause of
		///  this exception.
		/// </summary>
		/// <param name="errorCode">The error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="innerException">The exception that is the cause of the current exception, or a null reference if no inner exception is specified. It may especially contain the actual error message returned by the service.</param>
		public AdalServiceException(string errorCode, WebException innerException)
			: base(errorCode, innerException)
		{
		}

		/// <summary>
		///  Initializes a new instance of the exception class with a specified
		///  error code, error message and a reference to the inner exception that is the cause of
		///  this exception.
		/// </summary>
		/// <param name="errorCode">The protocol error code returned by the service or generated by client. This is the code you can rely on for exception handling.</param>
		/// <param name="message">The error message that explains the reason for the exception.</param>
		/// <param name="serviceErrorCodes">The specific error codes that may be returned by the service.</param>
		/// <param name="innerException">The exception that is the cause of the current exception, or a null reference if no inner exception is specified. It may especially contain the actual error message returned by the service.</param>
		public AdalServiceException(string errorCode, string message, string[] serviceErrorCodes, WebException innerException)
			: base(errorCode, message, innerException)
		{
			StatusCode = (int)(NetworkPlugin.HttpWebRequestFactory.CreateResponse(innerException.Response)?.StatusCode ?? ((HttpStatusCode)0));
			ServiceErrorCodes = serviceErrorCodes;
		}

		/// <summary>
		/// Creates and returns a string representation of the current exception.
		/// </summary>
		/// <returns>A string representation of the current exception.</returns>
		public override string ToString()
		{
			return base.ToString() + string.Format(CultureInfo.InvariantCulture, "\n\tStatusCode: {0}", new object[1]
			{
				StatusCode
			});
		}

		/// <summary>
		/// Initializes a new instance of the exception class with serialized data.
		/// </summary>
		/// <param name="info">The System.Runtime.Serialization.SerializationInfo that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The System.Runtime.Serialization.StreamingContext that contains contextual information about the source or destination.</param>
		protected AdalServiceException(SerializationInfo info, StreamingContext context)
			: base(info, context)
		{
			StatusCode = info.GetInt32("StatusCode");
		}

		/// <summary>
		/// Sets the System.Runtime.Serialization.SerializationInfo with information about the exception.
		/// </summary>
		/// <param name="info">The System.Runtime.Serialization.SerializationInfo that holds the serialized object data about the exception being thrown.</param>
		/// <param name="context">The System.Runtime.Serialization.StreamingContext that contains contextual information about the source or destination.</param>
		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			if (info == null)
			{
				throw new ArgumentNullException("info");
			}
			info.AddValue("StatusCode", StatusCode);
			base.GetObjectData(info, context);
		}
	}
}