<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <OutputType>Library</OutputType>
    <RootNamespace>AvePoint.RA.SharePoint</RootNamespace>
    <AssemblyName>RevIMSharePoint</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\RAScheduleJob\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\bin\Release</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\DocaveReference\DocAveStandard.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>
  <ItemGroup>
    <Compile Remove="ManualApprovalTimer\**" />
    <EmbeddedResource Remove="ManualApprovalTimer\**" />
    <EntityDeploy Remove="ManualApprovalTimer\**" />
    <None Remove="ManualApprovalTimer\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\GlobalCommon\GCommonContract\DocAve.GCommonContract.csproj" />
    <ProjectReference Include="..\Common\GlobalCommon\GCommonFileReceiver\GCommonFileReceiver.csproj" />
    <ProjectReference Include="..\Common\GlobalCommon\GCommonFileSender\GCommonFileSender.csproj" />
    <ProjectReference Include="..\Common\GlobalCommon\GCommonNetWork\GCommonNetwork.csproj" />
    <ProjectReference Include="..\Common\GlobalCommon\GCommonUtility\DocAve.GCommonUtility.csproj" />
    <ProjectReference Include="..\Common\Microsoft365\Authentication\Microsoft365.Authentication.csproj" />
    <ProjectReference Include="..\Common\SPAPIWrapper\AveObjectModel.Client\AveObjectModel.Common\AveObjectModel.Common.csproj" />
    <ProjectReference Include="..\Common\VCService30\CommonUtility30\DocAve.CommonUtility30.csproj" />
    <ProjectReference Include="..\Common\Wrapper\Wrapper.Backup\Wrapper.Backup.csproj" />
    <ProjectReference Include="..\Common\Wrapper\Wrapper.Common\Wrapper.Common.csproj" />
    <ProjectReference Include="..\Common\Wrapper\Wrapper.Discovery\Wrapper.Discovery.csproj" />
    <ProjectReference Include="..\Common\Wrapper\Wrapper.Restore\Wrapper.Restore.csproj" />
    <ProjectReference Include="..\Common\Wrapper\Wrapper.Workflow\Wrapper.Workflow.csproj" />
    <ProjectReference Include="..\Media\Media.Service.ArchiverBackup\Media.Service.ArchiverBackup.csproj" />
    <ProjectReference Include="..\Media\Media.Service.DomainModel\Media.Service.DomainModel.csproj" />
    <ProjectReference Include="..\Merged18NResources\Merged18NResources.csproj" />
    <ProjectReference Include="..\RAArchiverCommon\RAArchiverCommon.csproj" />
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
    <ProjectReference Include="..\RAContract.Global\RAContract.Global.csproj" />
    <ProjectReference Include="..\RACommonUtility\RACommonUtility.csproj" />
    <ProjectReference Include="..\RACommon\RACommon.csproj" />
    <ProjectReference Include="..\RAContract\RAContract.csproj" />
    <ProjectReference Include="..\RADataBroker\RADataBroker.csproj" />
    <ProjectReference Include="..\RADB\RADB.csproj" />
    <ProjectReference Include="..\RAExportCommon\RAExportCommon.csproj" />
    <ProjectReference Include="..\RAGoogle\RAGoogle.csproj" />
    <ProjectReference Include="..\RAI18N\RAI18N.csproj" />
    <ProjectReference Include="..\RAManualApprovalCommon\RAManualApprovalCommon.csproj" />
    <ProjectReference Include="..\RAPhysical\RAPhysical.csproj" />
    <ProjectReference Include="..\VectorDataCenter\VectorDataCenter.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.1.1" />
	<PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="DataOrchestration.Tag.Sdk" Version="1.1.69" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="8.1.2" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="util.ai.text.extractor" Version="6.10.11" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="RMExplorer\RMExplorerMove\RMExplorerMoveCommon\RelatedItemInfo\RelatedItemInfo.cs" />
    <Compile Remove="RMSharePointColumn\RMIncrementalUniqueIDSettingProcessor.cs" />
    <Compile Remove="RMSharePointColumn\RMUniqueIDSettingProcessor.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Archiver\ArchiverMultiTask\" />
    <Folder Include="Archiver\LogicBackup\" />
    <Folder Include="Archiver\Deletion\" />
    <Folder Include="Archiver\MediaCenter\" />
    <Folder Include="Archiver\SPOjbects.RecordManager\RM.Backup\SPStub\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RMSharePointColumn\automapper.lic" />
  </ItemGroup>
</Project>