<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SignAssembly>false</SignAssembly>
    <AssemblyOriginatorKeyFile>DocAveStandard.snk</AssemblyOriginatorKeyFile>
    <UserSecretsId>c6b46a93-a702-4f5e-ba44-1b885acd3f43</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Utils\CertificateHelper.cs" />
    <Compile Remove="Utils\ConfigurationUtil.cs" />
  </ItemGroup>
	<PropertyGroup>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageReference Include="Cloud.Sdk.Amls.Ics" Version="4.12.30" />
    <PackageReference Include="Cloud.Sdk.Aos" Version="5.6.17" />
    <PackageReference Include="Cloud.Sdk.AosModernApi" Version="6.8.39" />
    <PackageReference Include="Cloud.Sdk.Cipher" Version="4.12.30" />
    <PackageReference Include="Cloud.Sdk.CloudInsights" Version="5.4.70" />
    <PackageReference Include="Cloud.Sdk.Core" Version="6.10.102" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="MessagePack" Version="3.1.7" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.15.0" />
    <PackageReference Include="Microsoft.NET.StringTools" Version="18.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.0.7" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Formats.Asn1" Version="10.0.2" />
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
    <PackageReference Include="System.Private.Uri" Version="4.3.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.10" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="util" Version="4.12.7" />
    <PackageReference Include="util.security" Version="4.12.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RACommon.Global\RACommon.Global.csproj" />
    <ProjectReference Include="..\..\RARedisCache\RedisService.csproj" />
    <ProjectReference Include="..\HybirdProxy\HybridProxy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Log\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="DocAveStandard.snk">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
