<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Microsoft365.Graph.Extensions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Microsoft365.Graph\Microsoft365.Graph.csproj" />
  </ItemGroup>
</Project>
