<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AvePoint.RA.VectorDataCenter</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="config\**" />
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="config\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="config\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.57.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RACommon.Global\RACommon.Global.csproj" />
    <ProjectReference Include="..\RACommon\RACommon.csproj" />
    <ProjectReference Include="..\RAI.Core\RAI.Core.csproj" />
    <ProjectReference Include="..\RAContract.Global\RAContract.Global.csproj" />
    <ProjectReference Include="..\RADB\RADB.csproj" />
  </ItemGroup>

</Project>
